<template>
  <section>
    <header class="d-flex flex-wrap justify-content-between align-items-end gap-3 mb-4">
      <div><RouterLink to="/cms/courses" class="small text-secondary"><i class="bi bi-arrow-left"></i> Danh sách khóa học</RouterLink><h1 class="page-title mt-2">Nội dung: {{ course.title }}</h1><p class="page-subtitle mb-0">Thêm, sửa, xóa chương/bài học và chọn video dùng chung từ thư viện.</p></div>
      <div class="d-flex gap-2"><RouterLink class="btn btn-light" to="/cms/videos"><i class="bi bi-collection-play"></i> Thư viện video</RouterLink><button class="btn btn-brand" @click="openChapter()"><i class="bi bi-plus-lg"></i> Thêm chương</button></div>
    </header>
    <div v-if="message" :class="['alert',messageType==='danger'?'alert-danger':'alert-success']">{{ message }}</div>
    <div v-if="loading" class="app-card p-5 text-center"><span class="spinner-border text-success"></span></div>
    <div v-else class="builder">
      <article v-for="(chapter,index) in chapters" :key="chapter.id" class="app-card chapter-card">
        <header><span class="number">{{ index+1 }}</span><div class="chapter-copy"><strong>{{ chapter.title }}</strong><small>{{ chapter.lessons.length }} bài học • {{ chapter.status==='ACTIVE'?'Hoạt động':'Tạm ẩn' }}</small></div><div class="ms-auto d-flex gap-2"><button class="btn btn-light btn-sm" title="Sửa chương" @click="openChapter(chapter)"><i class="bi bi-pencil"></i></button><button class="btn btn-light btn-sm text-danger" title="Xóa chương" @click="askDelete('chapter',chapter)"><i class="bi bi-trash"></i></button></div></header>
        <div v-for="lesson in chapter.lessons" :key="lesson.id" class="lesson">
          <span class="type"><i :class="['bi',lesson.lessonType.includes('VIDEO')?'bi-play-btn':'bi-file-earmark-text']"></i></span>
          <div class="lesson-copy"><strong>{{ lesson.title }}</strong><small>{{ lessonTypeLabel(lesson.lessonType) }} • {{ formatTime(lesson.durationSeconds) }}<template v-if="lesson.videoTitle"> • {{ lesson.videoTitle }}</template></small></div>
          <span :class="['badge',lesson.status==='ACTIVE'?'badge-soft-success':'badge-soft-warning']">{{ lesson.status==='ACTIVE'?'Hoạt động':'Tạm ẩn' }}</span>
          <div class="lesson-actions"><RouterLink v-if="lesson.videoId" class="btn btn-light btn-sm" :to="`/cms/videos/${lesson.videoId}/editor`" title="Biên tập video"><i class="bi bi-sliders"></i></RouterLink><button v-else-if="lesson.lessonType.includes('VIDEO')" class="btn btn-blue btn-sm" title="Chọn video từ thư viện" @click="openVideoPicker(lesson)"><i class="bi bi-collection-play"></i></button><button class="btn btn-light btn-sm" title="Sửa bài học" @click="openLesson(chapter,lesson)"><i class="bi bi-pencil"></i></button><button class="btn btn-light btn-sm text-danger" title="Xóa bài học" @click="askDelete('lesson',lesson)"><i class="bi bi-trash"></i></button></div>
        </div>
        <div v-if="!chapter.lessons.length" class="empty-lessons">Chương này chưa có bài học.</div>
        <button class="add-lesson" @click="openLesson(chapter)"><i class="bi bi-plus-circle"></i> Thêm bài học</button>
      </article>
      <div v-if="!chapters.length" class="app-card empty-state"><i class="bi bi-journal-plus"></i><h2>Chưa có chương</h2><p>Tạo chương đầu tiên để bắt đầu xây dựng nội dung khóa học.</p><button class="btn btn-brand" @click="openChapter()">Thêm chương</button></div>
    </div>

    <div v-if="chapterModal" class="modal-mask" @click.self="chapterModal=false"><form class="app-card form-modal" @submit.prevent="saveChapter"><div class="modal-heading"><div><small>CHƯƠNG KHÓA HỌC</small><h2>{{ chapterForm.id?'Sửa chương':'Thêm chương' }}</h2></div><button type="button" class="btn-close" @click="chapterModal=false"></button></div><div class="row g-3"><div class="col-12"><label class="form-label">Tên chương</label><input v-model.trim="chapterForm.title" class="form-control" required maxlength="500"></div><div class="col-12"><label class="form-label">Mô tả</label><textarea v-model.trim="chapterForm.description" class="form-control" rows="3"></textarea></div><div class="col-md-6"><label class="form-label">Thứ tự</label><input v-model.number="chapterForm.sortOrder" class="form-control" type="number" min="1" required></div><div class="col-md-6"><label class="form-label">Trạng thái</label><select v-model="chapterForm.status" class="form-select"><option value="ACTIVE">Hoạt động</option><option value="INACTIVE">Tạm ẩn</option></select></div></div><div class="modal-actions"><button type="button" class="btn btn-light" @click="chapterModal=false">Hủy</button><button class="btn btn-brand" :disabled="saving"><span v-if="saving" class="spinner-border spinner-border-sm me-1"></span>Lưu chương</button></div></form></div>

    <div v-if="lessonModal" class="modal-mask" @click.self="lessonModal=false"><form class="app-card form-modal" @submit.prevent="saveLesson"><div class="modal-heading"><div><small>BÀI HỌC</small><h2>{{ lessonForm.id?'Sửa bài học':'Thêm bài học' }}</h2></div><button type="button" class="btn-close" @click="lessonModal=false"></button></div><div class="row g-3"><div class="col-12"><label class="form-label">Tên bài học</label><input v-model.trim="lessonForm.title" class="form-control" required maxlength="500"></div><div class="col-12"><label class="form-label">Mô tả</label><textarea v-model.trim="lessonForm.description" class="form-control" rows="3"></textarea></div><div class="col-md-6"><label class="form-label">Loại bài</label><select v-model="lessonForm.lessonType" class="form-select"><option value="INTERACTIVE_VIDEO">Video tương tác</option><option value="VIDEO">Video</option><option value="QUIZ">Bài kiểm tra</option><option value="DOCUMENT">Tài liệu</option></select></div><div class="col-md-3"><label class="form-label">Thứ tự</label><input v-model.number="lessonForm.sortOrder" class="form-control" type="number" min="1"></div><div class="col-md-3"><label class="form-label">Điểm đạt</label><input v-model.number="lessonForm.passingScore" class="form-control" type="number" min="0" max="100"></div><div class="col-md-6"><label class="form-label">Trạng thái</label><select v-model="lessonForm.status" class="form-select"><option value="ACTIVE">Hoạt động</option><option value="INACTIVE">Tạm ẩn</option></select></div><div class="col-md-6 check-row"><input id="requiredLesson" v-model="lessonForm.isRequired" class="form-check-input" type="checkbox"><label for="requiredLesson">Bài học bắt buộc</label></div></div><div class="modal-actions"><button type="button" class="btn btn-light" @click="lessonModal=false">Hủy</button><button class="btn btn-brand" :disabled="saving"><span v-if="saving" class="spinner-border spinner-border-sm me-1"></span>Lưu bài học</button></div></form></div>

    <div v-if="videoModal" class="modal-mask" @click.self="videoModal=false"><div class="app-card library-modal"><div class="modal-heading"><div><small>VIDEO DÙNG CHUNG</small><h2>Chọn video cho “{{ targetLesson?.title }}”</h2><p>Một video thư viện có thể gắn vào nhiều môn và bài học.</p></div><button class="btn-close" @click="videoModal=false"></button></div><div class="library-toolbar"><input v-model.trim="videoSearch" class="form-control" placeholder="Tìm theo tên video hoặc tên file..."><RouterLink class="btn btn-light text-nowrap" to="/cms/videos"><i class="bi bi-plus-lg"></i> Thêm video mới</RouterLink></div><div class="video-list"><button v-for="asset in videoAssets" :key="asset.id" class="video-item" :disabled="saving" @click="attachVideo(asset)"><span class="video-icon"><i class="bi bi-play-fill"></i></span><div><strong>{{ asset.title }}</strong><small>{{ formatTime(asset.durationSeconds) }} • Đang dùng ở {{ asset.usageCount }} bài</small></div><span class="btn btn-blue btn-sm">Chọn</span></button><div v-if="!videoAssets.length" class="p-4 text-center text-secondary">Không tìm thấy video phù hợp.</div></div></div></div>

    <div v-if="deleteTarget" class="modal-mask" @click.self="deleteTarget=null"><div class="app-card confirm-modal"><span class="delete-icon"><i class="bi bi-trash"></i></span><h2>Xóa {{ deleteTarget.type==='chapter'?'chương':'bài học' }}?</h2><p>{{ deleteTarget.type==='chapter'?'Các bài học bên trong cũng sẽ bị ẩn khỏi hệ thống.':'Bài học sẽ bị ẩn khỏi khóa học và LMS.' }}</p><div class="modal-actions"><button class="btn btn-light" @click="deleteTarget=null">Hủy</button><button class="btn btn-danger" :disabled="saving" @click="removeTarget">Xóa</button></div></div></div>
  </section>
</template>

<script setup>
import { onMounted,reactive,ref,watch } from 'vue'
import { useRoute } from 'vue-router'
import axiosClient from '../../api/axiosClient'
import { formatInteractionTime } from '../../utils/learningRules'

const route=useRoute(),courseId=Number(route.params.id),course=reactive({id:courseId,title:'Khóa học'}),chapters=ref([]),loading=ref(true),saving=ref(false),message=ref(''),messageType=ref('success')
const chapterModal=ref(false),lessonModal=ref(false),videoModal=ref(false),deleteTarget=ref(null),targetLesson=ref(null),videoAssets=ref([]),videoSearch=ref('')
const chapterForm=reactive(blankChapter()),lessonForm=reactive(blankLesson())
const pick=(source,...names)=>names.map(name=>source?.[name]).find(value=>value!==undefined&&value!==null)
const formatTime=formatInteractionTime
let videoTimer
watch(videoSearch,()=>{clearTimeout(videoTimer);videoTimer=setTimeout(loadVideoAssets,250)})
onMounted(load)

async function load(){loading.value=true;try{const [courseData,content]=await Promise.all([axiosClient.get(`/courses/${courseId}`),axiosClient.get(`/courses/${courseId}/content`,{params:{_fresh:Date.now()}})]);course.title=pick(courseData,'Title','title')||course.title;const chapterRows=pick(content,'chapters','Chapters')||[],lessonRows=pick(content,'lessons','Lessons')||[];chapters.value=chapterRows.map((row,index)=>{const id=Number(pick(row,'Id','id'));return{id,title:pick(row,'Title','title'),description:pick(row,'Description','description')||'',sortOrder:Number(pick(row,'SortOrder','sortOrder')||index+1),status:pick(row,'Status','status')||'ACTIVE',lessons:lessonRows.filter(x=>Number(pick(x,'ChapterId','chapterId'))===id).map(mapLesson)}})}catch(error){show(error.message,'danger')}finally{loading.value=false}}
function mapLesson(row,index){return{id:Number(pick(row,'Id','id')),chapterId:Number(pick(row,'ChapterId','chapterId')),title:pick(row,'Title','title'),description:pick(row,'Description','description')||'',lessonType:pick(row,'LessonType','lessonType')||'INTERACTIVE_VIDEO',durationSeconds:Number(pick(row,'DurationSeconds','durationSeconds')||0),sortOrder:Number(pick(row,'SortOrder','sortOrder')||index+1),isRequired:Boolean(pick(row,'IsRequired','isRequired')),passingScore:Number(pick(row,'PassingScore','passingScore')||0),status:pick(row,'Status','status')||'ACTIVE',videoId:Number(pick(row,'VideoId','videoId')||0),videoAssetId:Number(pick(row,'VideoAssetId','videoAssetId')||0),videoTitle:pick(row,'VideoTitle','videoTitle')||''}}
function blankChapter(){return{id:0,title:'',description:'',sortOrder:1,status:'ACTIVE'}}
function blankLesson(){return{id:0,chapterId:0,title:'',description:'',lessonType:'INTERACTIVE_VIDEO',durationSeconds:0,sortOrder:1,isRequired:true,passingScore:0,status:'ACTIVE'}}
function openChapter(item=null){Object.assign(chapterForm,item?{id:item.id,title:item.title,description:item.description,sortOrder:item.sortOrder,status:item.status}:{...blankChapter(),sortOrder:chapters.value.length+1});chapterModal.value=true}
function openLesson(chapter,item=null){Object.assign(lessonForm,item?{...item}:{...blankLesson(),chapterId:chapter.id,sortOrder:chapter.lessons.length+1});lessonForm.chapterId=chapter.id;lessonModal.value=true}
async function saveChapter(){saving.value=true;try{const body={title:chapterForm.title,description:chapterForm.description||null,sortOrder:chapterForm.sortOrder,status:chapterForm.status};if(chapterForm.id)await axiosClient.put(`/chapters/${chapterForm.id}`,body);else await axiosClient.post(`/courses/${courseId}/chapters`,body);chapterModal.value=false;await load();show('Đã lưu chương vào SQL.')}catch(error){show(error.message,'danger')}finally{saving.value=false}}
async function saveLesson(){saving.value=true;try{const body={title:lessonForm.title,description:lessonForm.description||null,lessonType:lessonForm.lessonType,durationSeconds:Math.max(0,Number(lessonForm.durationSeconds)||0),sortOrder:lessonForm.sortOrder,isRequired:lessonForm.isRequired,passingScore:Number(lessonForm.passingScore)||0,status:lessonForm.status};if(lessonForm.id)await axiosClient.put(`/lessons/${lessonForm.id}`,body);else await axiosClient.post(`/chapters/${lessonForm.chapterId}/lessons`,body);lessonModal.value=false;await load();show('Đã lưu bài học vào SQL.')}catch(error){show(error.message,'danger')}finally{saving.value=false}}
function askDelete(type,item){deleteTarget.value={type,item}}
async function removeTarget(){saving.value=true;try{await axiosClient.delete(`/${deleteTarget.value.type==='chapter'?'chapters':'lessons'}/${deleteTarget.value.item.id}`);deleteTarget.value=null;await load();show('Đã xóa nội dung khỏi khóa học.')}catch(error){show(error.message,'danger')}finally{saving.value=false}}
async function openVideoPicker(lesson){targetLesson.value=lesson;videoSearch.value='';await loadVideoAssets();videoModal.value=true}
async function loadVideoAssets(){try{const rows=await axiosClient.get('/video-library',{params:{search:videoSearch.value||undefined,_fresh:Date.now()}});videoAssets.value=(Array.isArray(rows)?rows:[]).map(row=>({id:Number(pick(row,'Id','id')),title:pick(row,'Title','title'),durationSeconds:Number(pick(row,'DurationSeconds','durationSeconds')||0),usageCount:Number(pick(row,'UsageCount','usageCount')||0)}))}catch(error){show(error.message,'danger')}}
async function attachVideo(asset){saving.value=true;try{const result=await axiosClient.post(`/lessons/${targetLesson.value.id}/video-library/${asset.id}`,{allowSeek:false,allowSpeed:true,requiredWatchPercent:80});const videoId=Number(pick(result,'id','Id'));videoModal.value=false;await load();show(`Đã gắn “${asset.title}” vào bài học. Video này vẫn có thể dùng tiếp cho môn khác.`);if(videoId) targetLesson.value=null}catch(error){show(error.message,'danger')}finally{saving.value=false}}
function lessonTypeLabel(type){return({INTERACTIVE_VIDEO:'Video tương tác',VIDEO:'Video',QUIZ:'Bài kiểm tra',DOCUMENT:'Tài liệu'})[type]||type}
function show(text,type='success'){message.value=text;messageType.value=type;window.scrollTo({top:0,behavior:'smooth'})}
</script>

<style scoped>
.builder{display:grid;gap:1rem}.chapter-card{overflow:hidden}.chapter-card>header{display:flex;align-items:center;gap:.8rem;padding:1rem 1.2rem;background:#f8faf9}.chapter-copy,.lesson-copy{display:grid;min-width:0}.chapter-card small{color:#75857f}.number{width:34px;height:34px;border-radius:8px;background:var(--eduvers-base);color:white;display:grid;place-items:center;font-weight:800}.lesson{display:grid;grid-template-columns:42px minmax(0,1fr) auto auto;align-items:center;gap:.8rem;padding:.9rem 1.2rem;border-top:1px solid #e8eeeb}.type{width:38px;height:38px;border-radius:9px;background:var(--eduvers-primary);color:var(--eduvers-black);display:grid;place-items:center}.lesson strong{font-size:.9rem}.lesson-actions{display:flex;gap:.4rem}.add-lesson{border:0;background:white;color:var(--eduvers-base);font-weight:750;padding:1rem 1.2rem;text-align:left}.empty-lessons{padding:1rem 1.2rem 0;color:#75857f}.empty-state{text-align:center;padding:3.5rem}.empty-state>i{font-size:3rem;color:var(--eduvers-base)}.empty-state h2{font-size:1.25rem;margin-top:1rem}.empty-state p{color:#75857f}.modal-mask{position:fixed;inset:0;background:rgba(5,24,35,.65);display:grid;place-items:center;z-index:2000;padding:1rem}.form-modal{width:min(720px,96vw);padding:1.5rem;max-height:94vh;overflow:auto}.modal-heading{display:flex;justify-content:space-between;align-items:flex-start;gap:1rem;margin-bottom:1.25rem}.modal-heading small{color:var(--eduvers-base);font-weight:800}.modal-heading h2{font-size:1.35rem;margin:.2rem 0}.modal-heading p{color:#75857f;margin:.3rem 0 0}.modal-actions{display:flex;justify-content:flex-end;gap:.6rem;margin-top:1.5rem}.check-row{display:flex;align-items:end;gap:.55rem;padding-bottom:.65rem}.check-row input{margin:0}.library-modal{width:min(820px,96vw);padding:1.5rem;max-height:92vh;overflow:auto}.library-toolbar{display:flex;gap:.75rem;margin-bottom:1rem}.video-list{display:grid;gap:.6rem}.video-item{border:0;background:#f5f8f7;border-radius:10px;padding:.85rem;display:grid;grid-template-columns:46px 1fr auto;align-items:center;gap:.8rem;text-align:left}.video-item:hover{background:rgba(var(--eduvers-base-rgb),.10)}.video-item>div{display:grid}.video-item small{color:#75857f}.video-icon{width:44px;height:44px;border-radius:9px;background:var(--eduvers-black);color:white;display:grid;place-items:center;font-size:1.25rem}.confirm-modal{width:min(440px,94vw);padding:1.5rem}.confirm-modal h2{font-size:1.25rem;margin:1rem 0 .4rem}.confirm-modal p{color:#75857f}.delete-icon{width:48px;height:48px;border-radius:12px;background:#fde9e9;color:var(--eduvers-base);display:grid;place-items:center}@media(max-width:700px){.lesson{grid-template-columns:38px 1fr}.lesson>.badge{display:none}.lesson-actions{grid-column:2}.library-toolbar{display:grid}.video-item{grid-template-columns:42px 1fr}.video-item>.btn{grid-column:2;justify-self:start}}
</style>
