<template>
  <section>
    <header class="d-flex flex-wrap justify-content-between align-items-end gap-3 mb-4"><div><h1 class="page-title mb-1">Thư viện video</h1><p class="page-subtitle mb-0">Quản lý video dùng chung; một video có thể gắn vào nhiều môn và bài học.</p></div><button class="btn btn-brand" @click="openUpload"><i class="bi bi-cloud-arrow-up"></i> Thêm video</button></header>
    <div v-if="message" :class="['alert',messageType==='danger'?'alert-danger':'alert-success']">{{ message }}</div>
    <div class="app-card p-3 mb-3"><div class="search-box"><i class="bi bi-search"></i><input v-model.trim="search" class="form-control" placeholder="Tìm theo tên video hoặc tên file..."></div></div>
    <div class="app-card p-2"><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Video</th><th>Thời lượng</th><th>Đang sử dụng</th><th>Người tạo</th><th>Ngày tạo</th><th class="text-end">Thao tác</th></tr></thead><tbody><tr v-for="(item,index) in items" :key="item.id"><td><div class="video-name"><span class="video-thumb" :style="{backgroundImage:`url(${thumbnailFor(item,index)})`}"><i class="bi bi-play-fill"></i></span><div><strong>{{ item.title }}</strong><small>{{ item.originalFileName || item.videoUrl || 'Chưa có file' }}</small></div></div></td><td>{{ formatTime(item.durationSeconds) }}</td><td><span class="badge badge-soft-primary">{{ item.usageCount }} bài học</span></td><td>{{ item.createdByName }}</td><td>{{ formatDate(item.createdAt) }}</td><td class="text-end"><RouterLink v-if="item.firstVideoId" class="btn btn-light btn-sm me-1" :to="`/cms/videos/${item.firstVideoId}/editor`" title="Mở một bản đang dùng"><i class="bi bi-sliders"></i></RouterLink><button class="btn btn-light btn-sm text-danger" :disabled="item.usageCount>0" :title="item.usageCount>0?'Video đang được sử dụng':'Xóa video'" @click="remove(item)"><i class="bi bi-trash"></i></button></td></tr><tr v-if="!loading&&!items.length"><td colspan="6" class="text-center text-secondary py-5">Chưa có video phù hợp trong thư viện.</td></tr></tbody></table></div><div v-if="loading" class="text-center p-4"><span class="spinner-border text-success"></span></div></div>

    <div v-if="uploadModal" class="modal-mask" @click.self="uploadModal=false"><form class="app-card upload-modal" @submit.prevent="save"><div class="modal-heading"><div><small>VIDEO DÙNG CHUNG</small><h2>Thêm video vào thư viện</h2></div><button type="button" class="btn-close" @click="uploadModal=false"></button></div><label v-if="!form.videoUrl" class="drop-zone" :class="{disabled:uploading}"><i class="bi bi-cloud-arrow-up"></i><strong>{{ uploading?`Đang tải lên ${uploadProgress}%`:'Chọn file video' }}</strong><span>MP4, WebM, OGV hoặc MOV; file lưu trong project.</span><input class="visually-hidden" type="file" accept="video/mp4,video/webm,video/ogg,video/quicktime" :disabled="uploading" @change="upload"></label><video v-else ref="metadataVideo" :src="playbackUrl" controls preload="metadata" @loadedmetadata="readDuration"></video><div class="row g-3 mt-1"><div class="col-md-8"><label class="form-label">Tên video</label><input v-model.trim="form.title" class="form-control" required maxlength="500"></div><div class="col-md-4"><label class="form-label">Thời lượng (giây)</label><input v-model.number="form.durationSeconds" class="form-control" type="number" min="1" required></div><div class="col-12"><label class="form-label">URL tương đối trong project</label><input v-model="form.videoUrl" class="form-control" readonly required></div></div><div class="modal-actions"><button type="button" class="btn btn-light" @click="uploadModal=false">Hủy</button><button class="btn btn-brand" :disabled="saving||!form.videoUrl"><span v-if="saving" class="spinner-border spinner-border-sm me-1"></span>Lưu vào thư viện</button></div></form></div>
  </section>
</template>

<script setup>
import { computed,onMounted,reactive,ref,watch } from 'vue'
import axiosClient from '../../api/axiosClient'
import { resolveApiAssetUrl } from '../../api/apiConfig'
import { formatInteractionTime } from '../../utils/learningRules'
const items=ref([]),search=ref(''),loading=ref(true),uploadModal=ref(false),uploading=ref(false),saving=ref(false),uploadProgress=ref(0),message=ref(''),messageType=ref('success'),metadataVideo=ref(null)
const form=reactive(blank()),playbackUrl=computed(()=>resolveApiAssetUrl(form.videoUrl)),pick=(source,...names)=>names.map(name=>source?.[name]).find(value=>value!==undefined&&value!==null),formatTime=formatInteractionTime
const fallbackThumbnails=[
  new URL('../../assets/eduvers/images/courses/course-list-img-1.jpg',import.meta.url).href,new URL('../../assets/eduvers/images/courses/course-list-img-2.jpg',import.meta.url).href,new URL('../../assets/eduvers/images/courses/course-list-img-3.jpg',import.meta.url).href,new URL('../../assets/eduvers/images/courses/course-list-img-4.jpg',import.meta.url).href,new URL('../../assets/eduvers/images/courses/course-list-img-5.jpg',import.meta.url).href,
  new URL('../../assets/eduvers/images/courses/courses-1-1.jpg',import.meta.url).href,new URL('../../assets/eduvers/images/courses/courses-1-2.jpg',import.meta.url).href,new URL('../../assets/eduvers/images/courses/courses-1-3.jpg',import.meta.url).href,new URL('../../assets/eduvers/images/courses/courses-1-4.jpg',import.meta.url).href,
  new URL('../../assets/eduvers/images/courses/courses-2-1.jpg',import.meta.url).href,new URL('../../assets/eduvers/images/courses/courses-2-2.jpg',import.meta.url).href,new URL('../../assets/eduvers/images/courses/courses-2-3.jpg',import.meta.url).href,
  new URL('../../assets/eduvers/images/courses/courses-3-1.jpg',import.meta.url).href,new URL('../../assets/eduvers/images/courses/courses-3-2.jpg',import.meta.url).href,new URL('../../assets/eduvers/images/courses/courses-3-3.jpg',import.meta.url).href,new URL('../../assets/eduvers/images/courses/courses-3-4.jpg',import.meta.url).href,new URL('../../assets/eduvers/images/courses/courses-3-5.jpg',import.meta.url).href,new URL('../../assets/eduvers/images/courses/courses-3-6.jpg',import.meta.url).href,
  new URL('../../assets/eduvers/images/courses/course-details-img-1.jpg',import.meta.url).href,new URL('../../assets/eduvers/images/courses/course-details-client-img-1.jpg',import.meta.url).href,new URL('../../assets/eduvers/images/courses/course-details-Instructor-img.jpg',import.meta.url).href,new URL('../../assets/eduvers/images/courses/course-list-client-img-1.jpg',import.meta.url).href,new URL('../../assets/eduvers/images/courses/course-list-client-img-2.jpg',import.meta.url).href,new URL('../../assets/eduvers/images/courses/course-list-client-img-3.jpg',import.meta.url).href,new URL('../../assets/eduvers/images/courses/course-list-client-img-4.jpg',import.meta.url).href
]
let timer
watch(search,()=>{clearTimeout(timer);timer=setTimeout(load,250)})
onMounted(load)
function blank(){return{title:'',videoUrl:'',posterUrl:'',durationSeconds:60,originalFileName:'',fileSize:0,mimeType:''}}
async function load(){loading.value=true;try{const rows=await axiosClient.get('/video-library',{params:{search:search.value||undefined,_fresh:Date.now()}});items.value=(Array.isArray(rows)?rows:[]).map(row=>({id:Number(pick(row,'Id','id')),title:pick(row,'Title','title'),videoUrl:pick(row,'VideoUrl','videoUrl')||'',posterUrl:pick(row,'PosterUrl','posterUrl')||'',originalFileName:pick(row,'OriginalFileName','originalFileName')||'',durationSeconds:Number(pick(row,'DurationSeconds','durationSeconds')||0),usageCount:Number(pick(row,'UsageCount','usageCount')||0),createdByName:pick(row,'CreatedByName','createdByName')||'',createdAt:pick(row,'CreatedAt','createdAt'),firstVideoId:Number(pick(row,'FirstVideoId','firstVideoId')||0)}))}catch(error){show(error.message,'danger')}finally{loading.value=false}}
function thumbnailFor(item,index){const projectPoster=item.posterUrl&&(!/^https?:\/\//i.test(item.posterUrl)||/^https?:\/\/localhost(?::\d+)?\//i.test(item.posterUrl));return projectPoster?resolveApiAssetUrl(item.posterUrl):fallbackThumbnails[index%fallbackThumbnails.length]}
function openUpload(){Object.assign(form,blank());uploadProgress.value=0;uploadModal.value=true}
async function upload(event){const file=event.target.files?.[0];event.target.value='';if(!file)return;uploading.value=true;try{const body=new FormData();body.append('file',file);const result=await axiosClient.post('/videos/upload',body,{timeout:0,onUploadProgress:e=>uploadProgress.value=e.total?Math.round(e.loaded/e.total*100):0});form.videoUrl=pick(result,'videoUrl','VideoUrl');form.originalFileName=pick(result,'originalFileName','OriginalFileName')||file.name;form.fileSize=Number(pick(result,'fileSize','FileSize')||file.size);form.mimeType=pick(result,'mimeType','MimeType')||file.type;form.title=file.name.replace(/\.[^.]+$/,'')}catch(error){show(error.message,'danger')}finally{uploading.value=false}}
function readDuration(){if(metadataVideo.value?.duration&&Number.isFinite(metadataVideo.value.duration))form.durationSeconds=Math.max(1,Math.round(metadataVideo.value.duration))}
async function save(){saving.value=true;try{await axiosClient.post('/video-library',{...form,durationSeconds:Math.max(1,Math.round(form.durationSeconds))});uploadModal.value=false;await load();show('Đã thêm video vào thư viện. Có thể chọn lại video này cho nhiều môn/bài học.')}catch(error){show(error.message,'danger')}finally{saving.value=false}}
async function remove(item){if(item.usageCount>0)return;if(!window.confirm(`Xóa “${item.title}” khỏi thư viện?`))return;try{await axiosClient.delete(`/video-library/${item.id}`);await load();show('Đã xóa video chưa sử dụng khỏi thư viện.')}catch(error){show(error.message,'danger')}}
function formatDate(value){return value?new Intl.DateTimeFormat('vi-VN').format(new Date(value)):'—'}
function show(text,type='success'){message.value=text;messageType.value=type}
</script>

<style scoped>
.search-box{position:relative}.search-box i{position:absolute;left:.85rem;top:50%;transform:translateY(-50%);color:#75857f}.search-box input{padding-left:2.35rem}.video-name{display:flex;align-items:center;gap:.75rem;min-width:320px}.video-thumb{position:relative;width:68px;height:46px;flex:0 0 68px;overflow:hidden;border-radius:8px;background-position:center;background-size:cover;display:grid;place-items:center}.video-thumb::after{content:'';position:absolute;inset:0;background:linear-gradient(135deg,rgba(5,24,35,.06),rgba(5,24,35,.34))}.video-thumb i{position:relative;z-index:1;width:24px;height:24px;display:grid;place-items:center;border-radius:50%;color:#fff;background:rgba(211,34,77,.9);font-size:.75rem}.video-name>div{display:grid}.video-name small{color:#75857f;max-width:360px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.modal-mask{position:fixed;inset:0;background:rgba(5,24,35,.65);z-index:2000;display:grid;place-items:center;padding:1rem}.upload-modal{width:min(760px,96vw);max-height:94vh;overflow:auto;padding:1.5rem}.modal-heading{display:flex;justify-content:space-between;align-items:flex-start;margin-bottom:1.2rem}.modal-heading small{color:var(--eduvers-base);font-weight:800}.modal-heading h2{font-size:1.35rem;margin:.2rem 0}.drop-zone{min-height:220px;border:1px dashed #a7b7b1;border-radius:12px;display:grid;place-items:center;align-content:center;gap:.5rem;background:#f8faf9;cursor:pointer}.drop-zone i{font-size:2.7rem;color:var(--eduvers-base)}.drop-zone span{color:#75857f}.upload-modal video{display:block;width:100%;max-height:330px;background:#071922;border-radius:10px}.modal-actions{display:flex;justify-content:flex-end;gap:.6rem;margin-top:1.5rem}
</style>
