// <auto-generated>
// File được sinh bởi tools/SimsObjectGenerator. Không sửa trực tiếp file này.
// </auto-generated>

#nullable enable

namespace SimsObject;

/// <summary>
/// [LMS] Phiên học theo dõi thời lượng xem và hành vi học tập.
/// </summary>
public partial class LMS_LearningSessions
{
    public const string TableSchema = "dbo";
    public const string TableName = "LMS_LearningSessions";
    public const string QualifiedTableName = "[dbo].[LMS_LearningSessions]";

    public const string C_LearningSessionID = "LearningSessionID";
    public const string P_LearningSessionID = "@LearningSessionID";

    public const string C_SessionId = "SessionId";
    public const string P_SessionId = "@SessionId";

    public const string C_StudentUserID = "StudentUserID";
    public const string P_StudentUserID = "@StudentUserID";

    public const string C_CourseId = "CourseId";
    public const string P_CourseId = "@CourseId";

    public const string C_LessonId = "LessonId";
    public const string P_LessonId = "@LessonId";

    public const string C_VideoId = "VideoId";
    public const string P_VideoId = "@VideoId";

    public const string C_StartedAt = "StartedAt";
    public const string P_StartedAt = "@StartedAt";

    public const string C_EndedAt = "EndedAt";
    public const string P_EndedAt = "@EndedAt";

    public const string C_WatchDurationSeconds = "WatchDurationSeconds";
    public const string P_WatchDurationSeconds = "@WatchDurationSeconds";

    public const string C_LastPositionSeconds = "LastPositionSeconds";
    public const string P_LastPositionSeconds = "@LastPositionSeconds";

    public const string C_MaxPositionSeconds = "MaxPositionSeconds";
    public const string P_MaxPositionSeconds = "@MaxPositionSeconds";

    public const string C_SeekCount = "SeekCount";
    public const string P_SeekCount = "@SeekCount";

    public const string C_PauseCount = "PauseCount";
    public const string P_PauseCount = "@PauseCount";

    public const string C_InteractionCount = "InteractionCount";
    public const string P_InteractionCount = "@InteractionCount";

    public const string C_Completed = "Completed";
    public const string P_Completed = "@Completed";

    public const string C_VideoVersionID = "VideoVersionID";
    public const string P_VideoVersionID = "@VideoVersionID";

    /// <summary>
    /// Khóa chính tự tăng của phiên học. (Khóa chính, Tự tăng).
    /// </summary>
    public long LearningSessionID { get; set; }

    /// <summary>
    /// Mã UUID duy nhất dùng nhận diện phiên học.
    /// </summary>
    public Guid SessionId { get; set; }

    /// <summary>
    /// ID học viên tham gia phiên học.
    /// </summary>
    public long StudentUserID { get; set; }

    /// <summary>
    /// ID khóa học của phiên học.
    /// </summary>
    public long CourseId { get; set; }

    /// <summary>
    /// ID bài học của phiên học.
    /// </summary>
    public long LessonId { get; set; }

    /// <summary>
    /// ID video đang học; có thể rỗng với bài học không phải video.
    /// </summary>
    public long? VideoId { get; set; }

    /// <summary>
    /// Thời điểm bắt đầu phiên học theo UTC.
    /// </summary>
    public DateTime StartedAt { get; set; }

    /// <summary>
    /// Thời điểm kết thúc phiên học theo UTC.
    /// </summary>
    public DateTime? EndedAt { get; set; }

    /// <summary>
    /// Tổng thời lượng xem trong phiên, đơn vị giây.
    /// </summary>
    public int WatchDurationSeconds { get; set; }

    /// <summary>
    /// Vị trí phát cuối cùng trong phiên, đơn vị giây.
    /// </summary>
    public decimal LastPositionSeconds { get; set; }

    /// <summary>
    /// Vị trí xa nhất đã xem trong phiên, đơn vị giây.
    /// </summary>
    public decimal MaxPositionSeconds { get; set; }

    /// <summary>
    /// Số lần tua video trong phiên.
    /// </summary>
    public int SeekCount { get; set; }

    /// <summary>
    /// Số lần tạm dừng video trong phiên.
    /// </summary>
    public int PauseCount { get; set; }

    /// <summary>
    /// Số tương tác đã kích hoạt trong phiên.
    /// </summary>
    public int InteractionCount { get; set; }

    /// <summary>
    /// Cờ cho biết phiên đã hoàn thành nội dung học.
    /// </summary>
    public bool Completed { get; set; }

    /// <summary>
    /// ID phiên bản video được sử dụng trong phiên học.
    /// </summary>
    public long? VideoVersionID { get; set; }
}
