// <auto-generated>
// File được sinh bởi tools/SimsObjectGenerator. Không sửa trực tiếp file này.
// </auto-generated>

#nullable enable

namespace SimsObject;

/// <summary>
/// [LMS] Danh sách câu hỏi và số điểm trong một bài kiểm tra.
/// </summary>
public partial class LMS_QuizQuestions
{
    public const string TableSchema = "dbo";
    public const string TableName = "LMS_QuizQuestions";
    public const string QualifiedTableName = "[dbo].[LMS_QuizQuestions]";

    public const string C_QuizQuestionID = "QuizQuestionID";
    public const string P_QuizQuestionID = "@QuizQuestionID";

    public const string C_QuizID = "QuizID";
    public const string P_QuizID = "@QuizID";

    public const string C_QuestionID = "QuestionID";
    public const string P_QuestionID = "@QuestionID";

    public const string C_Score = "Score";
    public const string P_Score = "@Score";

    public const string C_SortOrder = "SortOrder";
    public const string P_SortOrder = "@SortOrder";

    public const string C_IsRequired = "IsRequired";
    public const string P_IsRequired = "@IsRequired";

    /// <summary>
    /// Khóa chính dòng câu hỏi của bài kiểm tra. (Khóa chính, Tự tăng).
    /// </summary>
    public long QuizQuestionID { get; set; }

    /// <summary>
    /// Bài kiểm tra sở hữu câu hỏi.
    /// </summary>
    public long QuizID { get; set; }

    /// <summary>
    /// Câu hỏi tham chiếu từ ngân hàng câu hỏi.
    /// </summary>
    public long QuestionID { get; set; }

    /// <summary>
    /// Cột Score của bảng LMS_QuizQuestions; thuộc schema nghiệp vụ LMS.
    /// </summary>
    public decimal Score { get; set; }

    /// <summary>
    /// Cột SortOrder của bảng LMS_QuizQuestions; thuộc schema nghiệp vụ LMS.
    /// </summary>
    public int SortOrder { get; set; }

    /// <summary>
    /// Cột IsRequired của bảng LMS_QuizQuestions; thuộc schema nghiệp vụ LMS.
    /// </summary>
    public bool IsRequired { get; set; }
}
