// <auto-generated>
// File được sinh bởi tools/SimsObjectGenerator. Không sửa trực tiếp file này.
// </auto-generated>

#nullable enable

namespace SimsObject;

/// <summary>
/// [LMS] Cấu hình bài kiểm tra gắn một-một với bài học loại QUIZ.
/// </summary>
public partial class LMS_Quizzes
{
    public const string TableSchema = "dbo";
    public const string TableName = "LMS_Quizzes";
    public const string QualifiedTableName = "[dbo].[LMS_Quizzes]";

    public const string C_QuizID = "QuizID";
    public const string P_QuizID = "@QuizID";

    public const string C_LessonID = "LessonID";
    public const string P_LessonID = "@LessonID";

    public const string C_Title = "Title";
    public const string P_Title = "@Title";

    public const string C_Description = "Description";
    public const string P_Description = "@Description";

    public const string C_PassingScore = "PassingScore";
    public const string P_PassingScore = "@PassingScore";

    public const string C_TimeLimitMinutes = "TimeLimitMinutes";
    public const string P_TimeLimitMinutes = "@TimeLimitMinutes";

    public const string C_MaxAttempts = "MaxAttempts";
    public const string P_MaxAttempts = "@MaxAttempts";

    public const string C_ShuffleQuestions = "ShuffleQuestions";
    public const string P_ShuffleQuestions = "@ShuffleQuestions";

    public const string C_Status = "Status";
    public const string P_Status = "@Status";

    public const string C_CreatedByUserID = "CreatedByUserID";
    public const string P_CreatedByUserID = "@CreatedByUserID";

    public const string C_CreatedAt = "CreatedAt";
    public const string P_CreatedAt = "@CreatedAt";

    public const string C_UpdatedAt = "UpdatedAt";
    public const string P_UpdatedAt = "@UpdatedAt";

    /// <summary>
    /// Khóa chính bài kiểm tra. (Khóa chính, Tự tăng).
    /// </summary>
    public long QuizID { get; set; }

    /// <summary>
    /// Bài học loại QUIZ sở hữu bài kiểm tra.
    /// </summary>
    public long LessonID { get; set; }

    /// <summary>
    /// Cột Title của bảng LMS_Quizzes; thuộc schema nghiệp vụ LMS.
    /// </summary>
    public string? Title { get; set; }

    /// <summary>
    /// Cột Description của bảng LMS_Quizzes; thuộc schema nghiệp vụ LMS.
    /// </summary>
    public string? Description { get; set; }

    /// <summary>
    /// Phần trăm điểm tối thiểu để đạt.
    /// </summary>
    public decimal PassingScore { get; set; }

    /// <summary>
    /// Thời gian làm bài tối đa; rỗng nghĩa là không giới hạn.
    /// </summary>
    public int? TimeLimitMinutes { get; set; }

    /// <summary>
    /// Số lượt làm tối đa của mỗi học viên.
    /// </summary>
    public int MaxAttempts { get; set; }

    /// <summary>
    /// Cột ShuffleQuestions của bảng LMS_Quizzes; thuộc schema nghiệp vụ LMS.
    /// </summary>
    public bool ShuffleQuestions { get; set; }

    /// <summary>
    /// Cột Status của bảng LMS_Quizzes; thuộc schema nghiệp vụ LMS.
    /// </summary>
    public string? Status { get; set; }

    /// <summary>
    /// Cột CreatedByUserID của bảng LMS_Quizzes; thuộc schema nghiệp vụ LMS.
    /// </summary>
    public long CreatedByUserID { get; set; }

    /// <summary>
    /// Cột CreatedAt của bảng LMS_Quizzes; thuộc schema nghiệp vụ LMS.
    /// </summary>
    public DateTime CreatedAt { get; set; }

    /// <summary>
    /// Cột UpdatedAt của bảng LMS_Quizzes; thuộc schema nghiệp vụ LMS.
    /// </summary>
    public DateTime? UpdatedAt { get; set; }
}
