// <auto-generated>
// File được sinh bởi tools/SimsObjectGenerator. Không sửa trực tiếp file này.
// </auto-generated>

#nullable enable

namespace SimsObject;

/// <summary>
/// [LMS] Ngân hàng câu hỏi dùng trong hoạt động học tập.
/// </summary>
public partial class LMS_Questions
{
    public const string TableSchema = "dbo";
    public const string TableName = "LMS_Questions";
    public const string QualifiedTableName = "[dbo].[LMS_Questions]";

    public const string C_QuestionID = "QuestionID";
    public const string P_QuestionID = "@QuestionID";

    public const string C_QuestionType = "QuestionType";
    public const string P_QuestionType = "@QuestionType";

    public const string C_QuestionText = "QuestionText";
    public const string P_QuestionText = "@QuestionText";

    public const string C_Description = "Description";
    public const string P_Description = "@Description";

    public const string C_Explanation = "Explanation";
    public const string P_Explanation = "@Explanation";

    public const string C_Difficulty = "Difficulty";
    public const string P_Difficulty = "@Difficulty";

    public const string C_DefaultScore = "DefaultScore";
    public const string P_DefaultScore = "@DefaultScore";

    public const string C_ShortAnswerMode = "ShortAnswerMode";
    public const string P_ShortAnswerMode = "@ShortAnswerMode";

    public const string C_CreatedByUserID = "CreatedByUserID";
    public const string P_CreatedByUserID = "@CreatedByUserID";

    public const string C_CreatedAt = "CreatedAt";
    public const string P_CreatedAt = "@CreatedAt";

    public const string C_UpdatedAt = "UpdatedAt";
    public const string P_UpdatedAt = "@UpdatedAt";

    public const string C_Status = "Status";
    public const string P_Status = "@Status";

    public const string C_IsDeleted = "IsDeleted";
    public const string P_IsDeleted = "@IsDeleted";

    /// <summary>
    /// Khóa chính tự tăng của câu hỏi. (Khóa chính, Tự tăng).
    /// </summary>
    public long QuestionID { get; set; }

    /// <summary>
    /// Loại câu hỏi: một lựa chọn, nhiều lựa chọn, đúng/sai hoặc trả lời ngắn.
    /// </summary>
    public string? QuestionType { get; set; }

    /// <summary>
    /// Nội dung chính của câu hỏi.
    /// </summary>
    public string? QuestionText { get; set; }

    /// <summary>
    /// Thông tin bổ sung hoặc ngữ cảnh của câu hỏi.
    /// </summary>
    public string? Description { get; set; }

    /// <summary>
    /// Lời giải thích đáp án hiển thị sau khi trả lời.
    /// </summary>
    public string? Explanation { get; set; }

    /// <summary>
    /// Mức độ khó của câu hỏi.
    /// </summary>
    public string? Difficulty { get; set; }

    /// <summary>
    /// Điểm mặc định khi sử dụng câu hỏi.
    /// </summary>
    public decimal DefaultScore { get; set; }

    /// <summary>
    /// Quy tắc so khớp đáp án cho câu hỏi trả lời ngắn.
    /// </summary>
    public string? ShortAnswerMode { get; set; }

    /// <summary>
    /// ID người dùng tạo câu hỏi.
    /// </summary>
    public long CreatedByUserID { get; set; }

    /// <summary>
    /// Thời điểm tạo câu hỏi theo UTC.
    /// </summary>
    public DateTime CreatedAt { get; set; }

    /// <summary>
    /// Thời điểm cập nhật câu hỏi gần nhất theo UTC.
    /// </summary>
    public DateTime? UpdatedAt { get; set; }

    /// <summary>
    /// Trạng thái sử dụng của câu hỏi.
    /// </summary>
    public string? Status { get; set; }

    /// <summary>
    /// Cờ xóa mềm của câu hỏi.
    /// </summary>
    public bool IsDeleted { get; set; }
}
