// <auto-generated>
// File được sinh bởi tools/SimsObjectGenerator. Không sửa trực tiếp file này.
// </auto-generated>

#nullable enable

namespace SimsObject;

/// <summary>
/// Cấu hình bài học đọc hiểu có câu hỏi tương tác.
/// </summary>
public partial class LMS_InteractiveContents
{
    public const string TableSchema = "dbo";
    public const string TableName = "LMS_InteractiveContents";
    public const string QualifiedTableName = "[dbo].[LMS_InteractiveContents]";

    public const string C_InteractiveContentID = "InteractiveContentID";
    public const string P_InteractiveContentID = "@InteractiveContentID";

    public const string C_LessonID = "LessonID";
    public const string P_LessonID = "@LessonID";

    public const string C_CompletionRule = "CompletionRule";
    public const string P_CompletionRule = "@CompletionRule";

    public const string C_RequireReading = "RequireReading";
    public const string P_RequireReading = "@RequireReading";

    public const string C_PassingScore = "PassingScore";
    public const string P_PassingScore = "@PassingScore";

    public const string C_ShowResultImmediately = "ShowResultImmediately";
    public const string P_ShowResultImmediately = "@ShowResultImmediately";

    public const string C_ShowScore = "ShowScore";
    public const string P_ShowScore = "@ShowScore";

    public const string C_CreatedByUserID = "CreatedByUserID";
    public const string P_CreatedByUserID = "@CreatedByUserID";

    public const string C_CreatedAt = "CreatedAt";
    public const string P_CreatedAt = "@CreatedAt";

    public const string C_UpdatedByUserID = "UpdatedByUserID";
    public const string P_UpdatedByUserID = "@UpdatedByUserID";

    public const string C_UpdatedAt = "UpdatedAt";
    public const string P_UpdatedAt = "@UpdatedAt";

    /// <summary>
    /// Khóa chính của cấu hình bài học tương tác. (Khóa chính, Tự tăng).
    /// </summary>
    public long InteractiveContentID { get; set; }

    /// <summary>
    /// Bài học loại INTERACTIVE_CONTENT được cấu hình.
    /// </summary>
    public long LessonID { get; set; }

    /// <summary>
    /// Quy tắc hoàn thành: câu bắt buộc, toàn bộ câu hỏi hoặc đạt điểm.
    /// </summary>
    public string? CompletionRule { get; set; }

    /// <summary>
    /// Yêu cầu học viên đọc hết nội dung trước khi hoàn thành.
    /// </summary>
    public bool RequireReading { get; set; }

    /// <summary>
    /// Phần trăm điểm tối thiểu khi dùng quy tắc PASSING_SCORE.
    /// </summary>
    public decimal PassingScore { get; set; }

    /// <summary>
    /// Cho phép trả kết quả đúng sai và giải thích ngay sau khi trả lời.
    /// </summary>
    public bool ShowResultImmediately { get; set; }

    /// <summary>
    /// Cho phép học viên xem điểm của bài.
    /// </summary>
    public bool ShowScore { get; set; }

    /// <summary>
    /// Người dùng đã tạo cấu hình bài học tương tác.
    /// </summary>
    public long CreatedByUserID { get; set; }

    /// <summary>
    /// Thời điểm tạo cấu hình theo UTC.
    /// </summary>
    public DateTime CreatedAt { get; set; }

    /// <summary>
    /// Người dùng cập nhật cấu hình gần nhất.
    /// </summary>
    public long? UpdatedByUserID { get; set; }

    /// <summary>
    /// Thời điểm cập nhật cấu hình gần nhất theo UTC.
    /// </summary>
    public DateTime? UpdatedAt { get; set; }
}
