// <auto-generated>
// File được sinh bởi tools/SimsObjectGenerator. Không sửa trực tiếp file này.
// </auto-generated>

#nullable enable

namespace SimsObject;

/// <summary>
/// [LMS] Danh sách file đính kèm của từng lần nộp bài, tách khỏi metadata bài nộp.
/// </summary>
public partial class LMS_AssignmentSubmissionFiles
{
    public const string TableSchema = "dbo";
    public const string TableName = "LMS_AssignmentSubmissionFiles";
    public const string QualifiedTableName = "[dbo].[LMS_AssignmentSubmissionFiles]";

    public const string C_AssignmentSubmissionFileID = "AssignmentSubmissionFileID";
    public const string P_AssignmentSubmissionFileID = "@AssignmentSubmissionFileID";

    public const string C_AssignmentSubmissionID = "AssignmentSubmissionID";
    public const string P_AssignmentSubmissionID = "@AssignmentSubmissionID";

    public const string C_OriginalFileName = "OriginalFileName";
    public const string P_OriginalFileName = "@OriginalFileName";

    public const string C_StoredFileName = "StoredFileName";
    public const string P_StoredFileName = "@StoredFileName";

    public const string C_FileUrl = "FileUrl";
    public const string P_FileUrl = "@FileUrl";

    public const string C_FileSize = "FileSize";
    public const string P_FileSize = "@FileSize";

    public const string C_MimeType = "MimeType";
    public const string P_MimeType = "@MimeType";

    public const string C_CreatedAt = "CreatedAt";
    public const string P_CreatedAt = "@CreatedAt";

    /// <summary>
    /// Khóa chính của file thuộc một lần nộp bài. (Khóa chính, Tự tăng).
    /// </summary>
    public long AssignmentSubmissionFileID { get; set; }

    /// <summary>
    /// ID lần nộp bài sở hữu file.
    /// </summary>
    public long AssignmentSubmissionID { get; set; }

    /// <summary>
    /// Tên file gốc do học viên tải lên.
    /// </summary>
    public string? OriginalFileName { get; set; }

    /// <summary>
    /// Tên file GUID được lưu vật lý.
    /// </summary>
    public string? StoredFileName { get; set; }

    /// <summary>
    /// Đường dẫn tương đối an toàn trong thư mục Media/File.
    /// </summary>
    public string? FileUrl { get; set; }

    /// <summary>
    /// Kích thước file tính theo byte.
    /// </summary>
    public long FileSize { get; set; }

    /// <summary>
    /// Kiểu nội dung MIME đã được máy chủ kiểm tra.
    /// </summary>
    public string? MimeType { get; set; }

    /// <summary>
    /// Thời điểm metadata file được tạo theo UTC.
    /// </summary>
    public DateTime CreatedAt { get; set; }
}
