// <auto-generated>
// File được sinh bởi tools/SimsObjectGenerator. Không sửa trực tiếp file này.
// </auto-generated>

#nullable enable

namespace SimsObject;

/// <summary>
/// [LMS] Tiến độ và kết quả học tập theo từng bài học.
/// </summary>
public partial class LMS_StudentLessonProgress
{
    public const string TableSchema = "dbo";
    public const string TableName = "LMS_StudentLessonProgress";
    public const string QualifiedTableName = "[dbo].[LMS_StudentLessonProgress]";

    public const string C_StudentLessonProgressID = "StudentLessonProgressID";
    public const string P_StudentLessonProgressID = "@StudentLessonProgressID";

    public const string C_StudentUserID = "StudentUserID";
    public const string P_StudentUserID = "@StudentUserID";

    public const string C_CourseId = "CourseId";
    public const string P_CourseId = "@CourseId";

    public const string C_LessonId = "LessonId";
    public const string P_LessonId = "@LessonId";

    public const string C_ProgressPercent = "ProgressPercent";
    public const string P_ProgressPercent = "@ProgressPercent";

    public const string C_Score = "Score";
    public const string P_Score = "@Score";

    public const string C_AttemptCount = "AttemptCount";
    public const string P_AttemptCount = "@AttemptCount";

    public const string C_Completed = "Completed";
    public const string P_Completed = "@Completed";

    public const string C_CompletedAt = "CompletedAt";
    public const string P_CompletedAt = "@CompletedAt";

    public const string C_LastAccessAt = "LastAccessAt";
    public const string P_LastAccessAt = "@LastAccessAt";

    public const string C_CreatedAt = "CreatedAt";
    public const string P_CreatedAt = "@CreatedAt";

    public const string C_UpdatedAt = "UpdatedAt";
    public const string P_UpdatedAt = "@UpdatedAt";

    public const string C_ActiveStudySeconds = "ActiveStudySeconds";
    public const string P_ActiveStudySeconds = "@ActiveStudySeconds";

    public const string C_ReadingProgressPercent = "ReadingProgressPercent";
    public const string P_ReadingProgressPercent = "@ReadingProgressPercent";

    public const string C_LastScrollPercent = "LastScrollPercent";
    public const string P_LastScrollPercent = "@LastScrollPercent";

    /// <summary>
    /// Khóa chính tự tăng của tiến độ bài học. (Khóa chính, Tự tăng).
    /// </summary>
    public long StudentLessonProgressID { get; set; }

    /// <summary>
    /// ID học viên có tiến độ học.
    /// </summary>
    public long StudentUserID { get; set; }

    /// <summary>
    /// ID khóa học chứa bài học.
    /// </summary>
    public long CourseId { get; set; }

    /// <summary>
    /// ID bài học được theo dõi.
    /// </summary>
    public long LessonId { get; set; }

    /// <summary>
    /// Tỷ lệ phần trăm hoàn thành bài học.
    /// </summary>
    public decimal ProgressPercent { get; set; }

    /// <summary>
    /// Điểm cao nhất hoặc hiện tại của bài học.
    /// </summary>
    public decimal Score { get; set; }

    /// <summary>
    /// Tổng số lần học viên thực hiện bài học.
    /// </summary>
    public int AttemptCount { get; set; }

    /// <summary>
    /// Cờ cho biết bài học đã hoàn thành.
    /// </summary>
    public bool Completed { get; set; }

    /// <summary>
    /// Thời điểm hoàn thành bài học theo UTC.
    /// </summary>
    public DateTime? CompletedAt { get; set; }

    /// <summary>
    /// Thời điểm truy cập bài học gần nhất theo UTC.
    /// </summary>
    public DateTime LastAccessAt { get; set; }

    /// <summary>
    /// Thời điểm tạo bản ghi tiến độ theo UTC.
    /// </summary>
    public DateTime CreatedAt { get; set; }

    /// <summary>
    /// Thời điểm cập nhật tiến độ gần nhất theo UTC.
    /// </summary>
    public DateTime? UpdatedAt { get; set; }

    /// <summary>
    /// Tổng số giây học hợp lệ được backend tổng hợp từ các phiên heartbeat.
    /// </summary>
    public int ActiveStudySeconds { get; set; }

    /// <summary>
    /// Phần trăm nội dung học viên đã đọc.
    /// </summary>
    public decimal ReadingProgressPercent { get; set; }

    /// <summary>
    /// Vị trí cuộn gần nhất để khôi phục khi học tiếp.
    /// </summary>
    public decimal LastScrollPercent { get; set; }
}
