// <auto-generated>
// File được sinh bởi tools/SimsObjectGenerator. Không sửa trực tiếp file này.
// </auto-generated>

#nullable enable

namespace SimsObject;

/// <summary>
/// [LMS] Câu hỏi tương tác tại các mốc thời gian của video.
/// </summary>
public partial class LMS_VideoInteractions
{
    public const string TableSchema = "dbo";
    public const string TableName = "LMS_VideoInteractions";
    public const string QualifiedTableName = "[dbo].[LMS_VideoInteractions]";

    public const string C_VideoInteractionID = "VideoInteractionID";
    public const string P_VideoInteractionID = "@VideoInteractionID";

    public const string C_VideoId = "VideoId";
    public const string P_VideoId = "@VideoId";

    public const string C_QuestionId = "QuestionId";
    public const string P_QuestionId = "@QuestionId";

    public const string C_TimeSeconds = "TimeSeconds";
    public const string P_TimeSeconds = "@TimeSeconds";

    public const string C_EndTimeSeconds = "EndTimeSeconds";
    public const string P_EndTimeSeconds = "@EndTimeSeconds";

    public const string C_InteractionType = "InteractionType";
    public const string P_InteractionType = "@InteractionType";

    public const string C_Required = "Required";
    public const string P_Required = "@Required";

    public const string C_PauseVideo = "PauseVideo";
    public const string P_PauseVideo = "@PauseVideo";

    public const string C_AllowSkip = "AllowSkip";
    public const string P_AllowSkip = "@AllowSkip";

    public const string C_Score = "Score";
    public const string P_Score = "@Score";

    public const string C_AttemptLimit = "AttemptLimit";
    public const string P_AttemptLimit = "@AttemptLimit";

    public const string C_SortOrder = "SortOrder";
    public const string P_SortOrder = "@SortOrder";

    public const string C_Status = "Status";
    public const string P_Status = "@Status";

    public const string C_CreatedAt = "CreatedAt";
    public const string P_CreatedAt = "@CreatedAt";

    public const string C_UpdatedAt = "UpdatedAt";
    public const string P_UpdatedAt = "@UpdatedAt";

    public const string C_IsDeleted = "IsDeleted";
    public const string P_IsDeleted = "@IsDeleted";

    public const string C_VideoVersionID = "VideoVersionID";
    public const string P_VideoVersionID = "@VideoVersionID";

    /// <summary>
    /// Khóa chính tự tăng của tương tác video. (Khóa chính, Tự tăng).
    /// </summary>
    public long VideoInteractionID { get; set; }

    /// <summary>
    /// ID video chứa mốc tương tác.
    /// </summary>
    public long VideoId { get; set; }

    /// <summary>
    /// ID câu hỏi được hiển thị tại mốc tương tác.
    /// </summary>
    public long QuestionId { get; set; }

    /// <summary>
    /// Thời điểm bắt đầu tương tác tính từ đầu video, đơn vị giây.
    /// </summary>
    public int TimeSeconds { get; set; }

    /// <summary>
    /// Thời điểm kết thúc vùng tương tác tính bằng giây; có thể rỗng.
    /// </summary>
    public int? EndTimeSeconds { get; set; }

    /// <summary>
    /// Loại tương tác được kích hoạt trong video.
    /// </summary>
    public string? InteractionType { get; set; }

    /// <summary>
    /// Cờ bắt buộc học viên phải trả lời tương tác.
    /// </summary>
    public bool Required { get; set; }

    /// <summary>
    /// Cờ tự động tạm dừng video khi tương tác xuất hiện.
    /// </summary>
    public bool PauseVideo { get; set; }

    /// <summary>
    /// Cờ cho phép học viên bỏ qua tương tác.
    /// </summary>
    public bool AllowSkip { get; set; }

    /// <summary>
    /// Điểm tối đa của tương tác.
    /// </summary>
    public decimal Score { get; set; }

    /// <summary>
    /// Số lần tối đa được phép trả lời tương tác.
    /// </summary>
    public int AttemptLimit { get; set; }

    /// <summary>
    /// Thứ tự xử lý khi nhiều tương tác cùng thời điểm.
    /// </summary>
    public int SortOrder { get; set; }

    /// <summary>
    /// Trạng thái sử dụng của tương tác.
    /// </summary>
    public string? Status { get; set; }

    /// <summary>
    /// Thời điểm tạo tương tác theo UTC.
    /// </summary>
    public DateTime CreatedAt { get; set; }

    /// <summary>
    /// Thời điểm cập nhật tương tác gần nhất theo UTC.
    /// </summary>
    public DateTime? UpdatedAt { get; set; }

    /// <summary>
    /// Cờ xóa mềm của tương tác.
    /// </summary>
    public bool IsDeleted { get; set; }

    /// <summary>
    /// ID phiên bản video chứa mốc tương tác.
    /// </summary>
    public long? VideoVersionID { get; set; }
}
