// <auto-generated>
// File được sinh bởi tools/SimsObjectGenerator. Không sửa trực tiếp file này.
// </auto-generated>

#nullable enable

namespace SimsObject;

/// <summary>
/// [LMS] Lưu thảo luận của bài học và các câu trả lời lồng nhau bằng quan hệ tự tham chiếu.
/// </summary>
public partial class LMS_LessonComments
{
    public const string TableSchema = "dbo";
    public const string TableName = "LMS_LessonComments";
    public const string QualifiedTableName = "[dbo].[LMS_LessonComments]";

    public const string C_LessonCommentID = "LessonCommentID";
    public const string P_LessonCommentID = "@LessonCommentID";

    public const string C_CourseID = "CourseID";
    public const string P_CourseID = "@CourseID";

    public const string C_LessonID = "LessonID";
    public const string P_LessonID = "@LessonID";

    public const string C_UserID = "UserID";
    public const string P_UserID = "@UserID";

    public const string C_ParentCommentID = "ParentCommentID";
    public const string P_ParentCommentID = "@ParentCommentID";

    public const string C_Content = "Content";
    public const string P_Content = "@Content";

    public const string C_IsEdited = "IsEdited";
    public const string P_IsEdited = "@IsEdited";

    public const string C_CreatedDate = "CreatedDate";
    public const string P_CreatedDate = "@CreatedDate";

    public const string C_UpdatedDate = "UpdatedDate";
    public const string P_UpdatedDate = "@UpdatedDate";

    public const string C_IsDeleted = "IsDeleted";
    public const string P_IsDeleted = "@IsDeleted";

    public const string C_DeletedDate = "DeletedDate";
    public const string P_DeletedDate = "@DeletedDate";

    public const string C_DeletedUserID = "DeletedUserID";
    public const string P_DeletedUserID = "@DeletedUserID";

    /// <summary>
    /// Khóa chính tự tăng của bình luận bài học. (Khóa chính, Tự tăng).
    /// </summary>
    public long LessonCommentID { get; set; }

    /// <summary>
    /// Khóa học chứa bài học được bình luận.
    /// </summary>
    public long CourseID { get; set; }

    /// <summary>
    /// Bài học chứa luồng thảo luận.
    /// </summary>
    public long LessonID { get; set; }

    /// <summary>
    /// Tài khoản tạo bình luận hoặc câu trả lời.
    /// </summary>
    public long UserID { get; set; }

    /// <summary>
    /// Bình luận cha; rỗng nghĩa là bình luận gốc.
    /// </summary>
    public long? ParentCommentID { get; set; }

    /// <summary>
    /// Nội dung bình luận dạng văn bản thuần, tối đa 5000 ký tự.
    /// </summary>
    public string? Content { get; set; }

    /// <summary>
    /// Đánh dấu nội dung đã được tác giả chỉnh sửa.
    /// </summary>
    public bool IsEdited { get; set; }

    /// <summary>
    /// Thời điểm UTC tạo bình luận.
    /// </summary>
    public DateTime CreatedDate { get; set; }

    /// <summary>
    /// Thời điểm UTC cập nhật nội dung gần nhất.
    /// </summary>
    public DateTime? UpdatedDate { get; set; }

    /// <summary>
    /// Đánh dấu xóa mềm để giữ nguyên chuỗi trả lời.
    /// </summary>
    public bool IsDeleted { get; set; }

    /// <summary>
    /// Thời điểm UTC xóa mềm bình luận.
    /// </summary>
    public DateTime? DeletedDate { get; set; }

    /// <summary>
    /// Tài khoản thực hiện xóa mềm bình luận.
    /// </summary>
    public long? DeletedUserID { get; set; }
}
