// <auto-generated>
// File được sinh bởi tools/SimsObjectGenerator. Không sửa trực tiếp file này.
// </auto-generated>

#nullable enable

namespace SimsObject;

/// <summary>
/// Liên kết câu hỏi dùng chung với một bài học tương tác.
/// </summary>
public partial class LMS_ContentInteractions
{
    public const string TableSchema = "dbo";
    public const string TableName = "LMS_ContentInteractions";
    public const string QualifiedTableName = "[dbo].[LMS_ContentInteractions]";

    public const string C_ContentInteractionID = "ContentInteractionID";
    public const string P_ContentInteractionID = "@ContentInteractionID";

    public const string C_InteractiveContentID = "InteractiveContentID";
    public const string P_InteractiveContentID = "@InteractiveContentID";

    public const string C_QuestionID = "QuestionID";
    public const string P_QuestionID = "@QuestionID";

    public const string C_ContentAnchor = "ContentAnchor";
    public const string P_ContentAnchor = "@ContentAnchor";

    public const string C_Required = "Required";
    public const string P_Required = "@Required";

    public const string C_AllowRetry = "AllowRetry";
    public const string P_AllowRetry = "@AllowRetry";

    public const string C_Score = "Score";
    public const string P_Score = "@Score";

    public const string C_AttemptLimit = "AttemptLimit";
    public const string P_AttemptLimit = "@AttemptLimit";

    public const string C_SortOrder = "SortOrder";
    public const string P_SortOrder = "@SortOrder";

    public const string C_Status = "Status";
    public const string P_Status = "@Status";

    public const string C_CreatedByUserID = "CreatedByUserID";
    public const string P_CreatedByUserID = "@CreatedByUserID";

    public const string C_CreatedAt = "CreatedAt";
    public const string P_CreatedAt = "@CreatedAt";

    public const string C_UpdatedByUserID = "UpdatedByUserID";
    public const string P_UpdatedByUserID = "@UpdatedByUserID";

    public const string C_UpdatedAt = "UpdatedAt";
    public const string P_UpdatedAt = "@UpdatedAt";

    public const string C_IsDeleted = "IsDeleted";
    public const string P_IsDeleted = "@IsDeleted";

    /// <summary>
    /// Khóa chính của câu hỏi trong bài học tương tác. (Khóa chính, Tự tăng).
    /// </summary>
    public long ContentInteractionID { get; set; }

    /// <summary>
    /// Cấu hình bài học tương tác sở hữu câu hỏi.
    /// </summary>
    public long InteractiveContentID { get; set; }

    /// <summary>
    /// Câu hỏi dùng lại từ ngân hàng LMS_Questions.
    /// </summary>
    public long QuestionID { get; set; }

    /// <summary>
    /// Điểm neo tùy chọn để liên hệ câu hỏi với một phần nội dung.
    /// </summary>
    public string? ContentAnchor { get; set; }

    /// <summary>
    /// Đánh dấu câu hỏi bắt buộc.
    /// </summary>
    public bool Required { get; set; }

    /// <summary>
    /// Cho phép học viên thử lại khi chưa đạt.
    /// </summary>
    public bool AllowRetry { get; set; }

    /// <summary>
    /// Điểm tối đa của câu hỏi trong bài.
    /// </summary>
    public decimal Score { get; set; }

    /// <summary>
    /// Số lần trả lời tối đa.
    /// </summary>
    public int AttemptLimit { get; set; }

    /// <summary>
    /// Thứ tự hiển thị câu hỏi.
    /// </summary>
    public int SortOrder { get; set; }

    /// <summary>
    /// Trạng thái sử dụng của câu hỏi trong bài học.
    /// </summary>
    public string? Status { get; set; }

    /// <summary>
    /// Người dùng đã gắn câu hỏi vào bài học.
    /// </summary>
    public long CreatedByUserID { get; set; }

    /// <summary>
    /// Thời điểm gắn câu hỏi theo UTC.
    /// </summary>
    public DateTime CreatedAt { get; set; }

    /// <summary>
    /// Người dùng cập nhật liên kết câu hỏi gần nhất.
    /// </summary>
    public long? UpdatedByUserID { get; set; }

    /// <summary>
    /// Thời điểm cập nhật liên kết câu hỏi gần nhất theo UTC.
    /// </summary>
    public DateTime? UpdatedAt { get; set; }

    /// <summary>
    /// Cờ xóa mềm của câu hỏi trong bài học.
    /// </summary>
    public bool IsDeleted { get; set; }
}
