// <auto-generated>
// File được sinh bởi tools/SimsObjectGenerator. Không sửa trực tiếp file này.
// </auto-generated>

#nullable enable

namespace SimsObject;

/// <summary>
/// [LMS] Thông tin ghi danh học viên vào khóa học.
/// </summary>
public partial class LMS_Enrollments
{
    public const string TableSchema = "dbo";
    public const string TableName = "LMS_Enrollments";
    public const string QualifiedTableName = "[dbo].[LMS_Enrollments]";

    public const string C_EnrollmentID = "EnrollmentID";
    public const string P_EnrollmentID = "@EnrollmentID";

    public const string C_CourseId = "CourseId";
    public const string P_CourseId = "@CourseId";

    public const string C_StudentUserID = "StudentUserID";
    public const string P_StudentUserID = "@StudentUserID";

    public const string C_EnrolledAt = "EnrolledAt";
    public const string P_EnrolledAt = "@EnrolledAt";

    public const string C_StartedAt = "StartedAt";
    public const string P_StartedAt = "@StartedAt";

    public const string C_CompletedAt = "CompletedAt";
    public const string P_CompletedAt = "@CompletedAt";

    public const string C_Status = "Status";
    public const string P_Status = "@Status";

    public const string C_ProgressPercent = "ProgressPercent";
    public const string P_ProgressPercent = "@ProgressPercent";

    public const string C_FinalScore = "FinalScore";
    public const string P_FinalScore = "@FinalScore";

    public const string C_LastAccessAt = "LastAccessAt";
    public const string P_LastAccessAt = "@LastAccessAt";

    public const string C_CreatedByUserID = "CreatedByUserID";
    public const string P_CreatedByUserID = "@CreatedByUserID";

    /// <summary>
    /// Khóa chính tự tăng của lượt ghi danh. (Khóa chính, Tự tăng).
    /// </summary>
    public long EnrollmentID { get; set; }

    /// <summary>
    /// ID khóa học được ghi danh.
    /// </summary>
    public long CourseId { get; set; }

    /// <summary>
    /// ID học viên được ghi danh.
    /// </summary>
    public long StudentUserID { get; set; }

    /// <summary>
    /// Thời điểm ghi danh học viên theo UTC.
    /// </summary>
    public DateTime EnrolledAt { get; set; }

    /// <summary>
    /// Thời điểm học viên bắt đầu học theo UTC.
    /// </summary>
    public DateTime? StartedAt { get; set; }

    /// <summary>
    /// Thời điểm học viên hoàn thành khóa học theo UTC.
    /// </summary>
    public DateTime? CompletedAt { get; set; }

    /// <summary>
    /// Trạng thái ghi danh: ENROLLED, IN_PROGRESS, COMPLETED hoặc CANCELLED.
    /// </summary>
    public string? Status { get; set; }

    /// <summary>
    /// Tỷ lệ phần trăm hoàn thành khóa học.
    /// </summary>
    public decimal ProgressPercent { get; set; }

    /// <summary>
    /// Điểm tổng kết cuối cùng của khóa học.
    /// </summary>
    public decimal? FinalScore { get; set; }

    /// <summary>
    /// Thời điểm học viên truy cập khóa học gần nhất theo UTC.
    /// </summary>
    public DateTime? LastAccessAt { get; set; }

    /// <summary>
    /// ID người dùng thực hiện ghi danh.
    /// </summary>
    public long CreatedByUserID { get; set; }
}
