// <auto-generated>
// File được sinh bởi tools/SimsObjectGenerator. Không sửa trực tiếp file này.
// </auto-generated>

#nullable enable

namespace SimsObject;

/// <summary>
/// [LMS] Câu trả lời và điểm backend chấm cho từng câu trong một lượt quiz.
/// </summary>
public partial class LMS_QuizAttemptAnswers
{
    public const string TableSchema = "dbo";
    public const string TableName = "LMS_QuizAttemptAnswers";
    public const string QualifiedTableName = "[dbo].[LMS_QuizAttemptAnswers]";

    public const string C_QuizAttemptAnswerID = "QuizAttemptAnswerID";
    public const string P_QuizAttemptAnswerID = "@QuizAttemptAnswerID";

    public const string C_QuizAttemptID = "QuizAttemptID";
    public const string P_QuizAttemptID = "@QuizAttemptID";

    public const string C_QuestionID = "QuestionID";
    public const string P_QuestionID = "@QuestionID";

    public const string C_AnswerText = "AnswerText";
    public const string P_AnswerText = "@AnswerText";

    public const string C_IsCorrect = "IsCorrect";
    public const string P_IsCorrect = "@IsCorrect";

    public const string C_ScoreAwarded = "ScoreAwarded";
    public const string P_ScoreAwarded = "@ScoreAwarded";

    public const string C_AnsweredAt = "AnsweredAt";
    public const string P_AnsweredAt = "@AnsweredAt";

    /// <summary>
    /// Khóa chính câu trả lời trong lượt quiz. (Khóa chính, Tự tăng).
    /// </summary>
    public long QuizAttemptAnswerID { get; set; }

    /// <summary>
    /// Lượt quiz sở hữu câu trả lời.
    /// </summary>
    public long QuizAttemptID { get; set; }

    /// <summary>
    /// Câu hỏi được trả lời.
    /// </summary>
    public long QuestionID { get; set; }

    /// <summary>
    /// Nội dung hoặc mã phương án học viên đã chọn; không chứa đáp án đúng.
    /// </summary>
    public string? AnswerText { get; set; }

    /// <summary>
    /// Kết quả đúng sai do backend xác định.
    /// </summary>
    public bool? IsCorrect { get; set; }

    /// <summary>
    /// Điểm backend trao cho câu trả lời.
    /// </summary>
    public decimal ScoreAwarded { get; set; }

    /// <summary>
    /// Cột AnsweredAt của bảng LMS_QuizAttemptAnswers; thuộc schema nghiệp vụ LMS.
    /// </summary>
    public DateTime AnsweredAt { get; set; }
}
