// <auto-generated>
// File được sinh bởi tools/SimsObjectGenerator. Không sửa trực tiếp file này.
// </auto-generated>

#nullable enable

namespace SimsObject;

/// <summary>
/// [LMS] Bài làm học viên nộp cho bài tập, gồm file, nội dung và kết quả chấm.
/// </summary>
public partial class LMS_AssignmentSubmissions
{
    public const string TableSchema = "dbo";
    public const string TableName = "LMS_AssignmentSubmissions";
    public const string QualifiedTableName = "[dbo].[LMS_AssignmentSubmissions]";

    public const string C_AssignmentSubmissionID = "AssignmentSubmissionID";
    public const string P_AssignmentSubmissionID = "@AssignmentSubmissionID";

    public const string C_LessonID = "LessonID";
    public const string P_LessonID = "@LessonID";

    public const string C_CourseID = "CourseID";
    public const string P_CourseID = "@CourseID";

    public const string C_StudentUserID = "StudentUserID";
    public const string P_StudentUserID = "@StudentUserID";

    public const string C_AttemptNumber = "AttemptNumber";
    public const string P_AttemptNumber = "@AttemptNumber";

    public const string C_SubmissionText = "SubmissionText";
    public const string P_SubmissionText = "@SubmissionText";

    public const string C_FileUrl = "FileUrl";
    public const string P_FileUrl = "@FileUrl";

    public const string C_OriginalFileName = "OriginalFileName";
    public const string P_OriginalFileName = "@OriginalFileName";

    public const string C_StoredFileName = "StoredFileName";
    public const string P_StoredFileName = "@StoredFileName";

    public const string C_FileSize = "FileSize";
    public const string P_FileSize = "@FileSize";

    public const string C_MimeType = "MimeType";
    public const string P_MimeType = "@MimeType";

    public const string C_SubmittedAt = "SubmittedAt";
    public const string P_SubmittedAt = "@SubmittedAt";

    public const string C_SubmissionStatus = "SubmissionStatus";
    public const string P_SubmissionStatus = "@SubmissionStatus";

    public const string C_Score = "Score";
    public const string P_Score = "@Score";

    public const string C_Feedback = "Feedback";
    public const string P_Feedback = "@Feedback";

    public const string C_GradedByUserID = "GradedByUserID";
    public const string P_GradedByUserID = "@GradedByUserID";

    public const string C_GradedAt = "GradedAt";
    public const string P_GradedAt = "@GradedAt";

    public const string C_IsLate = "IsLate";
    public const string P_IsLate = "@IsLate";

    /// <summary>
    /// Cột AssignmentSubmissionID của bảng LMS_AssignmentSubmissions, lưu thông tin phục vụ nghiệp vụ được mô tả ở cấp bảng. (Khóa chính, Tự tăng).
    /// </summary>
    public long AssignmentSubmissionID { get; set; }

    /// <summary>
    /// Cột LessonID của bảng LMS_AssignmentSubmissions, lưu thông tin phục vụ nghiệp vụ được mô tả ở cấp bảng.
    /// </summary>
    public long LessonID { get; set; }

    /// <summary>
    /// Cột CourseID của bảng LMS_AssignmentSubmissions, lưu thông tin phục vụ nghiệp vụ được mô tả ở cấp bảng.
    /// </summary>
    public long CourseID { get; set; }

    /// <summary>
    /// Cột StudentUserID của bảng LMS_AssignmentSubmissions, lưu thông tin phục vụ nghiệp vụ được mô tả ở cấp bảng.
    /// </summary>
    public long StudentUserID { get; set; }

    /// <summary>
    /// Cột AttemptNumber của bảng LMS_AssignmentSubmissions, lưu thông tin phục vụ nghiệp vụ được mô tả ở cấp bảng.
    /// </summary>
    public int AttemptNumber { get; set; }

    /// <summary>
    /// Cột SubmissionText của bảng LMS_AssignmentSubmissions, lưu thông tin phục vụ nghiệp vụ được mô tả ở cấp bảng.
    /// </summary>
    public string? SubmissionText { get; set; }

    /// <summary>
    /// Đường dẫn tương đối tới file học viên nộp trong /Media/File/Assignments/.
    /// </summary>
    public string? FileUrl { get; set; }

    /// <summary>
    /// Cột OriginalFileName của bảng LMS_AssignmentSubmissions, lưu thông tin phục vụ nghiệp vụ được mô tả ở cấp bảng.
    /// </summary>
    public string? OriginalFileName { get; set; }

    /// <summary>
    /// Cột StoredFileName của bảng LMS_AssignmentSubmissions, lưu thông tin phục vụ nghiệp vụ được mô tả ở cấp bảng.
    /// </summary>
    public string? StoredFileName { get; set; }

    /// <summary>
    /// Cột FileSize của bảng LMS_AssignmentSubmissions, lưu thông tin phục vụ nghiệp vụ được mô tả ở cấp bảng.
    /// </summary>
    public long? FileSize { get; set; }

    /// <summary>
    /// Cột MimeType của bảng LMS_AssignmentSubmissions, lưu thông tin phục vụ nghiệp vụ được mô tả ở cấp bảng.
    /// </summary>
    public string? MimeType { get; set; }

    /// <summary>
    /// Cột SubmittedAt của bảng LMS_AssignmentSubmissions, lưu thông tin phục vụ nghiệp vụ được mô tả ở cấp bảng.
    /// </summary>
    public DateTime SubmittedAt { get; set; }

    /// <summary>
    /// Trạng thái bài nộp: nháp, đã nộp, đã chấm hoặc trả lại.
    /// </summary>
    public string? SubmissionStatus { get; set; }

    /// <summary>
    /// Cột Score của bảng LMS_AssignmentSubmissions, lưu thông tin phục vụ nghiệp vụ được mô tả ở cấp bảng.
    /// </summary>
    public decimal? Score { get; set; }

    /// <summary>
    /// Cột Feedback của bảng LMS_AssignmentSubmissions, lưu thông tin phục vụ nghiệp vụ được mô tả ở cấp bảng.
    /// </summary>
    public string? Feedback { get; set; }

    /// <summary>
    /// Cột GradedByUserID của bảng LMS_AssignmentSubmissions, lưu thông tin phục vụ nghiệp vụ được mô tả ở cấp bảng.
    /// </summary>
    public long? GradedByUserID { get; set; }

    /// <summary>
    /// Cột GradedAt của bảng LMS_AssignmentSubmissions, lưu thông tin phục vụ nghiệp vụ được mô tả ở cấp bảng.
    /// </summary>
    public DateTime? GradedAt { get; set; }

    /// <summary>
    /// Cho biết bài được nộp sau hạn cuối hay không.
    /// </summary>
    public bool IsLate { get; set; }
}
