// <auto-generated>
// File được sinh bởi tools/SimsObjectGenerator. Không sửa trực tiếp file này.
// </auto-generated>

#nullable enable

namespace SimsObject;

/// <summary>
/// [LMS] Các phương án lựa chọn của câu hỏi.
/// </summary>
public partial class LMS_QuestionOptions
{
    public const string TableSchema = "dbo";
    public const string TableName = "LMS_QuestionOptions";
    public const string QualifiedTableName = "[dbo].[LMS_QuestionOptions]";

    public const string C_QuestionOptionID = "QuestionOptionID";
    public const string P_QuestionOptionID = "@QuestionOptionID";

    public const string C_QuestionId = "QuestionId";
    public const string P_QuestionId = "@QuestionId";

    public const string C_OptionCode = "OptionCode";
    public const string P_OptionCode = "@OptionCode";

    public const string C_OptionText = "OptionText";
    public const string P_OptionText = "@OptionText";

    public const string C_IsCorrect = "IsCorrect";
    public const string P_IsCorrect = "@IsCorrect";

    public const string C_SortOrder = "SortOrder";
    public const string P_SortOrder = "@SortOrder";

    public const string C_IsDeleted = "IsDeleted";
    public const string P_IsDeleted = "@IsDeleted";

    /// <summary>
    /// Khóa chính tự tăng của phương án trả lời. (Khóa chính, Tự tăng).
    /// </summary>
    public long QuestionOptionID { get; set; }

    /// <summary>
    /// ID câu hỏi sở hữu phương án.
    /// </summary>
    public long QuestionId { get; set; }

    /// <summary>
    /// Mã phương án trong phạm vi câu hỏi, ví dụ A, B, C, D.
    /// </summary>
    public string? OptionCode { get; set; }

    /// <summary>
    /// Nội dung hiển thị của phương án.
    /// </summary>
    public string? OptionText { get; set; }

    /// <summary>
    /// Cờ cho biết phương án là đáp án đúng.
    /// </summary>
    public bool IsCorrect { get; set; }

    /// <summary>
    /// Thứ tự hiển thị của phương án.
    /// </summary>
    public int SortOrder { get; set; }

    /// <summary>
    /// Cờ xóa mềm của phương án.
    /// </summary>
    public bool IsDeleted { get; set; }
}
