// <auto-generated>
// File được sinh bởi tools/SimsObjectGenerator. Không sửa trực tiếp file này.
// </auto-generated>

#nullable enable

namespace SimsObject;

/// <summary>
/// [LMS] Các đáp án chữ được chấp nhận cho câu hỏi trả lời ngắn.
/// </summary>
public partial class LMS_QuestionAnswerKeys
{
    public const string TableSchema = "dbo";
    public const string TableName = "LMS_QuestionAnswerKeys";
    public const string QualifiedTableName = "[dbo].[LMS_QuestionAnswerKeys]";

    public const string C_QuestionAnswerKeyID = "QuestionAnswerKeyID";
    public const string P_QuestionAnswerKeyID = "@QuestionAnswerKeyID";

    public const string C_QuestionId = "QuestionId";
    public const string P_QuestionId = "@QuestionId";

    public const string C_AnswerText = "AnswerText";
    public const string P_AnswerText = "@AnswerText";

    public const string C_IsCaseSensitive = "IsCaseSensitive";
    public const string P_IsCaseSensitive = "@IsCaseSensitive";

    public const string C_SortOrder = "SortOrder";
    public const string P_SortOrder = "@SortOrder";

    /// <summary>
    /// Khóa chính tự tăng của đáp án chữ. (Khóa chính, Tự tăng).
    /// </summary>
    public long QuestionAnswerKeyID { get; set; }

    /// <summary>
    /// ID câu hỏi trả lời ngắn.
    /// </summary>
    public long QuestionId { get; set; }

    /// <summary>
    /// Nội dung đáp án được chấp nhận.
    /// </summary>
    public string? AnswerText { get; set; }

    /// <summary>
    /// Cờ cho biết việc so khớp có phân biệt chữ hoa, chữ thường.
    /// </summary>
    public bool IsCaseSensitive { get; set; }

    /// <summary>
    /// Thứ tự ưu tiên của đáp án được chấp nhận.
    /// </summary>
    public int SortOrder { get; set; }
}
