// <auto-generated>
// File được sinh bởi tools/SimsObjectGenerator. Không sửa trực tiếp file này.
// </auto-generated>

#nullable enable

namespace SimsObject;

/// <summary>
/// [LMS] Các phương án học viên chọn cho một lần trả lời.
/// </summary>
public partial class LMS_StudentAnswerOptions
{
    public const string TableSchema = "dbo";
    public const string TableName = "LMS_StudentAnswerOptions";
    public const string QualifiedTableName = "[dbo].[LMS_StudentAnswerOptions]";

    public const string C_StudentAnswerId = "StudentAnswerId";
    public const string P_StudentAnswerId = "@StudentAnswerId";

    public const string C_QuestionOptionId = "QuestionOptionId";
    public const string P_QuestionOptionId = "@QuestionOptionId";

    /// <summary>
    /// ID lần trả lời của học viên. (Khóa chính).
    /// </summary>
    public long StudentAnswerId { get; set; }

    /// <summary>
    /// ID phương án học viên đã chọn. (Khóa chính).
    /// </summary>
    public long QuestionOptionId { get; set; }
}
