// <auto-generated>
// File được sinh bởi tools/SimsObjectGenerator. Không sửa trực tiếp file này.
// </auto-generated>

#nullable enable

namespace SimsObject;

/// <summary>
/// [LMS] Mỗi lượt học viên bắt đầu và nộp bài kiểm tra.
/// </summary>
public partial class LMS_QuizAttempts
{
    public const string TableSchema = "dbo";
    public const string TableName = "LMS_QuizAttempts";
    public const string QualifiedTableName = "[dbo].[LMS_QuizAttempts]";

    public const string C_QuizAttemptID = "QuizAttemptID";
    public const string P_QuizAttemptID = "@QuizAttemptID";

    public const string C_QuizID = "QuizID";
    public const string P_QuizID = "@QuizID";

    public const string C_StudentUserID = "StudentUserID";
    public const string P_StudentUserID = "@StudentUserID";

    public const string C_AttemptNumber = "AttemptNumber";
    public const string P_AttemptNumber = "@AttemptNumber";

    public const string C_StartedAt = "StartedAt";
    public const string P_StartedAt = "@StartedAt";

    public const string C_SubmittedAt = "SubmittedAt";
    public const string P_SubmittedAt = "@SubmittedAt";

    public const string C_Score = "Score";
    public const string P_Score = "@Score";

    public const string C_MaxScore = "MaxScore";
    public const string P_MaxScore = "@MaxScore";

    public const string C_ScorePercent = "ScorePercent";
    public const string P_ScorePercent = "@ScorePercent";

    public const string C_Passed = "Passed";
    public const string P_Passed = "@Passed";

    public const string C_AttemptStatus = "AttemptStatus";
    public const string P_AttemptStatus = "@AttemptStatus";

    /// <summary>
    /// Khóa chính lượt làm bài kiểm tra. (Khóa chính, Tự tăng).
    /// </summary>
    public long QuizAttemptID { get; set; }

    /// <summary>
    /// Cột QuizID của bảng LMS_QuizAttempts; thuộc schema nghiệp vụ LMS.
    /// </summary>
    public long QuizID { get; set; }

    /// <summary>
    /// Tài khoản học viên thực hiện lượt làm.
    /// </summary>
    public long StudentUserID { get; set; }

    /// <summary>
    /// Số thứ tự lượt làm của học viên.
    /// </summary>
    public int AttemptNumber { get; set; }

    /// <summary>
    /// Cột StartedAt của bảng LMS_QuizAttempts; thuộc schema nghiệp vụ LMS.
    /// </summary>
    public DateTime StartedAt { get; set; }

    /// <summary>
    /// Cột SubmittedAt của bảng LMS_QuizAttempts; thuộc schema nghiệp vụ LMS.
    /// </summary>
    public DateTime? SubmittedAt { get; set; }

    /// <summary>
    /// Cột Score của bảng LMS_QuizAttempts; thuộc schema nghiệp vụ LMS.
    /// </summary>
    public decimal? Score { get; set; }

    /// <summary>
    /// Cột MaxScore của bảng LMS_QuizAttempts; thuộc schema nghiệp vụ LMS.
    /// </summary>
    public decimal? MaxScore { get; set; }

    /// <summary>
    /// Phần trăm điểm sau khi backend chấm.
    /// </summary>
    public decimal? ScorePercent { get; set; }

    /// <summary>
    /// Cột Passed của bảng LMS_QuizAttempts; thuộc schema nghiệp vụ LMS.
    /// </summary>
    public bool? Passed { get; set; }

    /// <summary>
    /// Cột AttemptStatus của bảng LMS_QuizAttempts; thuộc schema nghiệp vụ LMS.
    /// </summary>
    public string? AttemptStatus { get; set; }
}
