// <auto-generated>
// File được sinh bởi tools/SimsObjectGenerator. Không sửa trực tiếp file này.
// </auto-generated>

#nullable enable

namespace SimsObject;

/// <summary>
/// [LMS] Phiên đo thời gian học viên ở lại môn học, chương hoặc bài học.
/// </summary>
public partial class LMS_StudySessions
{
    public const string TableSchema = "dbo";
    public const string TableName = "LMS_StudySessions";
    public const string QualifiedTableName = "[dbo].[LMS_StudySessions]";

    public const string C_StudySessionID = "StudySessionID";
    public const string P_StudySessionID = "@StudySessionID";

    public const string C_StudentUserID = "StudentUserID";
    public const string P_StudentUserID = "@StudentUserID";

    public const string C_ClassSubjectID = "ClassSubjectID";
    public const string P_ClassSubjectID = "@ClassSubjectID";

    public const string C_CourseID = "CourseID";
    public const string P_CourseID = "@CourseID";

    public const string C_ChapterID = "ChapterID";
    public const string P_ChapterID = "@ChapterID";

    public const string C_LessonID = "LessonID";
    public const string P_LessonID = "@LessonID";

    public const string C_StartedAt = "StartedAt";
    public const string P_StartedAt = "@StartedAt";

    public const string C_LastHeartbeatAt = "LastHeartbeatAt";
    public const string P_LastHeartbeatAt = "@LastHeartbeatAt";

    public const string C_EndedAt = "EndedAt";
    public const string P_EndedAt = "@EndedAt";

    public const string C_ActiveDurationSeconds = "ActiveDurationSeconds";
    public const string P_ActiveDurationSeconds = "@ActiveDurationSeconds";

    public const string C_PageUrl = "PageUrl";
    public const string P_PageUrl = "@PageUrl";

    public const string C_ClientSessionKey = "ClientSessionKey";
    public const string P_ClientSessionKey = "@ClientSessionKey";

    public const string C_IsCompleted = "IsCompleted";
    public const string P_IsCompleted = "@IsCompleted";

    public const string C_IsAggregated = "IsAggregated";
    public const string P_IsAggregated = "@IsAggregated";

    /// <summary>
    /// Cột StudySessionID của bảng LMS_StudySessions, lưu thông tin phục vụ nghiệp vụ được mô tả ở cấp bảng. (Khóa chính).
    /// </summary>
    public Guid StudySessionID { get; set; }

    /// <summary>
    /// Cột StudentUserID của bảng LMS_StudySessions, lưu thông tin phục vụ nghiệp vụ được mô tả ở cấp bảng.
    /// </summary>
    public long StudentUserID { get; set; }

    /// <summary>
    /// Cột ClassSubjectID của bảng LMS_StudySessions, lưu thông tin phục vụ nghiệp vụ được mô tả ở cấp bảng.
    /// </summary>
    public long? ClassSubjectID { get; set; }

    /// <summary>
    /// Cột CourseID của bảng LMS_StudySessions, lưu thông tin phục vụ nghiệp vụ được mô tả ở cấp bảng.
    /// </summary>
    public long? CourseID { get; set; }

    /// <summary>
    /// Cột ChapterID của bảng LMS_StudySessions, lưu thông tin phục vụ nghiệp vụ được mô tả ở cấp bảng.
    /// </summary>
    public long? ChapterID { get; set; }

    /// <summary>
    /// Cột LessonID của bảng LMS_StudySessions, lưu thông tin phục vụ nghiệp vụ được mô tả ở cấp bảng.
    /// </summary>
    public long? LessonID { get; set; }

    /// <summary>
    /// Cột StartedAt của bảng LMS_StudySessions, lưu thông tin phục vụ nghiệp vụ được mô tả ở cấp bảng.
    /// </summary>
    public DateTime StartedAt { get; set; }

    /// <summary>
    /// Thời điểm gần nhất trình duyệt xác nhận học viên vẫn đang ở trang học.
    /// </summary>
    public DateTime LastHeartbeatAt { get; set; }

    /// <summary>
    /// Cột EndedAt của bảng LMS_StudySessions, lưu thông tin phục vụ nghiệp vụ được mô tả ở cấp bảng.
    /// </summary>
    public DateTime? EndedAt { get; set; }

    /// <summary>
    /// Tổng số giây hoạt động hợp lệ, được cộng qua mỗi heartbeat.
    /// </summary>
    public int ActiveDurationSeconds { get; set; }

    /// <summary>
    /// Cột PageUrl của bảng LMS_StudySessions, lưu thông tin phục vụ nghiệp vụ được mô tả ở cấp bảng.
    /// </summary>
    public string? PageUrl { get; set; }

    /// <summary>
    /// Cột ClientSessionKey của bảng LMS_StudySessions, lưu thông tin phục vụ nghiệp vụ được mô tả ở cấp bảng.
    /// </summary>
    public string? ClientSessionKey { get; set; }

    /// <summary>
    /// Cột IsCompleted của bảng LMS_StudySessions, lưu thông tin phục vụ nghiệp vụ được mô tả ở cấp bảng.
    /// </summary>
    public bool IsCompleted { get; set; }

    /// <summary>
    /// Cờ cho biết thời lượng phiên đã được cộng vào tiến độ bài học.
    /// </summary>
    public bool IsAggregated { get; set; }
}
