// <auto-generated>
// File được sinh bởi tools/SimsObjectGenerator. Không sửa trực tiếp file này.
// </auto-generated>

#nullable enable

namespace SimsObject;

/// <summary>
/// [LMS] Câu trả lời, điểm số và trạng thái chấm của học viên.
/// </summary>
public partial class LMS_StudentAnswers
{
    public const string TableSchema = "dbo";
    public const string TableName = "LMS_StudentAnswers";
    public const string QualifiedTableName = "[dbo].[LMS_StudentAnswers]";

    public const string C_StudentAnswerID = "StudentAnswerID";
    public const string P_StudentAnswerID = "@StudentAnswerID";

    public const string C_StudentUserID = "StudentUserID";
    public const string P_StudentUserID = "@StudentUserID";

    public const string C_CourseId = "CourseId";
    public const string P_CourseId = "@CourseId";

    public const string C_LessonId = "LessonId";
    public const string P_LessonId = "@LessonId";

    public const string C_VideoId = "VideoId";
    public const string P_VideoId = "@VideoId";

    public const string C_VideoInteractionID = "VideoInteractionID";
    public const string P_VideoInteractionID = "@VideoInteractionID";

    public const string C_QuestionId = "QuestionId";
    public const string P_QuestionId = "@QuestionId";

    public const string C_AttemptNumber = "AttemptNumber";
    public const string P_AttemptNumber = "@AttemptNumber";

    public const string C_AnswerText = "AnswerText";
    public const string P_AnswerText = "@AnswerText";

    public const string C_IsCorrect = "IsCorrect";
    public const string P_IsCorrect = "@IsCorrect";

    public const string C_ScoreAwarded = "ScoreAwarded";
    public const string P_ScoreAwarded = "@ScoreAwarded";

    public const string C_ReviewStatus = "ReviewStatus";
    public const string P_ReviewStatus = "@ReviewStatus";

    public const string C_AnsweredAt = "AnsweredAt";
    public const string P_AnsweredAt = "@AnsweredAt";

    public const string C_TimeInVideoSeconds = "TimeInVideoSeconds";
    public const string P_TimeInVideoSeconds = "@TimeInVideoSeconds";

    public const string C_TimeSpentSeconds = "TimeSpentSeconds";
    public const string P_TimeSpentSeconds = "@TimeSpentSeconds";

    public const string C_ReviewedByUserID = "ReviewedByUserID";
    public const string P_ReviewedByUserID = "@ReviewedByUserID";

    public const string C_ReviewedAt = "ReviewedAt";
    public const string P_ReviewedAt = "@ReviewedAt";

    public const string C_ReviewerComment = "ReviewerComment";
    public const string P_ReviewerComment = "@ReviewerComment";

    public const string C_VideoVersionID = "VideoVersionID";
    public const string P_VideoVersionID = "@VideoVersionID";

    public const string C_ContentInteractionID = "ContentInteractionID";
    public const string P_ContentInteractionID = "@ContentInteractionID";

    /// <summary>
    /// Khóa chính tự tăng của lần trả lời. (Khóa chính, Tự tăng).
    /// </summary>
    public long StudentAnswerID { get; set; }

    /// <summary>
    /// ID học viên thực hiện câu trả lời.
    /// </summary>
    public long StudentUserID { get; set; }

    /// <summary>
    /// ID khóa học phát sinh câu trả lời.
    /// </summary>
    public long CourseId { get; set; }

    /// <summary>
    /// ID bài học phát sinh câu trả lời.
    /// </summary>
    public long LessonId { get; set; }

    /// <summary>
    /// ID video phát sinh câu trả lời; rỗng nếu không từ video.
    /// </summary>
    public long? VideoId { get; set; }

    /// <summary>
    /// ID tương tác video phát sinh câu trả lời.
    /// </summary>
    public long? VideoInteractionID { get; set; }

    /// <summary>
    /// ID câu hỏi được trả lời.
    /// </summary>
    public long QuestionId { get; set; }

    /// <summary>
    /// Số thứ tự lần thử của học viên với câu hỏi.
    /// </summary>
    public int AttemptNumber { get; set; }

    /// <summary>
    /// Nội dung trả lời dạng chữ của học viên.
    /// </summary>
    public string? AnswerText { get; set; }

    /// <summary>
    /// Kết quả đúng/sai; rỗng khi chưa chấm.
    /// </summary>
    public bool? IsCorrect { get; set; }

    /// <summary>
    /// Số điểm được trao cho lần trả lời.
    /// </summary>
    public decimal ScoreAwarded { get; set; }

    /// <summary>
    /// Trạng thái chấm hoặc duyệt câu trả lời.
    /// </summary>
    public string? ReviewStatus { get; set; }

    /// <summary>
    /// Thời điểm học viên trả lời theo UTC.
    /// </summary>
    public DateTime AnsweredAt { get; set; }

    /// <summary>
    /// Vị trí video khi học viên trả lời, đơn vị giây.
    /// </summary>
    public decimal? TimeInVideoSeconds { get; set; }

    /// <summary>
    /// Thời gian học viên dùng để trả lời, đơn vị giây.
    /// </summary>
    public int? TimeSpentSeconds { get; set; }

    /// <summary>
    /// ID người dùng chấm hoặc duyệt câu trả lời.
    /// </summary>
    public long? ReviewedByUserID { get; set; }

    /// <summary>
    /// Thời điểm chấm hoặc duyệt câu trả lời theo UTC.
    /// </summary>
    public DateTime? ReviewedAt { get; set; }

    /// <summary>
    /// Nhận xét của người chấm dành cho học viên.
    /// </summary>
    public string? ReviewerComment { get; set; }

    /// <summary>
    /// ID phiên bản video tại thời điểm học viên trả lời.
    /// </summary>
    public long? VideoVersionID { get; set; }

    /// <summary>
    /// Câu hỏi bài đọc tương tác tương ứng; rỗng đối với video hoặc quiz.
    /// </summary>
    public long? ContentInteractionID { get; set; }
}
