// <auto-generated>
// File được sinh bởi tools/SimsObjectGenerator. Không sửa trực tiếp file này.
// </auto-generated>

#nullable enable

namespace SimsObject;

/// <summary>
/// [LMS] Tiến độ xem video chi tiết của học viên.
/// </summary>
public partial class LMS_StudentVideoProgress
{
    public const string TableSchema = "dbo";
    public const string TableName = "LMS_StudentVideoProgress";
    public const string QualifiedTableName = "[dbo].[LMS_StudentVideoProgress]";

    public const string C_StudentVideoProgressID = "StudentVideoProgressID";
    public const string P_StudentVideoProgressID = "@StudentVideoProgressID";

    public const string C_StudentUserID = "StudentUserID";
    public const string P_StudentUserID = "@StudentUserID";

    public const string C_CourseId = "CourseId";
    public const string P_CourseId = "@CourseId";

    public const string C_LessonId = "LessonId";
    public const string P_LessonId = "@LessonId";

    public const string C_VideoId = "VideoId";
    public const string P_VideoId = "@VideoId";

    public const string C_CurrentTimeSeconds = "CurrentTimeSeconds";
    public const string P_CurrentTimeSeconds = "@CurrentTimeSeconds";

    public const string C_MaxWatchedTimeSeconds = "MaxWatchedTimeSeconds";
    public const string P_MaxWatchedTimeSeconds = "@MaxWatchedTimeSeconds";

    public const string C_WatchedSeconds = "WatchedSeconds";
    public const string P_WatchedSeconds = "@WatchedSeconds";

    public const string C_WatchPercent = "WatchPercent";
    public const string P_WatchPercent = "@WatchPercent";

    public const string C_Completed = "Completed";
    public const string P_Completed = "@Completed";

    public const string C_StartedAt = "StartedAt";
    public const string P_StartedAt = "@StartedAt";

    public const string C_CompletedAt = "CompletedAt";
    public const string P_CompletedAt = "@CompletedAt";

    public const string C_LastAccessAt = "LastAccessAt";
    public const string P_LastAccessAt = "@LastAccessAt";

    public const string C_CreatedAt = "CreatedAt";
    public const string P_CreatedAt = "@CreatedAt";

    public const string C_UpdatedAt = "UpdatedAt";
    public const string P_UpdatedAt = "@UpdatedAt";

    public const string C_RowVersion = "RowVersion";
    public const string P_RowVersion = "@RowVersion";

    public const string C_VideoVersionID = "VideoVersionID";
    public const string P_VideoVersionID = "@VideoVersionID";

    /// <summary>
    /// Khóa chính tự tăng của tiến độ video. (Khóa chính, Tự tăng).
    /// </summary>
    public long StudentVideoProgressID { get; set; }

    /// <summary>
    /// ID học viên xem video.
    /// </summary>
    public long StudentUserID { get; set; }

    /// <summary>
    /// ID khóa học chứa video.
    /// </summary>
    public long CourseId { get; set; }

    /// <summary>
    /// ID bài học chứa video.
    /// </summary>
    public long LessonId { get; set; }

    /// <summary>
    /// ID video được theo dõi.
    /// </summary>
    public long VideoId { get; set; }

    /// <summary>
    /// Vị trí phát hiện tại của học viên, đơn vị giây.
    /// </summary>
    public decimal CurrentTimeSeconds { get; set; }

    /// <summary>
    /// Vị trí xa nhất học viên đã xem hợp lệ, đơn vị giây.
    /// </summary>
    public decimal MaxWatchedTimeSeconds { get; set; }

    /// <summary>
    /// Tổng thời lượng xem hợp lệ, đơn vị giây.
    /// </summary>
    public decimal WatchedSeconds { get; set; }

    /// <summary>
    /// Tỷ lệ phần trăm video đã xem hợp lệ.
    /// </summary>
    public decimal WatchPercent { get; set; }

    /// <summary>
    /// Cờ cho biết video đã đạt điều kiện hoàn thành.
    /// </summary>
    public bool Completed { get; set; }

    /// <summary>
    /// Thời điểm bắt đầu xem video theo UTC.
    /// </summary>
    public DateTime StartedAt { get; set; }

    /// <summary>
    /// Thời điểm hoàn thành video theo UTC.
    /// </summary>
    public DateTime? CompletedAt { get; set; }

    /// <summary>
    /// Thời điểm truy cập video gần nhất theo UTC.
    /// </summary>
    public DateTime LastAccessAt { get; set; }

    /// <summary>
    /// Thời điểm tạo bản ghi tiến độ video theo UTC.
    /// </summary>
    public DateTime CreatedAt { get; set; }

    /// <summary>
    /// Thời điểm cập nhật tiến độ video gần nhất theo UTC.
    /// </summary>
    public DateTime? UpdatedAt { get; set; }

    /// <summary>
    /// Phiên bản hàng tự động dùng kiểm soát cập nhật đồng thời.
    /// </summary>
    public byte[]? RowVersion { get; set; }

    /// <summary>
    /// ID phiên bản video mà học viên đã xem và phát sinh tiến độ.
    /// </summary>
    public long? VideoVersionID { get; set; }
}
