// <auto-generated>
// File được sinh bởi tools/SimsObjectGenerator. Không sửa trực tiếp file này.
// </auto-generated>

#nullable enable

namespace SimsObject;

/// <summary>
/// [SIM] Video tương tác độc lập đã soạn sẵn, có thể được nhiều bài học tham chiếu mà không nhân bản.
/// </summary>
public partial class SIM_Videos
{
    public const string TableSchema = "dbo";
    public const string TableName = "SIM_Videos";
    public const string QualifiedTableName = "[dbo].[SIM_Videos]";

    public const string C_VideoID = "VideoID";
    public const string P_VideoID = "@VideoID";

    public const string C_Title = "Title";
    public const string P_Title = "@Title";

    public const string C_VideoUrl = "VideoUrl";
    public const string P_VideoUrl = "@VideoUrl";

    public const string C_PosterUrl = "PosterUrl";
    public const string P_PosterUrl = "@PosterUrl";

    public const string C_DurationSeconds = "DurationSeconds";
    public const string P_DurationSeconds = "@DurationSeconds";

    public const string C_AllowSeek = "AllowSeek";
    public const string P_AllowSeek = "@AllowSeek";

    public const string C_AllowSpeed = "AllowSpeed";
    public const string P_AllowSpeed = "@AllowSpeed";

    public const string C_RequiredWatchPercent = "RequiredWatchPercent";
    public const string P_RequiredWatchPercent = "@RequiredWatchPercent";

    public const string C_Status = "Status";
    public const string P_Status = "@Status";

    public const string C_CreatedAt = "CreatedAt";
    public const string P_CreatedAt = "@CreatedAt";

    public const string C_UpdatedAt = "UpdatedAt";
    public const string P_UpdatedAt = "@UpdatedAt";

    public const string C_VideoAssetId = "VideoAssetId";
    public const string P_VideoAssetId = "@VideoAssetId";

    public const string C_CurrentVideoVersionID = "CurrentVideoVersionID";
    public const string P_CurrentVideoVersionID = "@CurrentVideoVersionID";

    public const string C_SourceType = "SourceType";
    public const string P_SourceType = "@SourceType";

    /// <summary>
    /// Khóa chính tự tăng của cấu hình video bài học. (Khóa chính, Tự tăng).
    /// </summary>
    public long VideoID { get; set; }

    /// <summary>
    /// Tên hiển thị của video trong bài học.
    /// </summary>
    public string? Title { get; set; }

    /// <summary>
    /// Đường dẫn phát video; giữ để tương thích dữ liệu cũ.
    /// </summary>
    public string? VideoUrl { get; set; }

    /// <summary>
    /// Đường dẫn ảnh đại diện của video.
    /// </summary>
    public string? PosterUrl { get; set; }

    /// <summary>
    /// Thời lượng video tính bằng giây.
    /// </summary>
    public int DurationSeconds { get; set; }

    /// <summary>
    /// Cờ cho phép học viên tua đến vị trí chưa xem.
    /// </summary>
    public bool AllowSeek { get; set; }

    /// <summary>
    /// Cờ cho phép học viên thay đổi tốc độ phát.
    /// </summary>
    public bool AllowSpeed { get; set; }

    /// <summary>
    /// Tỷ lệ phần trăm video phải xem để được tính hoàn thành.
    /// </summary>
    public decimal RequiredWatchPercent { get; set; }

    /// <summary>
    /// Trạng thái sử dụng của video.
    /// </summary>
    public string? Status { get; set; }

    /// <summary>
    /// Thời điểm tạo cấu hình video theo UTC.
    /// </summary>
    public DateTime CreatedAt { get; set; }

    /// <summary>
    /// Thời điểm cập nhật cấu hình video gần nhất theo UTC.
    /// </summary>
    public DateTime? UpdatedAt { get; set; }

    /// <summary>
    /// ID tệp trong thư viện video được bài học sử dụng.
    /// </summary>
    public long? VideoAssetId { get; set; }

    /// <summary>
    /// ID phiên bản mới nhất dùng cho lần gắn video tiếp theo và màn hình biên tập.
    /// </summary>
    public long? CurrentVideoVersionID { get; set; }

    /// <summary>
    /// Loại nguồn phát hiện tại của video tương tác: LOCAL hoặc YOUTUBE.
    /// </summary>
    public string? SourceType { get; set; }
}
