// <auto-generated>
// File được sinh bởi tools/SimsObjectGenerator. Không sửa trực tiếp file này.
// </auto-generated>

#nullable enable

namespace SimsObject;

/// <summary>
/// [SIM] Lịch sử phiên bản bất biến của video; bài học ghim một phiên bản cụ thể để tránh thay đổi nội dung ngoài ý muốn.
/// </summary>
public partial class SIM_VideoVersions
{
    public const string TableSchema = "dbo";
    public const string TableName = "SIM_VideoVersions";
    public const string QualifiedTableName = "[dbo].[SIM_VideoVersions]";

    public const string C_VideoVersionID = "VideoVersionID";
    public const string P_VideoVersionID = "@VideoVersionID";

    public const string C_VideoID = "VideoID";
    public const string P_VideoID = "@VideoID";

    public const string C_VersionNumber = "VersionNumber";
    public const string P_VersionNumber = "@VersionNumber";

    public const string C_Title = "Title";
    public const string P_Title = "@Title";

    public const string C_VideoUrl = "VideoUrl";
    public const string P_VideoUrl = "@VideoUrl";

    public const string C_PosterUrl = "PosterUrl";
    public const string P_PosterUrl = "@PosterUrl";

    public const string C_DurationSeconds = "DurationSeconds";
    public const string P_DurationSeconds = "@DurationSeconds";

    public const string C_AllowSeek = "AllowSeek";
    public const string P_AllowSeek = "@AllowSeek";

    public const string C_AllowSpeed = "AllowSpeed";
    public const string P_AllowSpeed = "@AllowSpeed";

    public const string C_RequiredWatchPercent = "RequiredWatchPercent";
    public const string P_RequiredWatchPercent = "@RequiredWatchPercent";

    public const string C_OriginalFileName = "OriginalFileName";
    public const string P_OriginalFileName = "@OriginalFileName";

    public const string C_FileSize = "FileSize";
    public const string P_FileSize = "@FileSize";

    public const string C_MimeType = "MimeType";
    public const string P_MimeType = "@MimeType";

    public const string C_ChangeSummary = "ChangeSummary";
    public const string P_ChangeSummary = "@ChangeSummary";

    public const string C_VersionStatus = "VersionStatus";
    public const string P_VersionStatus = "@VersionStatus";

    public const string C_CreatedByUserID = "CreatedByUserID";
    public const string P_CreatedByUserID = "@CreatedByUserID";

    public const string C_CreatedAt = "CreatedAt";
    public const string P_CreatedAt = "@CreatedAt";

    public const string C_PublishedByUserID = "PublishedByUserID";
    public const string P_PublishedByUserID = "@PublishedByUserID";

    public const string C_PublishedAt = "PublishedAt";
    public const string P_PublishedAt = "@PublishedAt";

    public const string C_RowVersion = "RowVersion";
    public const string P_RowVersion = "@RowVersion";

    public const string C_SourceType = "SourceType";
    public const string P_SourceType = "@SourceType";

    /// <summary>
    /// Khóa chính tự tăng của phiên bản video. (Khóa chính, Tự tăng).
    /// </summary>
    public long VideoVersionID { get; set; }

    /// <summary>
    /// ID video gốc sở hữu phiên bản.
    /// </summary>
    public long VideoID { get; set; }

    /// <summary>
    /// Số phiên bản tăng dần trong phạm vi một video.
    /// </summary>
    public int VersionNumber { get; set; }

    /// <summary>
    /// Tên video được chụp tại thời điểm tạo phiên bản.
    /// </summary>
    public string? Title { get; set; }

    /// <summary>
    /// Đường dẫn file video tương đối trong project của phiên bản.
    /// </summary>
    public string? VideoUrl { get; set; }

    /// <summary>
    /// Đường dẫn ảnh đại diện của phiên bản video.
    /// </summary>
    public string? PosterUrl { get; set; }

    /// <summary>
    /// Thời lượng của file thuộc phiên bản, tính bằng giây.
    /// </summary>
    public int DurationSeconds { get; set; }

    /// <summary>
    /// Cho phép học viên tua video trong phiên bản.
    /// </summary>
    public bool AllowSeek { get; set; }

    /// <summary>
    /// Cho phép học viên thay đổi tốc độ phát.
    /// </summary>
    public bool AllowSpeed { get; set; }

    /// <summary>
    /// Tỷ lệ xem tối thiểu để hoàn thành phiên bản video.
    /// </summary>
    public decimal RequiredWatchPercent { get; set; }

    /// <summary>
    /// Tên gốc của file video khi được tải lên.
    /// </summary>
    public string? OriginalFileName { get; set; }

    /// <summary>
    /// Kích thước file của phiên bản video, tính bằng byte.
    /// </summary>
    public long? FileSize { get; set; }

    /// <summary>
    /// Kiểu MIME của file video thuộc phiên bản.
    /// </summary>
    public string? MimeType { get; set; }

    /// <summary>
    /// Nội dung mô tả lý do tạo phiên bản mới.
    /// </summary>
    public string? ChangeSummary { get; set; }

    /// <summary>
    /// Trạng thái phiên bản: DRAFT, PUBLISHED hoặc ARCHIVED.
    /// </summary>
    public string? VersionStatus { get; set; }

    /// <summary>
    /// ID người dùng tạo phiên bản.
    /// </summary>
    public long CreatedByUserID { get; set; }

    /// <summary>
    /// Thời điểm tạo phiên bản theo UTC.
    /// </summary>
    public DateTime CreatedAt { get; set; }

    /// <summary>
    /// ID người dùng xuất bản phiên bản.
    /// </summary>
    public long? PublishedByUserID { get; set; }

    /// <summary>
    /// Thời điểm xuất bản phiên bản theo UTC.
    /// </summary>
    public DateTime? PublishedAt { get; set; }

    /// <summary>
    /// Dấu phiên bản hàng do SQL Server quản lý để kiểm soát đồng thời.
    /// </summary>
    public byte[]? RowVersion { get; set; }

    /// <summary>
    /// Loại nguồn được chụp tại phiên bản video: LOCAL hoặc YOUTUBE.
    /// </summary>
    public string? SourceType { get; set; }
}
