// <auto-generated>
// File được sinh bởi tools/SimsObjectGenerator. Không sửa trực tiếp file này.
// </auto-generated>

#nullable enable

namespace SimsObject;

/// <summary>
/// [SIM] Danh mục phân loại khóa học.
/// </summary>
public partial class SIM_CourseCategories
{
    public const string TableSchema = "dbo";
    public const string TableName = "SIM_CourseCategories";
    public const string QualifiedTableName = "[dbo].[SIM_CourseCategories]";

    public const string C_CourseCategoryID = "CourseCategoryID";
    public const string P_CourseCategoryID = "@CourseCategoryID";

    public const string C_Code = "Code";
    public const string P_Code = "@Code";

    public const string C_Name = "Name";
    public const string P_Name = "@Name";

    public const string C_Description = "Description";
    public const string P_Description = "@Description";

    public const string C_SortOrder = "SortOrder";
    public const string P_SortOrder = "@SortOrder";

    public const string C_Status = "Status";
    public const string P_Status = "@Status";

    /// <summary>
    /// Khóa chính tự tăng của danh mục khóa học. (Khóa chính, Tự tăng).
    /// </summary>
    public long CourseCategoryID { get; set; }

    /// <summary>
    /// Mã duy nhất của danh mục khóa học.
    /// </summary>
    public string? Code { get; set; }

    /// <summary>
    /// Tên hiển thị của danh mục khóa học.
    /// </summary>
    public string? Name { get; set; }

    /// <summary>
    /// Mô tả nội dung của danh mục khóa học.
    /// </summary>
    public string? Description { get; set; }

    /// <summary>
    /// Thứ tự hiển thị của danh mục, số nhỏ hiển thị trước.
    /// </summary>
    public int SortOrder { get; set; }

    /// <summary>
    /// Trạng thái sử dụng của danh mục khóa học.
    /// </summary>
    public string? Status { get; set; }
}
