// <auto-generated>
// File được sinh bởi tools/SimsObjectGenerator. Không sửa trực tiếp file này.
// </auto-generated>

#nullable enable

namespace SimsObject;

/// <summary>
/// [SIM] Lớp hành chính thuộc khoa và khóa tuyển sinh.
/// </summary>
public partial class SIM_Class
{
    public const string TableSchema = "dbo";
    public const string TableName = "SIM_Class";
    public const string QualifiedTableName = "[dbo].[SIM_Class]";

    public const string C_DataGroupID = "DataGroupID";
    public const string P_DataGroupID = "@DataGroupID";

    public const string C_ClassID = "ClassID";
    public const string P_ClassID = "@ClassID";

    public const string C_ClassName = "ClassName";
    public const string P_ClassName = "@ClassName";

    public const string C_ClassShortName = "ClassShortName";
    public const string P_ClassShortName = "@ClassShortName";

    public const string C_ScienceID = "ScienceID";
    public const string P_ScienceID = "@ScienceID";

    public const string C_CourseID = "CourseID";
    public const string P_CourseID = "@CourseID";

    public const string C_TrainingLevelID = "TrainingLevelID";
    public const string P_TrainingLevelID = "@TrainingLevelID";

    public const string C_TrainingType = "TrainingType";
    public const string P_TrainingType = "@TrainingType";

    public const string C_ClassSize = "ClassSize";
    public const string P_ClassSize = "@ClassSize";

    public const string C_StartAt = "StartAt";
    public const string P_StartAt = "@StartAt";

    public const string C_FinishAt = "FinishAt";
    public const string P_FinishAt = "@FinishAt";

    public const string C_ManagerTeacherID = "ManagerTeacherID";
    public const string P_ManagerTeacherID = "@ManagerTeacherID";

    public const string C_IsActived = "IsActived";
    public const string P_IsActived = "@IsActived";

    public const string C_Description = "Description";
    public const string P_Description = "@Description";

    /// <summary>
    /// Cột DataGroupID của bảng SIM_Class, lưu thông tin phục vụ nghiệp vụ được mô tả ở cấp bảng. (Khóa chính).
    /// </summary>
    public int DataGroupID { get; set; }

    /// <summary>
    /// Cột ClassID của bảng SIM_Class, lưu thông tin phục vụ nghiệp vụ được mô tả ở cấp bảng. (Khóa chính).
    /// </summary>
    public string? ClassID { get; set; }

    /// <summary>
    /// Cột ClassName của bảng SIM_Class, lưu thông tin phục vụ nghiệp vụ được mô tả ở cấp bảng.
    /// </summary>
    public string? ClassName { get; set; }

    /// <summary>
    /// Cột ClassShortName của bảng SIM_Class, lưu thông tin phục vụ nghiệp vụ được mô tả ở cấp bảng.
    /// </summary>
    public string? ClassShortName { get; set; }

    /// <summary>
    /// Cột ScienceID của bảng SIM_Class, lưu thông tin phục vụ nghiệp vụ được mô tả ở cấp bảng.
    /// </summary>
    public string? ScienceID { get; set; }

    /// <summary>
    /// Cột CourseID của bảng SIM_Class, lưu thông tin phục vụ nghiệp vụ được mô tả ở cấp bảng.
    /// </summary>
    public string? CourseID { get; set; }

    /// <summary>
    /// Cột TrainingLevelID của bảng SIM_Class, lưu thông tin phục vụ nghiệp vụ được mô tả ở cấp bảng.
    /// </summary>
    public string? TrainingLevelID { get; set; }

    /// <summary>
    /// Cột TrainingType của bảng SIM_Class, lưu thông tin phục vụ nghiệp vụ được mô tả ở cấp bảng.
    /// </summary>
    public string? TrainingType { get; set; }

    /// <summary>
    /// Cột ClassSize của bảng SIM_Class, lưu thông tin phục vụ nghiệp vụ được mô tả ở cấp bảng.
    /// </summary>
    public int ClassSize { get; set; }

    /// <summary>
    /// Cột StartAt của bảng SIM_Class, lưu thông tin phục vụ nghiệp vụ được mô tả ở cấp bảng.
    /// </summary>
    public DateTime? StartAt { get; set; }

    /// <summary>
    /// Cột FinishAt của bảng SIM_Class, lưu thông tin phục vụ nghiệp vụ được mô tả ở cấp bảng.
    /// </summary>
    public DateTime? FinishAt { get; set; }

    /// <summary>
    /// Cột ManagerTeacherID của bảng SIM_Class, lưu thông tin phục vụ nghiệp vụ được mô tả ở cấp bảng.
    /// </summary>
    public string? ManagerTeacherID { get; set; }

    /// <summary>
    /// Cột IsActived của bảng SIM_Class, lưu thông tin phục vụ nghiệp vụ được mô tả ở cấp bảng.
    /// </summary>
    public bool IsActived { get; set; }

    /// <summary>
    /// Cột Description của bảng SIM_Class, lưu thông tin phục vụ nghiệp vụ được mô tả ở cấp bảng.
    /// </summary>
    public string? Description { get; set; }
}
