// <auto-generated>
// File được sinh bởi tools/SimsObjectGenerator. Không sửa trực tiếp file này.
// </auto-generated>

#nullable enable

namespace SimsObject;

/// <summary>
/// [SIM] Thời khóa biểu học theo từng môn học lớp và khoảng thời gian hiệu lực.
/// </summary>
public partial class SIM_Timetable
{
    public const string TableSchema = "dbo";
    public const string TableName = "SIM_Timetable";
    public const string QualifiedTableName = "[dbo].[SIM_Timetable]";

    public const string C_TimetableID = "TimetableID";
    public const string P_TimetableID = "@TimetableID";

    public const string C_DataGroupID = "DataGroupID";
    public const string P_DataGroupID = "@DataGroupID";

    public const string C_ClassSubjectID = "ClassSubjectID";
    public const string P_ClassSubjectID = "@ClassSubjectID";

    public const string C_DayOfWeek = "DayOfWeek";
    public const string P_DayOfWeek = "@DayOfWeek";

    public const string C_StartPeriod = "StartPeriod";
    public const string P_StartPeriod = "@StartPeriod";

    public const string C_EndPeriod = "EndPeriod";
    public const string P_EndPeriod = "@EndPeriod";

    public const string C_StartTime = "StartTime";
    public const string P_StartTime = "@StartTime";

    public const string C_EndTime = "EndTime";
    public const string P_EndTime = "@EndTime";

    public const string C_RoomName = "RoomName";
    public const string P_RoomName = "@RoomName";

    public const string C_EffectiveFrom = "EffectiveFrom";
    public const string P_EffectiveFrom = "@EffectiveFrom";

    public const string C_EffectiveTo = "EffectiveTo";
    public const string P_EffectiveTo = "@EffectiveTo";

    public const string C_TimetableStatus = "TimetableStatus";
    public const string P_TimetableStatus = "@TimetableStatus";

    public const string C_CreatedDate = "CreatedDate";
    public const string P_CreatedDate = "@CreatedDate";

    public const string C_UpdatedDate = "UpdatedDate";
    public const string P_UpdatedDate = "@UpdatedDate";

    /// <summary>
    /// Cột TimetableID của bảng SIM_Timetable, lưu thông tin phục vụ nghiệp vụ được mô tả ở cấp bảng. (Khóa chính, Tự tăng).
    /// </summary>
    public long TimetableID { get; set; }

    /// <summary>
    /// Cột DataGroupID của bảng SIM_Timetable, lưu thông tin phục vụ nghiệp vụ được mô tả ở cấp bảng.
    /// </summary>
    public int DataGroupID { get; set; }

    /// <summary>
    /// Cột ClassSubjectID của bảng SIM_Timetable, lưu thông tin phục vụ nghiệp vụ được mô tả ở cấp bảng.
    /// </summary>
    public long ClassSubjectID { get; set; }

    /// <summary>
    /// Cột DayOfWeek của bảng SIM_Timetable, lưu thông tin phục vụ nghiệp vụ được mô tả ở cấp bảng.
    /// </summary>
    public byte DayOfWeek { get; set; }

    /// <summary>
    /// Cột StartPeriod của bảng SIM_Timetable, lưu thông tin phục vụ nghiệp vụ được mô tả ở cấp bảng.
    /// </summary>
    public byte? StartPeriod { get; set; }

    /// <summary>
    /// Cột EndPeriod của bảng SIM_Timetable, lưu thông tin phục vụ nghiệp vụ được mô tả ở cấp bảng.
    /// </summary>
    public byte? EndPeriod { get; set; }

    /// <summary>
    /// Cột StartTime của bảng SIM_Timetable, lưu thông tin phục vụ nghiệp vụ được mô tả ở cấp bảng.
    /// </summary>
    public TimeSpan? StartTime { get; set; }

    /// <summary>
    /// Cột EndTime của bảng SIM_Timetable, lưu thông tin phục vụ nghiệp vụ được mô tả ở cấp bảng.
    /// </summary>
    public TimeSpan? EndTime { get; set; }

    /// <summary>
    /// Cột RoomName của bảng SIM_Timetable, lưu thông tin phục vụ nghiệp vụ được mô tả ở cấp bảng.
    /// </summary>
    public string? RoomName { get; set; }

    /// <summary>
    /// Cột EffectiveFrom của bảng SIM_Timetable, lưu thông tin phục vụ nghiệp vụ được mô tả ở cấp bảng.
    /// </summary>
    public DateTime? EffectiveFrom { get; set; }

    /// <summary>
    /// Cột EffectiveTo của bảng SIM_Timetable, lưu thông tin phục vụ nghiệp vụ được mô tả ở cấp bảng.
    /// </summary>
    public DateTime? EffectiveTo { get; set; }

    /// <summary>
    /// Cột TimetableStatus của bảng SIM_Timetable, lưu thông tin phục vụ nghiệp vụ được mô tả ở cấp bảng.
    /// </summary>
    public byte TimetableStatus { get; set; }

    /// <summary>
    /// Cột CreatedDate của bảng SIM_Timetable, lưu thông tin phục vụ nghiệp vụ được mô tả ở cấp bảng.
    /// </summary>
    public DateTime CreatedDate { get; set; }

    /// <summary>
    /// Cột UpdatedDate của bảng SIM_Timetable, lưu thông tin phục vụ nghiệp vụ được mô tả ở cấp bảng.
    /// </summary>
    public DateTime? UpdatedDate { get; set; }
}
