// <auto-generated>
// File được sinh bởi tools/SimsObjectGenerator. Không sửa trực tiếp file này.
// </auto-generated>

#nullable enable

namespace SimsObject;

/// <summary>
/// [SIM] Thư viện tài nguyên video dùng lại cho nhiều bài học.
/// </summary>
public partial class SIM_VideoAssets
{
    public const string TableSchema = "dbo";
    public const string TableName = "SIM_VideoAssets";
    public const string QualifiedTableName = "[dbo].[SIM_VideoAssets]";

    public const string C_VideoAssetID = "VideoAssetID";
    public const string P_VideoAssetID = "@VideoAssetID";

    public const string C_Title = "Title";
    public const string P_Title = "@Title";

    public const string C_VideoUrl = "VideoUrl";
    public const string P_VideoUrl = "@VideoUrl";

    public const string C_PosterUrl = "PosterUrl";
    public const string P_PosterUrl = "@PosterUrl";

    public const string C_DurationSeconds = "DurationSeconds";
    public const string P_DurationSeconds = "@DurationSeconds";

    public const string C_OriginalFileName = "OriginalFileName";
    public const string P_OriginalFileName = "@OriginalFileName";

    public const string C_FileSize = "FileSize";
    public const string P_FileSize = "@FileSize";

    public const string C_MimeType = "MimeType";
    public const string P_MimeType = "@MimeType";

    public const string C_SourceVideoId = "SourceVideoId";
    public const string P_SourceVideoId = "@SourceVideoId";

    public const string C_CreatedByUserID = "CreatedByUserID";
    public const string P_CreatedByUserID = "@CreatedByUserID";

    public const string C_ShareScope = "ShareScope";
    public const string P_ShareScope = "@ShareScope";

    public const string C_CreatedAt = "CreatedAt";
    public const string P_CreatedAt = "@CreatedAt";

    public const string C_UpdatedAt = "UpdatedAt";
    public const string P_UpdatedAt = "@UpdatedAt";

    public const string C_Status = "Status";
    public const string P_Status = "@Status";

    public const string C_IsDeleted = "IsDeleted";
    public const string P_IsDeleted = "@IsDeleted";

    public const string C_SourceType = "SourceType";
    public const string P_SourceType = "@SourceType";

    /// <summary>
    /// Khóa chính tự tăng của tài nguyên video. (Khóa chính, Tự tăng).
    /// </summary>
    public long VideoAssetID { get; set; }

    /// <summary>
    /// Tên hiển thị của tài nguyên video.
    /// </summary>
    public string? Title { get; set; }

    /// <summary>
    /// Đường dẫn tệp video trong vùng lưu trữ dự án.
    /// </summary>
    public string? VideoUrl { get; set; }

    /// <summary>
    /// Đường dẫn ảnh đại diện của tài nguyên video.
    /// </summary>
    public string? PosterUrl { get; set; }

    /// <summary>
    /// Thời lượng tài nguyên video tính bằng giây.
    /// </summary>
    public int DurationSeconds { get; set; }

    /// <summary>
    /// Tên gốc của tệp khi được tải lên.
    /// </summary>
    public string? OriginalFileName { get; set; }

    /// <summary>
    /// Kích thước tệp video tính bằng byte.
    /// </summary>
    public long? FileSize { get; set; }

    /// <summary>
    /// Kiểu nội dung MIME của tệp video.
    /// </summary>
    public string? MimeType { get; set; }

    /// <summary>
    /// ID video nguồn dùng khi chuyển đổi dữ liệu cũ sang thư viện.
    /// </summary>
    public long? SourceVideoId { get; set; }

    /// <summary>
    /// ID người dùng tải lên hoặc tạo tài nguyên video.
    /// </summary>
    public long CreatedByUserID { get; set; }

    /// <summary>
    /// Phạm vi chia sẻ: riêng tư, một số giáo viên được chọn hoặc toàn trường.
    /// </summary>
    public string? ShareScope { get; set; }

    /// <summary>
    /// Thời điểm tạo tài nguyên video theo UTC.
    /// </summary>
    public DateTime CreatedAt { get; set; }

    /// <summary>
    /// Thời điểm cập nhật tài nguyên video gần nhất theo UTC.
    /// </summary>
    public DateTime? UpdatedAt { get; set; }

    /// <summary>
    /// Trạng thái sử dụng của tài nguyên video.
    /// </summary>
    public string? Status { get; set; }

    /// <summary>
    /// Cờ xóa mềm của tài nguyên video.
    /// </summary>
    public bool IsDeleted { get; set; }

    /// <summary>
    /// Loại nguồn video trong thư viện: LOCAL là file tải lên Media, YOUTUBE là liên kết YouTube.
    /// </summary>
    public string? SourceType { get; set; }
}
