// <auto-generated>
// File được sinh bởi tools/SimsObjectGenerator. Không sửa trực tiếp file này.
// </auto-generated>

#nullable enable

namespace SimsObject;

/// <summary>
/// [SIM] Hồ sơ cá nhân học viên và lớp hành chính đang theo học.
/// </summary>
public partial class SIM_Student
{
    public const string TableSchema = "dbo";
    public const string TableName = "SIM_Student";
    public const string QualifiedTableName = "[dbo].[SIM_Student]";

    public const string C_DataGroupID = "DataGroupID";
    public const string P_DataGroupID = "@DataGroupID";

    public const string C_StudentID = "StudentID";
    public const string P_StudentID = "@StudentID";

    public const string C_UserID = "UserID";
    public const string P_UserID = "@UserID";

    public const string C_ClassID = "ClassID";
    public const string P_ClassID = "@ClassID";

    public const string C_StudentFirstName = "StudentFirstName";
    public const string P_StudentFirstName = "@StudentFirstName";

    public const string C_StudentLastName = "StudentLastName";
    public const string P_StudentLastName = "@StudentLastName";

    public const string C_FullName = "FullName";
    public const string P_FullName = "@FullName";

    public const string C_Gender = "Gender";
    public const string P_Gender = "@Gender";

    public const string C_BirthDate = "BirthDate";
    public const string P_BirthDate = "@BirthDate";

    public const string C_Email = "Email";
    public const string P_Email = "@Email";

    public const string C_Mobile = "Mobile";
    public const string P_Mobile = "@Mobile";

    public const string C_Address = "Address";
    public const string P_Address = "@Address";

    public const string C_IsActived = "IsActived";
    public const string P_IsActived = "@IsActived";

    public const string C_CreatedDate = "CreatedDate";
    public const string P_CreatedDate = "@CreatedDate";

    public const string C_UpdatedDate = "UpdatedDate";
    public const string P_UpdatedDate = "@UpdatedDate";

    /// <summary>
    /// Cột DataGroupID của bảng SIM_Student, lưu thông tin phục vụ nghiệp vụ được mô tả ở cấp bảng. (Khóa chính).
    /// </summary>
    public int DataGroupID { get; set; }

    /// <summary>
    /// Cột StudentID của bảng SIM_Student, lưu thông tin phục vụ nghiệp vụ được mô tả ở cấp bảng. (Khóa chính).
    /// </summary>
    public string? StudentID { get; set; }

    /// <summary>
    /// Cột UserID của bảng SIM_Student, lưu thông tin phục vụ nghiệp vụ được mô tả ở cấp bảng.
    /// </summary>
    public long? UserID { get; set; }

    /// <summary>
    /// Cột ClassID của bảng SIM_Student, lưu thông tin phục vụ nghiệp vụ được mô tả ở cấp bảng.
    /// </summary>
    public string? ClassID { get; set; }

    /// <summary>
    /// Cột StudentFirstName của bảng SIM_Student, lưu thông tin phục vụ nghiệp vụ được mô tả ở cấp bảng.
    /// </summary>
    public string? StudentFirstName { get; set; }

    /// <summary>
    /// Cột StudentLastName của bảng SIM_Student, lưu thông tin phục vụ nghiệp vụ được mô tả ở cấp bảng.
    /// </summary>
    public string? StudentLastName { get; set; }

    /// <summary>
    /// Cột FullName của bảng SIM_Student, lưu thông tin phục vụ nghiệp vụ được mô tả ở cấp bảng.
    /// </summary>
    public string? FullName { get; set; }

    /// <summary>
    /// Cột Gender của bảng SIM_Student, lưu thông tin phục vụ nghiệp vụ được mô tả ở cấp bảng.
    /// </summary>
    public bool? Gender { get; set; }

    /// <summary>
    /// Cột BirthDate của bảng SIM_Student, lưu thông tin phục vụ nghiệp vụ được mô tả ở cấp bảng.
    /// </summary>
    public DateTime? BirthDate { get; set; }

    /// <summary>
    /// Cột Email của bảng SIM_Student, lưu thông tin phục vụ nghiệp vụ được mô tả ở cấp bảng.
    /// </summary>
    public string? Email { get; set; }

    /// <summary>
    /// Cột Mobile của bảng SIM_Student, lưu thông tin phục vụ nghiệp vụ được mô tả ở cấp bảng.
    /// </summary>
    public string? Mobile { get; set; }

    /// <summary>
    /// Cột Address của bảng SIM_Student, lưu thông tin phục vụ nghiệp vụ được mô tả ở cấp bảng.
    /// </summary>
    public string? Address { get; set; }

    /// <summary>
    /// Cột IsActived của bảng SIM_Student, lưu thông tin phục vụ nghiệp vụ được mô tả ở cấp bảng.
    /// </summary>
    public bool IsActived { get; set; }

    /// <summary>
    /// Cột CreatedDate của bảng SIM_Student, lưu thông tin phục vụ nghiệp vụ được mô tả ở cấp bảng.
    /// </summary>
    public DateTime CreatedDate { get; set; }

    /// <summary>
    /// Cột UpdatedDate của bảng SIM_Student, lưu thông tin phục vụ nghiệp vụ được mô tả ở cấp bảng.
    /// </summary>
    public DateTime? UpdatedDate { get; set; }
}
