// <auto-generated>
// File được sinh bởi tools/SimsObjectGenerator. Không sửa trực tiếp file này.
// </auto-generated>

#nullable enable

namespace SimsObject;

/// <summary>
/// [SIM] Danh mục khoa chuyên môn, ví dụ Khoa Công nghệ thông tin.
/// </summary>
public partial class SIM_Science
{
    public const string TableSchema = "dbo";
    public const string TableName = "SIM_Science";
    public const string QualifiedTableName = "[dbo].[SIM_Science]";

    public const string C_DataGroupID = "DataGroupID";
    public const string P_DataGroupID = "@DataGroupID";

    public const string C_ScienceID = "ScienceID";
    public const string P_ScienceID = "@ScienceID";

    public const string C_ScienceName = "ScienceName";
    public const string P_ScienceName = "@ScienceName";

    public const string C_ScienceShortName = "ScienceShortName";
    public const string P_ScienceShortName = "@ScienceShortName";

    public const string C_IsActived = "IsActived";
    public const string P_IsActived = "@IsActived";

    /// <summary>
    /// Cột DataGroupID của bảng SIM_Science, lưu thông tin phục vụ nghiệp vụ được mô tả ở cấp bảng. (Khóa chính).
    /// </summary>
    public int DataGroupID { get; set; }

    /// <summary>
    /// Cột ScienceID của bảng SIM_Science, lưu thông tin phục vụ nghiệp vụ được mô tả ở cấp bảng. (Khóa chính).
    /// </summary>
    public string? ScienceID { get; set; }

    /// <summary>
    /// Cột ScienceName của bảng SIM_Science, lưu thông tin phục vụ nghiệp vụ được mô tả ở cấp bảng.
    /// </summary>
    public string? ScienceName { get; set; }

    /// <summary>
    /// Cột ScienceShortName của bảng SIM_Science, lưu thông tin phục vụ nghiệp vụ được mô tả ở cấp bảng.
    /// </summary>
    public string? ScienceShortName { get; set; }

    /// <summary>
    /// Cột IsActived của bảng SIM_Science, lưu thông tin phục vụ nghiệp vụ được mô tả ở cấp bảng.
    /// </summary>
    public bool IsActived { get; set; }
}
