// <auto-generated>
// File được sinh bởi tools/SimsObjectGenerator. Không sửa trực tiếp file này.
// </auto-generated>

#nullable enable

namespace SimsObject;

/// <summary>
/// [SIM] Hồ sơ nghiệp vụ giảng viên gắn với tài khoản SYS_Users.
/// </summary>
public partial class SIM_Teacher
{
    public const string TableSchema = "dbo";
    public const string TableName = "SIM_Teacher";
    public const string QualifiedTableName = "[dbo].[SIM_Teacher]";

    public const string C_DataGroupID = "DataGroupID";
    public const string P_DataGroupID = "@DataGroupID";

    public const string C_TeacherID = "TeacherID";
    public const string P_TeacherID = "@TeacherID";

    public const string C_UserID = "UserID";
    public const string P_UserID = "@UserID";

    public const string C_TeacherFirstName = "TeacherFirstName";
    public const string P_TeacherFirstName = "@TeacherFirstName";

    public const string C_TeacherLastName = "TeacherLastName";
    public const string P_TeacherLastName = "@TeacherLastName";

    public const string C_TeacherShortName = "TeacherShortName";
    public const string P_TeacherShortName = "@TeacherShortName";

    public const string C_ScienceID = "ScienceID";
    public const string P_ScienceID = "@ScienceID";

    public const string C_SubjectGroupID = "SubjectGroupID";
    public const string P_SubjectGroupID = "@SubjectGroupID";

    public const string C_Email = "Email";
    public const string P_Email = "@Email";

    public const string C_IsActived = "IsActived";
    public const string P_IsActived = "@IsActived";

    /// <summary>
    /// Cột DataGroupID của bảng SIM_Teacher, lưu thông tin phục vụ nghiệp vụ được mô tả ở cấp bảng. (Khóa chính).
    /// </summary>
    public int DataGroupID { get; set; }

    /// <summary>
    /// Cột TeacherID của bảng SIM_Teacher, lưu thông tin phục vụ nghiệp vụ được mô tả ở cấp bảng. (Khóa chính).
    /// </summary>
    public string? TeacherID { get; set; }

    /// <summary>
    /// Cột UserID của bảng SIM_Teacher, lưu thông tin phục vụ nghiệp vụ được mô tả ở cấp bảng.
    /// </summary>
    public long? UserID { get; set; }

    /// <summary>
    /// Cột TeacherFirstName của bảng SIM_Teacher, lưu thông tin phục vụ nghiệp vụ được mô tả ở cấp bảng.
    /// </summary>
    public string? TeacherFirstName { get; set; }

    /// <summary>
    /// Cột TeacherLastName của bảng SIM_Teacher, lưu thông tin phục vụ nghiệp vụ được mô tả ở cấp bảng.
    /// </summary>
    public string? TeacherLastName { get; set; }

    /// <summary>
    /// Cột TeacherShortName của bảng SIM_Teacher, lưu thông tin phục vụ nghiệp vụ được mô tả ở cấp bảng.
    /// </summary>
    public string? TeacherShortName { get; set; }

    /// <summary>
    /// Cột ScienceID của bảng SIM_Teacher, lưu thông tin phục vụ nghiệp vụ được mô tả ở cấp bảng.
    /// </summary>
    public string? ScienceID { get; set; }

    /// <summary>
    /// Cột SubjectGroupID của bảng SIM_Teacher, lưu thông tin phục vụ nghiệp vụ được mô tả ở cấp bảng.
    /// </summary>
    public string? SubjectGroupID { get; set; }

    /// <summary>
    /// Cột Email của bảng SIM_Teacher, lưu thông tin phục vụ nghiệp vụ được mô tả ở cấp bảng.
    /// </summary>
    public string? Email { get; set; }

    /// <summary>
    /// Cột IsActived của bảng SIM_Teacher, lưu thông tin phục vụ nghiệp vụ được mô tả ở cấp bảng.
    /// </summary>
    public bool IsActived { get; set; }
}
