// <auto-generated>
// File được sinh bởi tools/SimsObjectGenerator. Không sửa trực tiếp file này.
// </auto-generated>

#nullable enable

namespace SimsObject;

/// <summary>
/// [SIM] Các bài học thuộc chương và khóa học.
/// </summary>
public partial class SIM_Lessons
{
    public const string TableSchema = "dbo";
    public const string TableName = "SIM_Lessons";
    public const string QualifiedTableName = "[dbo].[SIM_Lessons]";

    public const string C_LessonID = "LessonID";
    public const string P_LessonID = "@LessonID";

    public const string C_CourseId = "CourseId";
    public const string P_CourseId = "@CourseId";

    public const string C_ChapterId = "ChapterId";
    public const string P_ChapterId = "@ChapterId";

    public const string C_Title = "Title";
    public const string P_Title = "@Title";

    public const string C_Description = "Description";
    public const string P_Description = "@Description";

    public const string C_LessonType = "LessonType";
    public const string P_LessonType = "@LessonType";

    public const string C_DurationSeconds = "DurationSeconds";
    public const string P_DurationSeconds = "@DurationSeconds";

    public const string C_SortOrder = "SortOrder";
    public const string P_SortOrder = "@SortOrder";

    public const string C_IsRequired = "IsRequired";
    public const string P_IsRequired = "@IsRequired";

    public const string C_PassingScore = "PassingScore";
    public const string P_PassingScore = "@PassingScore";

    public const string C_Status = "Status";
    public const string P_Status = "@Status";

    public const string C_CreatedAt = "CreatedAt";
    public const string P_CreatedAt = "@CreatedAt";

    public const string C_UpdatedAt = "UpdatedAt";
    public const string P_UpdatedAt = "@UpdatedAt";

    public const string C_IsDeleted = "IsDeleted";
    public const string P_IsDeleted = "@IsDeleted";

    public const string C_VideoID = "VideoID";
    public const string P_VideoID = "@VideoID";

    public const string C_VideoVersionID = "VideoVersionID";
    public const string P_VideoVersionID = "@VideoVersionID";

    public const string C_ContentHtml = "ContentHtml";
    public const string P_ContentHtml = "@ContentHtml";

    public const string C_DocumentUrl = "DocumentUrl";
    public const string P_DocumentUrl = "@DocumentUrl";

    public const string C_AssignmentFolderName = "AssignmentFolderName";
    public const string P_AssignmentFolderName = "@AssignmentFolderName";

    public const string C_DueAt = "DueAt";
    public const string P_DueAt = "@DueAt";

    public const string C_MaxSubmissionFileSizeMB = "MaxSubmissionFileSizeMB";
    public const string P_MaxSubmissionFileSizeMB = "@MaxSubmissionFileSizeMB";

    public const string C_AllowLateSubmission = "AllowLateSubmission";
    public const string P_AllowLateSubmission = "@AllowLateSubmission";

    public const string C_AssignmentStartAt = "AssignmentStartAt";
    public const string P_AssignmentStartAt = "@AssignmentStartAt";

    public const string C_AssignmentMaxScore = "AssignmentMaxScore";
    public const string P_AssignmentMaxScore = "@AssignmentMaxScore";

    public const string C_MaxSubmissionAttempts = "MaxSubmissionAttempts";
    public const string P_MaxSubmissionAttempts = "@MaxSubmissionAttempts";

    /// <summary>
    /// Khóa chính tự tăng của bài học. (Khóa chính, Tự tăng).
    /// </summary>
    public long LessonID { get; set; }

    /// <summary>
    /// ID khóa học chứa bài học.
    /// </summary>
    public long CourseId { get; set; }

    /// <summary>
    /// ID chương chứa bài học.
    /// </summary>
    public long ChapterId { get; set; }

    /// <summary>
    /// Tên hiển thị của bài học.
    /// </summary>
    public string? Title { get; set; }

    /// <summary>
    /// Mô tả nội dung của bài học.
    /// </summary>
    public string? Description { get; set; }

    /// <summary>
    /// Loại bài học: VIDEO, INTERACTIVE_VIDEO, QUIZ hoặc DOCUMENT.
    /// </summary>
    public string? LessonType { get; set; }

    /// <summary>
    /// Thời lượng dự kiến của bài học tính bằng giây.
    /// </summary>
    public int DurationSeconds { get; set; }

    /// <summary>
    /// Thứ tự hiển thị của bài học trong chương.
    /// </summary>
    public int SortOrder { get; set; }

    /// <summary>
    /// Cờ cho biết bài học có bắt buộc hoàn thành hay không.
    /// </summary>
    public bool IsRequired { get; set; }

    /// <summary>
    /// Điểm tối thiểu để đạt bài học; rỗng nếu không áp dụng.
    /// </summary>
    public decimal? PassingScore { get; set; }

    /// <summary>
    /// Trạng thái sử dụng của bài học.
    /// </summary>
    public string? Status { get; set; }

    /// <summary>
    /// Thời điểm tạo bài học theo UTC.
    /// </summary>
    public DateTime CreatedAt { get; set; }

    /// <summary>
    /// Thời điểm cập nhật bài học gần nhất theo UTC.
    /// </summary>
    public DateTime? UpdatedAt { get; set; }

    /// <summary>
    /// Cờ xóa mềm của bài học.
    /// </summary>
    public bool IsDeleted { get; set; }

    /// <summary>
    /// ID video tương tác độc lập được bài học tham chiếu; nhiều bài học có thể dùng chung một video.
    /// </summary>
    public long? VideoID { get; set; }

    /// <summary>
    /// ID phiên bản video được bài học ghim; thay phiên bản khác không ảnh hưởng bài học này.
    /// </summary>
    public long? VideoVersionID { get; set; }

    /// <summary>
    /// Nội dung bài học được giảng viên soạn bằng trình biên tập.
    /// </summary>
    public string? ContentHtml { get; set; }

    /// <summary>
    /// Đường dẫn tài liệu chính của bài học trong /Media/File/.
    /// </summary>
    public string? DocumentUrl { get; set; }

    /// <summary>
    /// Tên thư mục bài tập dùng tổ chức file nộp của học viên.
    /// </summary>
    public string? AssignmentFolderName { get; set; }

    /// <summary>
    /// Hạn cuối nộp bài tập.
    /// </summary>
    public DateTime? DueAt { get; set; }

    /// <summary>
    /// Dung lượng tối đa tính bằng MB cho mỗi file bài nộp.
    /// </summary>
    public int MaxSubmissionFileSizeMB { get; set; }

    /// <summary>
    /// Cho phép học viên nộp bài sau hạn hay không.
    /// </summary>
    public bool AllowLateSubmission { get; set; }

    /// <summary>
    /// Thời điểm học viên bắt đầu được nộp bài tập.
    /// </summary>
    public DateTime? AssignmentStartAt { get; set; }

    /// <summary>
    /// Điểm tối đa giáo viên có thể chấm cho bài tập.
    /// </summary>
    public decimal AssignmentMaxScore { get; set; }

    /// <summary>
    /// Số lần nộp tối đa được phép cho bài tập.
    /// </summary>
    public int MaxSubmissionAttempts { get; set; }
}
