// <auto-generated>
// File được sinh bởi tools/SimsObjectGenerator. Không sửa trực tiếp file này.
// </auto-generated>

#nullable enable

namespace SimsObject;

/// <summary>
/// [SIM] Danh mục khóa tuyển sinh, ví dụ K18; không phải không gian học trực tuyến.
/// </summary>
public partial class SIM_Course
{
    public const string TableSchema = "dbo";
    public const string TableName = "SIM_Course";
    public const string QualifiedTableName = "[dbo].[SIM_Course]";

    public const string C_DataGroupID = "DataGroupID";
    public const string P_DataGroupID = "@DataGroupID";

    public const string C_CourseID = "CourseID";
    public const string P_CourseID = "@CourseID";

    public const string C_CourseName = "CourseName";
    public const string P_CourseName = "@CourseName";

    public const string C_StartYear = "StartYear";
    public const string P_StartYear = "@StartYear";

    public const string C_FinishYear = "FinishYear";
    public const string P_FinishYear = "@FinishYear";

    public const string C_IsActived = "IsActived";
    public const string P_IsActived = "@IsActived";

    /// <summary>
    /// Cột DataGroupID của bảng SIM_Course, lưu thông tin phục vụ nghiệp vụ được mô tả ở cấp bảng. (Khóa chính).
    /// </summary>
    public int DataGroupID { get; set; }

    /// <summary>
    /// Cột CourseID của bảng SIM_Course, lưu thông tin phục vụ nghiệp vụ được mô tả ở cấp bảng. (Khóa chính).
    /// </summary>
    public string? CourseID { get; set; }

    /// <summary>
    /// Cột CourseName của bảng SIM_Course, lưu thông tin phục vụ nghiệp vụ được mô tả ở cấp bảng.
    /// </summary>
    public string? CourseName { get; set; }

    /// <summary>
    /// Cột StartYear của bảng SIM_Course, lưu thông tin phục vụ nghiệp vụ được mô tả ở cấp bảng.
    /// </summary>
    public int StartYear { get; set; }

    /// <summary>
    /// Cột FinishYear của bảng SIM_Course, lưu thông tin phục vụ nghiệp vụ được mô tả ở cấp bảng.
    /// </summary>
    public int FinishYear { get; set; }

    /// <summary>
    /// Cột IsActived của bảng SIM_Course, lưu thông tin phục vụ nghiệp vụ được mô tả ở cấp bảng.
    /// </summary>
    public bool IsActived { get; set; }
}
