// <auto-generated>
// File được sinh bởi tools/SimsObjectGenerator. Không sửa trực tiếp file này.
// </auto-generated>

#nullable enable

namespace SimsObject;

/// <summary>
/// [SIM] Môn học được mở cho một lớp trong năm học và học kỳ cụ thể.
/// </summary>
public partial class SIM_Class_Subject
{
    public const string TableSchema = "dbo";
    public const string TableName = "SIM_Class_Subject";
    public const string QualifiedTableName = "[dbo].[SIM_Class_Subject]";

    public const string C_DataGroupID = "DataGroupID";
    public const string P_DataGroupID = "@DataGroupID";

    public const string C_ClassSubjectID = "ClassSubjectID";
    public const string P_ClassSubjectID = "@ClassSubjectID";

    public const string C_Semester = "Semester";
    public const string P_Semester = "@Semester";

    public const string C_YearID = "YearID";
    public const string P_YearID = "@YearID";

    public const string C_ClassID = "ClassID";
    public const string P_ClassID = "@ClassID";

    public const string C_SubjectID = "SubjectID";
    public const string P_SubjectID = "@SubjectID";

    public const string C_TeacherID = "TeacherID";
    public const string P_TeacherID = "@TeacherID";

    public const string C_TheoryQuantity = "TheoryQuantity";
    public const string P_TheoryQuantity = "@TheoryQuantity";

    public const string C_PracticeQuantity = "PracticeQuantity";
    public const string P_PracticeQuantity = "@PracticeQuantity";

    public const string C_TestQuantity = "TestQuantity";
    public const string P_TestQuantity = "@TestQuantity";

    public const string C_CreditCount = "CreditCount";
    public const string P_CreditCount = "@CreditCount";

    public const string C_ClassSubjectStatus = "ClassSubjectStatus";
    public const string P_ClassSubjectStatus = "@ClassSubjectStatus";

    public const string C_OrderIndex = "OrderIndex";
    public const string P_OrderIndex = "@OrderIndex";

    public const string C_IsLocked = "IsLocked";
    public const string P_IsLocked = "@IsLocked";

    public const string C_CreatedDate = "CreatedDate";
    public const string P_CreatedDate = "@CreatedDate";

    public const string C_CreatedUser = "CreatedUser";
    public const string P_CreatedUser = "@CreatedUser";

    public const string C_UpdatedDate = "UpdatedDate";
    public const string P_UpdatedDate = "@UpdatedDate";

    public const string C_UpdatedUser = "UpdatedUser";
    public const string P_UpdatedUser = "@UpdatedUser";

    public const string C_MeetingLink = "MeetingLink";
    public const string P_MeetingLink = "@MeetingLink";

    public const string C_MeetingCode = "MeetingCode";
    public const string P_MeetingCode = "@MeetingCode";

    /// <summary>
    /// Cột DataGroupID của bảng SIM_Class_Subject, lưu thông tin phục vụ nghiệp vụ được mô tả ở cấp bảng. (Khóa chính).
    /// </summary>
    public int DataGroupID { get; set; }

    /// <summary>
    /// Cột ClassSubjectID của bảng SIM_Class_Subject, lưu thông tin phục vụ nghiệp vụ được mô tả ở cấp bảng. (Khóa chính).
    /// </summary>
    public long ClassSubjectID { get; set; }

    /// <summary>
    /// Cột Semester của bảng SIM_Class_Subject, lưu thông tin phục vụ nghiệp vụ được mô tả ở cấp bảng.
    /// </summary>
    public byte Semester { get; set; }

    /// <summary>
    /// Cột YearID của bảng SIM_Class_Subject, lưu thông tin phục vụ nghiệp vụ được mô tả ở cấp bảng.
    /// </summary>
    public int YearID { get; set; }

    /// <summary>
    /// Cột ClassID của bảng SIM_Class_Subject, lưu thông tin phục vụ nghiệp vụ được mô tả ở cấp bảng.
    /// </summary>
    public string? ClassID { get; set; }

    /// <summary>
    /// Cột SubjectID của bảng SIM_Class_Subject, lưu thông tin phục vụ nghiệp vụ được mô tả ở cấp bảng.
    /// </summary>
    public string? SubjectID { get; set; }

    /// <summary>
    /// Cột TeacherID của bảng SIM_Class_Subject, lưu thông tin phục vụ nghiệp vụ được mô tả ở cấp bảng.
    /// </summary>
    public string? TeacherID { get; set; }

    /// <summary>
    /// Cột TheoryQuantity của bảng SIM_Class_Subject, lưu thông tin phục vụ nghiệp vụ được mô tả ở cấp bảng.
    /// </summary>
    public int TheoryQuantity { get; set; }

    /// <summary>
    /// Cột PracticeQuantity của bảng SIM_Class_Subject, lưu thông tin phục vụ nghiệp vụ được mô tả ở cấp bảng.
    /// </summary>
    public int PracticeQuantity { get; set; }

    /// <summary>
    /// Cột TestQuantity của bảng SIM_Class_Subject, lưu thông tin phục vụ nghiệp vụ được mô tả ở cấp bảng.
    /// </summary>
    public int TestQuantity { get; set; }

    /// <summary>
    /// Cột CreditCount của bảng SIM_Class_Subject, lưu thông tin phục vụ nghiệp vụ được mô tả ở cấp bảng.
    /// </summary>
    public byte CreditCount { get; set; }

    /// <summary>
    /// Cột ClassSubjectStatus của bảng SIM_Class_Subject, lưu thông tin phục vụ nghiệp vụ được mô tả ở cấp bảng.
    /// </summary>
    public byte ClassSubjectStatus { get; set; }

    /// <summary>
    /// Cột OrderIndex của bảng SIM_Class_Subject, lưu thông tin phục vụ nghiệp vụ được mô tả ở cấp bảng.
    /// </summary>
    public long OrderIndex { get; set; }

    /// <summary>
    /// Cột IsLocked của bảng SIM_Class_Subject, lưu thông tin phục vụ nghiệp vụ được mô tả ở cấp bảng.
    /// </summary>
    public bool IsLocked { get; set; }

    /// <summary>
    /// Cột CreatedDate của bảng SIM_Class_Subject, lưu thông tin phục vụ nghiệp vụ được mô tả ở cấp bảng.
    /// </summary>
    public DateTime CreatedDate { get; set; }

    /// <summary>
    /// Cột CreatedUser của bảng SIM_Class_Subject, lưu thông tin phục vụ nghiệp vụ được mô tả ở cấp bảng.
    /// </summary>
    public string? CreatedUser { get; set; }

    /// <summary>
    /// Cột UpdatedDate của bảng SIM_Class_Subject, lưu thông tin phục vụ nghiệp vụ được mô tả ở cấp bảng.
    /// </summary>
    public DateTime? UpdatedDate { get; set; }

    /// <summary>
    /// Cột UpdatedUser của bảng SIM_Class_Subject, lưu thông tin phục vụ nghiệp vụ được mô tả ở cấp bảng.
    /// </summary>
    public string? UpdatedUser { get; set; }

    /// <summary>
    /// Cột MeetingLink của bảng SIM_Class_Subject, lưu thông tin phục vụ nghiệp vụ được mô tả ở cấp bảng.
    /// </summary>
    public string? MeetingLink { get; set; }

    /// <summary>
    /// Cột MeetingCode của bảng SIM_Class_Subject, lưu thông tin phục vụ nghiệp vụ được mô tả ở cấp bảng.
    /// </summary>
    public string? MeetingCode { get; set; }
}
