// <auto-generated>
// File được sinh bởi tools/SimsObjectGenerator. Không sửa trực tiếp file này.
// </auto-generated>

#nullable enable

namespace SimsObject;

/// <summary>
/// [SIM] Các file, tài liệu hoặc liên kết đính kèm cho bài học.
/// </summary>
public partial class SIM_LessonResources
{
    public const string TableSchema = "dbo";
    public const string TableName = "SIM_LessonResources";
    public const string QualifiedTableName = "[dbo].[SIM_LessonResources]";

    public const string C_LessonResourceID = "LessonResourceID";
    public const string P_LessonResourceID = "@LessonResourceID";

    public const string C_LessonID = "LessonID";
    public const string P_LessonID = "@LessonID";

    public const string C_ResourceType = "ResourceType";
    public const string P_ResourceType = "@ResourceType";

    public const string C_ResourceName = "ResourceName";
    public const string P_ResourceName = "@ResourceName";

    public const string C_ResourceUrl = "ResourceUrl";
    public const string P_ResourceUrl = "@ResourceUrl";

    public const string C_OriginalFileName = "OriginalFileName";
    public const string P_OriginalFileName = "@OriginalFileName";

    public const string C_FileSize = "FileSize";
    public const string P_FileSize = "@FileSize";

    public const string C_MimeType = "MimeType";
    public const string P_MimeType = "@MimeType";

    public const string C_SortOrder = "SortOrder";
    public const string P_SortOrder = "@SortOrder";

    public const string C_CreatedByUserID = "CreatedByUserID";
    public const string P_CreatedByUserID = "@CreatedByUserID";

    public const string C_CreatedAt = "CreatedAt";
    public const string P_CreatedAt = "@CreatedAt";

    public const string C_IsDeleted = "IsDeleted";
    public const string P_IsDeleted = "@IsDeleted";

    /// <summary>
    /// Cột LessonResourceID của bảng SIM_LessonResources, lưu thông tin phục vụ nghiệp vụ được mô tả ở cấp bảng. (Khóa chính, Tự tăng).
    /// </summary>
    public long LessonResourceID { get; set; }

    /// <summary>
    /// Cột LessonID của bảng SIM_LessonResources, lưu thông tin phục vụ nghiệp vụ được mô tả ở cấp bảng.
    /// </summary>
    public long LessonID { get; set; }

    /// <summary>
    /// Cột ResourceType của bảng SIM_LessonResources, lưu thông tin phục vụ nghiệp vụ được mô tả ở cấp bảng.
    /// </summary>
    public string? ResourceType { get; set; }

    /// <summary>
    /// Cột ResourceName của bảng SIM_LessonResources, lưu thông tin phục vụ nghiệp vụ được mô tả ở cấp bảng.
    /// </summary>
    public string? ResourceName { get; set; }

    /// <summary>
    /// Cột ResourceUrl của bảng SIM_LessonResources, lưu thông tin phục vụ nghiệp vụ được mô tả ở cấp bảng.
    /// </summary>
    public string? ResourceUrl { get; set; }

    /// <summary>
    /// Cột OriginalFileName của bảng SIM_LessonResources, lưu thông tin phục vụ nghiệp vụ được mô tả ở cấp bảng.
    /// </summary>
    public string? OriginalFileName { get; set; }

    /// <summary>
    /// Cột FileSize của bảng SIM_LessonResources, lưu thông tin phục vụ nghiệp vụ được mô tả ở cấp bảng.
    /// </summary>
    public long? FileSize { get; set; }

    /// <summary>
    /// Cột MimeType của bảng SIM_LessonResources, lưu thông tin phục vụ nghiệp vụ được mô tả ở cấp bảng.
    /// </summary>
    public string? MimeType { get; set; }

    /// <summary>
    /// Cột SortOrder của bảng SIM_LessonResources, lưu thông tin phục vụ nghiệp vụ được mô tả ở cấp bảng.
    /// </summary>
    public int SortOrder { get; set; }

    /// <summary>
    /// Cột CreatedByUserID của bảng SIM_LessonResources, lưu thông tin phục vụ nghiệp vụ được mô tả ở cấp bảng.
    /// </summary>
    public long CreatedByUserID { get; set; }

    /// <summary>
    /// Cột CreatedAt của bảng SIM_LessonResources, lưu thông tin phục vụ nghiệp vụ được mô tả ở cấp bảng.
    /// </summary>
    public DateTime CreatedAt { get; set; }

    /// <summary>
    /// Cột IsDeleted của bảng SIM_LessonResources, lưu thông tin phục vụ nghiệp vụ được mô tả ở cấp bảng.
    /// </summary>
    public bool IsDeleted { get; set; }
}
