// <auto-generated>
// File được sinh bởi tools/SimsObjectGenerator. Không sửa trực tiếp file này.
// </auto-generated>

#nullable enable

namespace SimsObject;

/// <summary>
/// [SIM] Các chương nội dung thuộc khóa học.
/// </summary>
public partial class SIM_Chapters
{
    public const string TableSchema = "dbo";
    public const string TableName = "SIM_Chapters";
    public const string QualifiedTableName = "[dbo].[SIM_Chapters]";

    public const string C_ChapterID = "ChapterID";
    public const string P_ChapterID = "@ChapterID";

    public const string C_CourseId = "CourseId";
    public const string P_CourseId = "@CourseId";

    public const string C_Title = "Title";
    public const string P_Title = "@Title";

    public const string C_Description = "Description";
    public const string P_Description = "@Description";

    public const string C_SortOrder = "SortOrder";
    public const string P_SortOrder = "@SortOrder";

    public const string C_Status = "Status";
    public const string P_Status = "@Status";

    public const string C_CreatedAt = "CreatedAt";
    public const string P_CreatedAt = "@CreatedAt";

    public const string C_UpdatedAt = "UpdatedAt";
    public const string P_UpdatedAt = "@UpdatedAt";

    public const string C_IsDeleted = "IsDeleted";
    public const string P_IsDeleted = "@IsDeleted";

    /// <summary>
    /// Khóa chính tự tăng của chương. (Khóa chính, Tự tăng).
    /// </summary>
    public long ChapterID { get; set; }

    /// <summary>
    /// ID khóa học chứa chương.
    /// </summary>
    public long CourseId { get; set; }

    /// <summary>
    /// Tên hiển thị của chương.
    /// </summary>
    public string? Title { get; set; }

    /// <summary>
    /// Mô tả nội dung của chương.
    /// </summary>
    public string? Description { get; set; }

    /// <summary>
    /// Thứ tự hiển thị của chương trong khóa học.
    /// </summary>
    public int SortOrder { get; set; }

    /// <summary>
    /// Trạng thái sử dụng của chương.
    /// </summary>
    public string? Status { get; set; }

    /// <summary>
    /// Thời điểm tạo chương theo UTC.
    /// </summary>
    public DateTime CreatedAt { get; set; }

    /// <summary>
    /// Thời điểm cập nhật chương gần nhất theo UTC.
    /// </summary>
    public DateTime? UpdatedAt { get; set; }

    /// <summary>
    /// Cờ xóa mềm của chương.
    /// </summary>
    public bool IsDeleted { get; set; }
}
