// <auto-generated>
// File được sinh bởi tools/SimsObjectGenerator. Không sửa trực tiếp file này.
// </auto-generated>

#nullable enable

namespace SimsObject;

/// <summary>
/// [SIM] Thông tin tổng quan và trạng thái xuất bản của khóa học.
/// </summary>
public partial class SIM_Courses
{
    public const string TableSchema = "dbo";
    public const string TableName = "SIM_Courses";
    public const string QualifiedTableName = "[dbo].[SIM_Courses]";

    public const string C_CourseID = "CourseID";
    public const string P_CourseID = "@CourseID";

    public const string C_Code = "Code";
    public const string P_Code = "@Code";

    public const string C_Title = "Title";
    public const string P_Title = "@Title";

    public const string C_Slug = "Slug";
    public const string P_Slug = "@Slug";

    public const string C_ThumbnailUrl = "ThumbnailUrl";
    public const string P_ThumbnailUrl = "@ThumbnailUrl";

    public const string C_ShortDescription = "ShortDescription";
    public const string P_ShortDescription = "@ShortDescription";

    public const string C_Description = "Description";
    public const string P_Description = "@Description";

    public const string C_TeacherUserID = "TeacherUserID";
    public const string P_TeacherUserID = "@TeacherUserID";

    public const string C_CourseCategoryID = "CourseCategoryID";
    public const string P_CourseCategoryID = "@CourseCategoryID";

    public const string C_Level = "Level";
    public const string P_Level = "@Level";

    public const string C_PassingScore = "PassingScore";
    public const string P_PassingScore = "@PassingScore";

    public const string C_Status = "Status";
    public const string P_Status = "@Status";

    public const string C_PublishedAt = "PublishedAt";
    public const string P_PublishedAt = "@PublishedAt";

    public const string C_CreatedAt = "CreatedAt";
    public const string P_CreatedAt = "@CreatedAt";

    public const string C_UpdatedAt = "UpdatedAt";
    public const string P_UpdatedAt = "@UpdatedAt";

    public const string C_CreatedByUserID = "CreatedByUserID";
    public const string P_CreatedByUserID = "@CreatedByUserID";

    public const string C_UpdatedByUserID = "UpdatedByUserID";
    public const string P_UpdatedByUserID = "@UpdatedByUserID";

    public const string C_IsDeleted = "IsDeleted";
    public const string P_IsDeleted = "@IsDeleted";

    public const string C_DataGroupID = "DataGroupID";
    public const string P_DataGroupID = "@DataGroupID";

    public const string C_ClassSubjectID = "ClassSubjectID";
    public const string P_ClassSubjectID = "@ClassSubjectID";

    /// <summary>
    /// Khóa chính tự tăng của khóa học. (Khóa chính, Tự tăng).
    /// </summary>
    public long CourseID { get; set; }

    /// <summary>
    /// Mã nghiệp vụ duy nhất của khóa học.
    /// </summary>
    public string? Code { get; set; }

    /// <summary>
    /// Tên hiển thị của khóa học.
    /// </summary>
    public string? Title { get; set; }

    /// <summary>
    /// Chuỗi định danh thân thiện dùng trong đường dẫn URL.
    /// </summary>
    public string? Slug { get; set; }

    /// <summary>
    /// Đường dẫn ảnh đại diện của khóa học.
    /// </summary>
    public string? ThumbnailUrl { get; set; }

    /// <summary>
    /// Mô tả ngắn dùng tại danh sách và thẻ khóa học.
    /// </summary>
    public string? ShortDescription { get; set; }

    /// <summary>
    /// Nội dung giới thiệu chi tiết của khóa học.
    /// </summary>
    public string? Description { get; set; }

    /// <summary>
    /// ID giảng viên phụ trách khóa học.
    /// </summary>
    public long TeacherUserID { get; set; }

    /// <summary>
    /// ID danh mục của khóa học; có thể chưa phân loại.
    /// </summary>
    public long? CourseCategoryID { get; set; }

    /// <summary>
    /// Cấp độ kiến thức của khóa học.
    /// </summary>
    public string? Level { get; set; }

    /// <summary>
    /// Điểm tối thiểu theo thang 100 để đạt khóa học.
    /// </summary>
    public decimal PassingScore { get; set; }

    /// <summary>
    /// Trạng thái khóa học: DRAFT, PUBLISHED hoặc ARCHIVED.
    /// </summary>
    public string? Status { get; set; }

    /// <summary>
    /// Thời điểm khóa học được xuất bản theo UTC.
    /// </summary>
    public DateTime? PublishedAt { get; set; }

    /// <summary>
    /// Thời điểm tạo khóa học theo UTC.
    /// </summary>
    public DateTime CreatedAt { get; set; }

    /// <summary>
    /// Thời điểm cập nhật khóa học gần nhất theo UTC.
    /// </summary>
    public DateTime? UpdatedAt { get; set; }

    /// <summary>
    /// ID người dùng tạo khóa học.
    /// </summary>
    public long CreatedByUserID { get; set; }

    /// <summary>
    /// ID người dùng cập nhật khóa học gần nhất.
    /// </summary>
    public long? UpdatedByUserID { get; set; }

    /// <summary>
    /// Cờ xóa mềm của khóa học.
    /// </summary>
    public bool IsDeleted { get; set; }

    /// <summary>
    /// Mã đơn vị sở hữu không gian học trực tuyến.
    /// </summary>
    public int DataGroupID { get; set; }

    /// <summary>
    /// Mã môn học lớp được liên kết với không gian học trực tuyến này.
    /// </summary>
    public long? ClassSubjectID { get; set; }
}
