// <auto-generated>
// File được sinh bởi tools/SimsObjectGenerator. Không sửa trực tiếp file này.
// </auto-generated>

#nullable enable

namespace SimsObject;

/// <summary>
/// [SIM] Danh mục năm học dùng để mở môn học lớp theo từng học kỳ.
/// </summary>
public partial class SIM_Year
{
    public const string TableSchema = "dbo";
    public const string TableName = "SIM_Year";
    public const string QualifiedTableName = "[dbo].[SIM_Year]";

    public const string C_DataGroupID = "DataGroupID";
    public const string P_DataGroupID = "@DataGroupID";

    public const string C_YearID = "YearID";
    public const string P_YearID = "@YearID";

    public const string C_YearName = "YearName";
    public const string P_YearName = "@YearName";

    public const string C_StartAt = "StartAt";
    public const string P_StartAt = "@StartAt";

    public const string C_FinishAt = "FinishAt";
    public const string P_FinishAt = "@FinishAt";

    public const string C_IsActived = "IsActived";
    public const string P_IsActived = "@IsActived";

    /// <summary>
    /// Mã đơn vị hoặc nhóm dữ liệu sở hữu năm học. (Khóa chính).
    /// </summary>
    public int DataGroupID { get; set; }

    /// <summary>
    /// Mã năm học, ví dụ 2025 cho năm học 2025-2026. (Khóa chính).
    /// </summary>
    public int YearID { get; set; }

    /// <summary>
    /// Tên hiển thị của năm học, ví dụ 2025-2026.
    /// </summary>
    public string? YearName { get; set; }

    /// <summary>
    /// Ngày bắt đầu năm học.
    /// </summary>
    public DateTime? StartAt { get; set; }

    /// <summary>
    /// Ngày kết thúc năm học.
    /// </summary>
    public DateTime? FinishAt { get; set; }

    /// <summary>
    /// Cho biết năm học còn được sử dụng hay không.
    /// </summary>
    public bool IsActived { get; set; }
}
