// <auto-generated>
// File được sinh bởi tools/SimsObjectGenerator. Không sửa trực tiếp file này.
// </auto-generated>

#nullable enable

namespace SimsObject;

/// <summary>
/// [SIM] Danh mục môn học thuộc chương trình đào tạo.
/// </summary>
public partial class SIM_Subject
{
    public const string TableSchema = "dbo";
    public const string TableName = "SIM_Subject";
    public const string QualifiedTableName = "[dbo].[SIM_Subject]";

    public const string C_DataGroupID = "DataGroupID";
    public const string P_DataGroupID = "@DataGroupID";

    public const string C_SubjectID = "SubjectID";
    public const string P_SubjectID = "@SubjectID";

    public const string C_SubjectName = "SubjectName";
    public const string P_SubjectName = "@SubjectName";

    public const string C_SubjectShortName = "SubjectShortName";
    public const string P_SubjectShortName = "@SubjectShortName";

    public const string C_ScienceID = "ScienceID";
    public const string P_ScienceID = "@ScienceID";

    public const string C_SubjectGroupID = "SubjectGroupID";
    public const string P_SubjectGroupID = "@SubjectGroupID";

    public const string C_TheoryQuantity = "TheoryQuantity";
    public const string P_TheoryQuantity = "@TheoryQuantity";

    public const string C_PracticeQuantity = "PracticeQuantity";
    public const string P_PracticeQuantity = "@PracticeQuantity";

    public const string C_TestQuantity = "TestQuantity";
    public const string P_TestQuantity = "@TestQuantity";

    public const string C_CreditCount = "CreditCount";
    public const string P_CreditCount = "@CreditCount";

    public const string C_IsActived = "IsActived";
    public const string P_IsActived = "@IsActived";

    /// <summary>
    /// Cột DataGroupID của bảng SIM_Subject, lưu thông tin phục vụ nghiệp vụ được mô tả ở cấp bảng. (Khóa chính).
    /// </summary>
    public int DataGroupID { get; set; }

    /// <summary>
    /// Cột SubjectID của bảng SIM_Subject, lưu thông tin phục vụ nghiệp vụ được mô tả ở cấp bảng. (Khóa chính).
    /// </summary>
    public string? SubjectID { get; set; }

    /// <summary>
    /// Cột SubjectName của bảng SIM_Subject, lưu thông tin phục vụ nghiệp vụ được mô tả ở cấp bảng.
    /// </summary>
    public string? SubjectName { get; set; }

    /// <summary>
    /// Cột SubjectShortName của bảng SIM_Subject, lưu thông tin phục vụ nghiệp vụ được mô tả ở cấp bảng.
    /// </summary>
    public string? SubjectShortName { get; set; }

    /// <summary>
    /// Cột ScienceID của bảng SIM_Subject, lưu thông tin phục vụ nghiệp vụ được mô tả ở cấp bảng.
    /// </summary>
    public string? ScienceID { get; set; }

    /// <summary>
    /// Cột SubjectGroupID của bảng SIM_Subject, lưu thông tin phục vụ nghiệp vụ được mô tả ở cấp bảng.
    /// </summary>
    public string? SubjectGroupID { get; set; }

    /// <summary>
    /// Cột TheoryQuantity của bảng SIM_Subject, lưu thông tin phục vụ nghiệp vụ được mô tả ở cấp bảng.
    /// </summary>
    public int TheoryQuantity { get; set; }

    /// <summary>
    /// Cột PracticeQuantity của bảng SIM_Subject, lưu thông tin phục vụ nghiệp vụ được mô tả ở cấp bảng.
    /// </summary>
    public int PracticeQuantity { get; set; }

    /// <summary>
    /// Cột TestQuantity của bảng SIM_Subject, lưu thông tin phục vụ nghiệp vụ được mô tả ở cấp bảng.
    /// </summary>
    public int TestQuantity { get; set; }

    /// <summary>
    /// Cột CreditCount của bảng SIM_Subject, lưu thông tin phục vụ nghiệp vụ được mô tả ở cấp bảng.
    /// </summary>
    public byte CreditCount { get; set; }

    /// <summary>
    /// Cột IsActived của bảng SIM_Subject, lưu thông tin phục vụ nghiệp vụ được mô tả ở cấp bảng.
    /// </summary>
    public bool IsActived { get; set; }
}
