// <auto-generated>
// File được sinh bởi tools/SimsObjectGenerator. Không sửa trực tiếp file này.
// </auto-generated>

#nullable enable

namespace SimsObject;

/// <summary>
/// [SIM] Quyền chia sẻ tài nguyên video cho giảng viên.
/// </summary>
public partial class SIM_VideoAssetShares
{
    public const string TableSchema = "dbo";
    public const string TableName = "SIM_VideoAssetShares";
    public const string QualifiedTableName = "[dbo].[SIM_VideoAssetShares]";

    public const string C_VideoAssetShareID = "VideoAssetShareID";
    public const string P_VideoAssetShareID = "@VideoAssetShareID";

    public const string C_VideoAssetId = "VideoAssetId";
    public const string P_VideoAssetId = "@VideoAssetId";

    public const string C_TeacherUserID = "TeacherUserID";
    public const string P_TeacherUserID = "@TeacherUserID";

    public const string C_SharedByUserID = "SharedByUserID";
    public const string P_SharedByUserID = "@SharedByUserID";

    public const string C_SharedAt = "SharedAt";
    public const string P_SharedAt = "@SharedAt";

    /// <summary>
    /// Khóa chính tự tăng của lượt chia sẻ video. (Khóa chính, Tự tăng).
    /// </summary>
    public long VideoAssetShareID { get; set; }

    /// <summary>
    /// ID tài nguyên video được chia sẻ.
    /// </summary>
    public long VideoAssetId { get; set; }

    /// <summary>
    /// ID giáo viên được quyền nhìn thấy và sử dụng video.
    /// </summary>
    public long TeacherUserID { get; set; }

    /// <summary>
    /// ID tác giả hoặc quản trị viên thực hiện chia sẻ.
    /// </summary>
    public long SharedByUserID { get; set; }

    /// <summary>
    /// Thời điểm cấp quyền chia sẻ theo UTC.
    /// </summary>
    public DateTime SharedAt { get; set; }
}
