// <auto-generated>
// File được sinh bởi tools/SimsObjectGenerator. Không sửa trực tiếp file này.
// </auto-generated>

#nullable enable

namespace SimsObject;

/// <summary>
/// [SYS] Quan hệ giữa vai trò và quyền được cấp.
/// </summary>
public partial class SYS_RolePermissions
{
    public const string TableSchema = "dbo";
    public const string TableName = "SYS_RolePermissions";
    public const string QualifiedTableName = "[dbo].[SYS_RolePermissions]";

    public const string C_RoleId = "RoleId";
    public const string P_RoleId = "@RoleId";

    public const string C_PermissionId = "PermissionId";
    public const string P_PermissionId = "@PermissionId";

    /// <summary>
    /// ID vai trò được cấp quyền. (Khóa chính).
    /// </summary>
    public long RoleId { get; set; }

    /// <summary>
    /// ID quyền được cấp cho vai trò. (Khóa chính).
    /// </summary>
    public long PermissionId { get; set; }
}
