// <auto-generated>
// File được sinh bởi tools/SimsObjectGenerator. Không sửa trực tiếp file này.
// </auto-generated>

#nullable enable

namespace SimsObject;

/// <summary>
/// [SYS] Danh mục vai trò sử dụng trong hệ thống.
/// </summary>
public partial class SYS_Roles
{
    public const string TableSchema = "dbo";
    public const string TableName = "SYS_Roles";
    public const string QualifiedTableName = "[dbo].[SYS_Roles]";

    public const string C_RoleID = "RoleID";
    public const string P_RoleID = "@RoleID";

    public const string C_Code = "Code";
    public const string P_Code = "@Code";

    public const string C_Name = "Name";
    public const string P_Name = "@Name";

    public const string C_Description = "Description";
    public const string P_Description = "@Description";

    public const string C_Status = "Status";
    public const string P_Status = "@Status";

    /// <summary>
    /// Khóa chính tự tăng của vai trò. (Khóa chính, Tự tăng).
    /// </summary>
    public long RoleID { get; set; }

    /// <summary>
    /// Mã kỹ thuật duy nhất của vai trò, ví dụ ADMIN, TEACHER, STUDENT.
    /// </summary>
    public string? Code { get; set; }

    /// <summary>
    /// Tên hiển thị của vai trò.
    /// </summary>
    public string? Name { get; set; }

    /// <summary>
    /// Mô tả phạm vi và mục đích của vai trò.
    /// </summary>
    public string? Description { get; set; }

    /// <summary>
    /// Trạng thái sử dụng của vai trò.
    /// </summary>
    public string? Status { get; set; }
}
