// <auto-generated>
// File được sinh bởi tools/SimsObjectGenerator. Không sửa trực tiếp file này.
// </auto-generated>

#nullable enable

namespace SimsObject;

/// <summary>
/// [SYS] Refresh token phục vụ xác thực và gia hạn phiên.
/// </summary>
public partial class SYS_RefreshTokens
{
    public const string TableSchema = "dbo";
    public const string TableName = "SYS_RefreshTokens";
    public const string QualifiedTableName = "[dbo].[SYS_RefreshTokens]";

    public const string C_RefreshTokenID = "RefreshTokenID";
    public const string P_RefreshTokenID = "@RefreshTokenID";

    public const string C_UserId = "UserId";
    public const string P_UserId = "@UserId";

    public const string C_TokenHash = "TokenHash";
    public const string P_TokenHash = "@TokenHash";

    public const string C_ExpiresAt = "ExpiresAt";
    public const string P_ExpiresAt = "@ExpiresAt";

    public const string C_CreatedAt = "CreatedAt";
    public const string P_CreatedAt = "@CreatedAt";

    public const string C_RevokedAt = "RevokedAt";
    public const string P_RevokedAt = "@RevokedAt";

    public const string C_CreatedIp = "CreatedIp";
    public const string P_CreatedIp = "@CreatedIp";

    public const string C_RevokedIp = "RevokedIp";
    public const string P_RevokedIp = "@RevokedIp";

    public const string C_IsRevoked = "IsRevoked";
    public const string P_IsRevoked = "@IsRevoked";

    /// <summary>
    /// Khóa chính tự tăng của refresh token. (Khóa chính, Tự tăng).
    /// </summary>
    public long RefreshTokenID { get; set; }

    /// <summary>
    /// ID người dùng sở hữu refresh token.
    /// </summary>
    public long UserId { get; set; }

    /// <summary>
    /// Giá trị refresh token đã được băm.
    /// </summary>
    public string? TokenHash { get; set; }

    /// <summary>
    /// Thời điểm refresh token hết hạn theo UTC.
    /// </summary>
    public DateTime ExpiresAt { get; set; }

    /// <summary>
    /// Thời điểm phát hành refresh token theo UTC.
    /// </summary>
    public DateTime CreatedAt { get; set; }

    /// <summary>
    /// Thời điểm refresh token bị thu hồi theo UTC.
    /// </summary>
    public DateTime? RevokedAt { get; set; }

    /// <summary>
    /// Địa chỉ IP yêu cầu phát hành refresh token.
    /// </summary>
    public string? CreatedIp { get; set; }

    /// <summary>
    /// Địa chỉ IP thực hiện thu hồi refresh token.
    /// </summary>
    public string? RevokedIp { get; set; }

    /// <summary>
    /// Cờ cho biết refresh token đã bị thu hồi hay chưa.
    /// </summary>
    public bool IsRevoked { get; set; }
}
