// <auto-generated>
// File được sinh bởi tools/SimsObjectGenerator. Không sửa trực tiếp file này.
// </auto-generated>

#nullable enable

namespace SimsObject;

/// <summary>
/// [SYS] Nhóm quyền nghiệp vụ nằm trong một danh mục quyền.
/// </summary>
public partial class SYS_PermissionGroup
{
    public const string TableSchema = "dbo";
    public const string TableName = "SYS_PermissionGroup";
    public const string QualifiedTableName = "[dbo].[SYS_PermissionGroup]";

    public const string C_PermissionGroupID = "PermissionGroupID";
    public const string P_PermissionGroupID = "@PermissionGroupID";

    public const string C_PermissionGroupName = "PermissionGroupName";
    public const string P_PermissionGroupName = "@PermissionGroupName";

    public const string C_PermissionCategoryID = "PermissionCategoryID";
    public const string P_PermissionCategoryID = "@PermissionCategoryID";

    public const string C_SortOrder = "SortOrder";
    public const string P_SortOrder = "@SortOrder";

    public const string C_IsActived = "IsActived";
    public const string P_IsActived = "@IsActived";

    /// <summary>
    /// Cột PermissionGroupID của bảng SYS_PermissionGroup, lưu thông tin phục vụ nghiệp vụ được mô tả ở cấp bảng. (Khóa chính).
    /// </summary>
    public string? PermissionGroupID { get; set; }

    /// <summary>
    /// Cột PermissionGroupName của bảng SYS_PermissionGroup, lưu thông tin phục vụ nghiệp vụ được mô tả ở cấp bảng.
    /// </summary>
    public string? PermissionGroupName { get; set; }

    /// <summary>
    /// Cột PermissionCategoryID của bảng SYS_PermissionGroup, lưu thông tin phục vụ nghiệp vụ được mô tả ở cấp bảng.
    /// </summary>
    public int PermissionCategoryID { get; set; }

    /// <summary>
    /// Cột SortOrder của bảng SYS_PermissionGroup, lưu thông tin phục vụ nghiệp vụ được mô tả ở cấp bảng.
    /// </summary>
    public int SortOrder { get; set; }

    /// <summary>
    /// Cột IsActived của bảng SYS_PermissionGroup, lưu thông tin phục vụ nghiệp vụ được mô tả ở cấp bảng.
    /// </summary>
    public bool IsActived { get; set; }
}
