// <auto-generated>
// File được sinh bởi tools/SimsObjectGenerator. Không sửa trực tiếp file này.
// </auto-generated>

#nullable enable

namespace SimsObject;

/// <summary>
/// [SYS] Danh mục cấp cao dùng phân loại quyền hệ thống.
/// </summary>
public partial class SYS_PermissionCategory
{
    public const string TableSchema = "dbo";
    public const string TableName = "SYS_PermissionCategory";
    public const string QualifiedTableName = "[dbo].[SYS_PermissionCategory]";

    public const string C_PermissionCategoryID = "PermissionCategoryID";
    public const string P_PermissionCategoryID = "@PermissionCategoryID";

    public const string C_PermissionCategoryName = "PermissionCategoryName";
    public const string P_PermissionCategoryName = "@PermissionCategoryName";

    public const string C_IsDefault = "IsDefault";
    public const string P_IsDefault = "@IsDefault";

    public const string C_IsActived = "IsActived";
    public const string P_IsActived = "@IsActived";

    public const string C_SortOrder = "SortOrder";
    public const string P_SortOrder = "@SortOrder";

    /// <summary>
    /// Cột PermissionCategoryID của bảng SYS_PermissionCategory, lưu thông tin phục vụ nghiệp vụ được mô tả ở cấp bảng. (Khóa chính).
    /// </summary>
    public int PermissionCategoryID { get; set; }

    /// <summary>
    /// Cột PermissionCategoryName của bảng SYS_PermissionCategory, lưu thông tin phục vụ nghiệp vụ được mô tả ở cấp bảng.
    /// </summary>
    public string? PermissionCategoryName { get; set; }

    /// <summary>
    /// Cột IsDefault của bảng SYS_PermissionCategory, lưu thông tin phục vụ nghiệp vụ được mô tả ở cấp bảng.
    /// </summary>
    public bool IsDefault { get; set; }

    /// <summary>
    /// Cột IsActived của bảng SYS_PermissionCategory, lưu thông tin phục vụ nghiệp vụ được mô tả ở cấp bảng.
    /// </summary>
    public bool IsActived { get; set; }

    /// <summary>
    /// Cột SortOrder của bảng SYS_PermissionCategory, lưu thông tin phục vụ nghiệp vụ được mô tả ở cấp bảng.
    /// </summary>
    public int SortOrder { get; set; }
}
