// <auto-generated>
// File được sinh bởi tools/SimsObjectGenerator. Không sửa trực tiếp file này.
// </auto-generated>

#nullable enable

namespace SimsObject;

/// <summary>
/// [SYS] Thông báo nghiệp vụ gửi đến từng tài khoản, hỗ trợ trạng thái đã đọc và điều hướng đến dữ liệu liên quan.
/// </summary>
public partial class SYS_Notifications
{
    public const string TableSchema = "dbo";
    public const string TableName = "SYS_Notifications";
    public const string QualifiedTableName = "[dbo].[SYS_Notifications]";

    public const string C_NotificationID = "NotificationID";
    public const string P_NotificationID = "@NotificationID";

    public const string C_RecipientUserID = "RecipientUserID";
    public const string P_RecipientUserID = "@RecipientUserID";

    public const string C_ActorUserID = "ActorUserID";
    public const string P_ActorUserID = "@ActorUserID";

    public const string C_NotificationType = "NotificationType";
    public const string P_NotificationType = "@NotificationType";

    public const string C_Title = "Title";
    public const string P_Title = "@Title";

    public const string C_Message = "Message";
    public const string P_Message = "@Message";

    public const string C_ReferenceType = "ReferenceType";
    public const string P_ReferenceType = "@ReferenceType";

    public const string C_ReferenceID = "ReferenceID";
    public const string P_ReferenceID = "@ReferenceID";

    public const string C_ActionUrl = "ActionUrl";
    public const string P_ActionUrl = "@ActionUrl";

    public const string C_MetadataJson = "MetadataJson";
    public const string P_MetadataJson = "@MetadataJson";

    public const string C_IsRead = "IsRead";
    public const string P_IsRead = "@IsRead";

    public const string C_ReadAt = "ReadAt";
    public const string P_ReadAt = "@ReadAt";

    public const string C_CreatedAt = "CreatedAt";
    public const string P_CreatedAt = "@CreatedAt";

    public const string C_ExpiresAt = "ExpiresAt";
    public const string P_ExpiresAt = "@ExpiresAt";

    /// <summary>
    /// Khóa chính tự tăng của thông báo. (Khóa chính, Tự tăng).
    /// </summary>
    public long NotificationID { get; set; }

    /// <summary>
    /// Tài khoản nhận và xem thông báo.
    /// </summary>
    public long RecipientUserID { get; set; }

    /// <summary>
    /// Tài khoản thực hiện hành động phát sinh thông báo; có thể rỗng đối với thông báo hệ thống.
    /// </summary>
    public long? ActorUserID { get; set; }

    /// <summary>
    /// Loại nghiệp vụ của thông báo, ví dụ ENROLLMENT, ANSWER_SUBMITTED hoặc LESSON_COMPLETED.
    /// </summary>
    public string? NotificationType { get; set; }

    /// <summary>
    /// Tiêu đề ngắn hiển thị trong danh sách thông báo.
    /// </summary>
    public string? Title { get; set; }

    /// <summary>
    /// Nội dung chi tiết giải thích sự kiện phát sinh thông báo.
    /// </summary>
    public string? Message { get; set; }

    /// <summary>
    /// Loại dữ liệu nghiệp vụ được tham chiếu như COURSE, LESSON hoặc STUDENT_ANSWER.
    /// </summary>
    public string? ReferenceType { get; set; }

    /// <summary>
    /// Khóa định danh của dữ liệu nghiệp vụ được tham chiếu.
    /// </summary>
    public long? ReferenceID { get; set; }

    /// <summary>
    /// Đường dẫn nội bộ để mở màn hình liên quan khi người dùng chọn thông báo.
    /// </summary>
    public string? ActionUrl { get; set; }

    /// <summary>
    /// Dữ liệu mở rộng dạng JSON phục vụ hiển thị hoặc tích hợp trong tương lai.
    /// </summary>
    public string? MetadataJson { get; set; }

    /// <summary>
    /// Đánh dấu người nhận đã đọc thông báo hay chưa.
    /// </summary>
    public bool IsRead { get; set; }

    /// <summary>
    /// Thời điểm UTC người nhận đánh dấu đã đọc thông báo.
    /// </summary>
    public DateTime? ReadAt { get; set; }

    /// <summary>
    /// Thời điểm UTC thông báo được tạo.
    /// </summary>
    public DateTime CreatedAt { get; set; }

    /// <summary>
    /// Thời điểm UTC thông báo hết hiệu lực; rỗng nghĩa là không tự hết hạn.
    /// </summary>
    public DateTime? ExpiresAt { get; set; }
}
