// <auto-generated>
// File được sinh bởi tools/SimsObjectGenerator. Không sửa trực tiếp file này.
// </auto-generated>

#nullable enable

namespace SimsObject;

/// <summary>
/// [SYS] Cấu hình vận hành và hiển thị dùng chung của hệ thống.
/// </summary>
public partial class SYS_SystemSettings
{
    public const string TableSchema = "dbo";
    public const string TableName = "SYS_SystemSettings";
    public const string QualifiedTableName = "[dbo].[SYS_SystemSettings]";

    public const string C_SystemSettingID = "SystemSettingID";
    public const string P_SystemSettingID = "@SystemSettingID";

    public const string C_SettingKey = "SettingKey";
    public const string P_SettingKey = "@SettingKey";

    public const string C_SettingName = "SettingName";
    public const string P_SettingName = "@SettingName";

    public const string C_SettingValue = "SettingValue";
    public const string P_SettingValue = "@SettingValue";

    public const string C_DataType = "DataType";
    public const string P_DataType = "@DataType";

    public const string C_Category = "Category";
    public const string P_Category = "@Category";

    public const string C_Description = "Description";
    public const string P_Description = "@Description";

    public const string C_SortOrder = "SortOrder";
    public const string P_SortOrder = "@SortOrder";

    public const string C_IsPublic = "IsPublic";
    public const string P_IsPublic = "@IsPublic";

    public const string C_CreatedAt = "CreatedAt";
    public const string P_CreatedAt = "@CreatedAt";

    public const string C_UpdatedAt = "UpdatedAt";
    public const string P_UpdatedAt = "@UpdatedAt";

    public const string C_UpdatedByUserID = "UpdatedByUserID";
    public const string P_UpdatedByUserID = "@UpdatedByUserID";

    /// <summary>
    /// Khóa chính định danh cấu hình hệ thống. (Khóa chính, Tự tăng).
    /// </summary>
    public long SystemSettingID { get; set; }

    /// <summary>
    /// Mã cấu hình duy nhất dùng trong mã nguồn và API.
    /// </summary>
    public string? SettingKey { get; set; }

    /// <summary>
    /// Tên tiếng Việt hiển thị cho quản trị viên.
    /// </summary>
    public string? SettingName { get; set; }

    /// <summary>
    /// Giá trị cấu hình được lưu dưới dạng chuỗi và diễn giải theo DataType.
    /// </summary>
    public string? SettingValue { get; set; }

    /// <summary>
    /// Kiểu dữ liệu của giá trị: TEXT, NUMBER, BOOLEAN, EMAIL hoặc URL.
    /// </summary>
    public string? DataType { get; set; }

    /// <summary>
    /// Nhóm cấu hình phục vụ phân loại trên giao diện.
    /// </summary>
    public string? Category { get; set; }

    /// <summary>
    /// Mô tả ý nghĩa và phạm vi ảnh hưởng của cấu hình.
    /// </summary>
    public string? Description { get; set; }

    /// <summary>
    /// Thứ tự hiển thị cấu hình trong cùng nhóm.
    /// </summary>
    public int SortOrder { get; set; }

    /// <summary>
    /// Cho biết cấu hình có được phép công khai cho giao diện người dùng hay không.
    /// </summary>
    public bool IsPublic { get; set; }

    /// <summary>
    /// Thời điểm cấu hình được tạo theo UTC.
    /// </summary>
    public DateTime CreatedAt { get; set; }

    /// <summary>
    /// Thời điểm cấu hình được cập nhật gần nhất theo UTC.
    /// </summary>
    public DateTime? UpdatedAt { get; set; }

    /// <summary>
    /// Tài khoản quản trị cập nhật cấu hình gần nhất; liên kết SYS_Users.UserID.
    /// </summary>
    public long? UpdatedByUserID { get; set; }
}
