// <auto-generated>
// File được sinh bởi tools/SimsObjectGenerator. Không sửa trực tiếp file này.
// </auto-generated>

#nullable enable

namespace SimsObject;

/// <summary>
/// [SYS] Danh mục quyền thao tác theo từng phân hệ.
/// </summary>
public partial class SYS_Permissions
{
    public const string TableSchema = "dbo";
    public const string TableName = "SYS_Permissions";
    public const string QualifiedTableName = "[dbo].[SYS_Permissions]";

    public const string C_PermissionID = "PermissionID";
    public const string P_PermissionID = "@PermissionID";

    public const string C_Code = "Code";
    public const string P_Code = "@Code";

    public const string C_Name = "Name";
    public const string P_Name = "@Name";

    public const string C_Module = "Module";
    public const string P_Module = "@Module";

    public const string C_Description = "Description";
    public const string P_Description = "@Description";

    public const string C_PermissionCategoryID = "PermissionCategoryID";
    public const string P_PermissionCategoryID = "@PermissionCategoryID";

    public const string C_PermissionGroupID = "PermissionGroupID";
    public const string P_PermissionGroupID = "@PermissionGroupID";

    /// <summary>
    /// Khóa chính tự tăng của quyền. (Khóa chính, Tự tăng).
    /// </summary>
    public long PermissionID { get; set; }

    /// <summary>
    /// Mã kỹ thuật duy nhất của quyền.
    /// </summary>
    public string? Code { get; set; }

    /// <summary>
    /// Tên hiển thị của quyền.
    /// </summary>
    public string? Name { get; set; }

    /// <summary>
    /// Tên phân hệ chức năng sở hữu quyền.
    /// </summary>
    public string? Module { get; set; }

    /// <summary>
    /// Mô tả thao tác mà quyền cho phép thực hiện.
    /// </summary>
    public string? Description { get; set; }

    /// <summary>
    /// Mã danh mục quyền chứa quyền chức năng này.
    /// </summary>
    public int? PermissionCategoryID { get; set; }

    /// <summary>
    /// Mã nhóm quyền nghiệp vụ chứa quyền chức năng này.
    /// </summary>
    public string? PermissionGroupID { get; set; }
}
