// <auto-generated>
// File được sinh bởi tools/SimsObjectGenerator. Không sửa trực tiếp file này.
// </auto-generated>

#nullable enable

namespace SimsObject;

/// <summary>
/// [SYS] Nhật ký thao tác và thay đổi dữ liệu quan trọng.
/// </summary>
public partial class SYS_AuditLogs
{
    public const string TableSchema = "dbo";
    public const string TableName = "SYS_AuditLogs";
    public const string QualifiedTableName = "[dbo].[SYS_AuditLogs]";

    public const string C_AuditLogID = "AuditLogID";
    public const string P_AuditLogID = "@AuditLogID";

    public const string C_UserId = "UserId";
    public const string P_UserId = "@UserId";

    public const string C_Action = "Action";
    public const string P_Action = "@Action";

    public const string C_Module = "Module";
    public const string P_Module = "@Module";

    public const string C_EntityName = "EntityName";
    public const string P_EntityName = "@EntityName";

    public const string C_EntityId = "EntityId";
    public const string P_EntityId = "@EntityId";

    public const string C_OldValuesJson = "OldValuesJson";
    public const string P_OldValuesJson = "@OldValuesJson";

    public const string C_NewValuesJson = "NewValuesJson";
    public const string P_NewValuesJson = "@NewValuesJson";

    public const string C_IpAddress = "IpAddress";
    public const string P_IpAddress = "@IpAddress";

    public const string C_UserAgent = "UserAgent";
    public const string P_UserAgent = "@UserAgent";

    public const string C_CreatedAt = "CreatedAt";
    public const string P_CreatedAt = "@CreatedAt";

    /// <summary>
    /// Khóa chính tự tăng của bản ghi nhật ký. (Khóa chính, Tự tăng).
    /// </summary>
    public long AuditLogID { get; set; }

    /// <summary>
    /// ID người dùng thực hiện thao tác; có thể rỗng với tác vụ hệ thống.
    /// </summary>
    public long? UserId { get; set; }

    /// <summary>
    /// Tên hành động được ghi nhận.
    /// </summary>
    public string? Action { get; set; }

    /// <summary>
    /// Phân hệ phát sinh hành động.
    /// </summary>
    public string? Module { get; set; }

    /// <summary>
    /// Tên loại dữ liệu bị tác động.
    /// </summary>
    public string? EntityName { get; set; }

    /// <summary>
    /// Khóa định danh của bản ghi bị tác động.
    /// </summary>
    public string? EntityId { get; set; }

    /// <summary>
    /// Dữ liệu trước thay đổi ở định dạng JSON.
    /// </summary>
    public string? OldValuesJson { get; set; }

    /// <summary>
    /// Dữ liệu sau thay đổi ở định dạng JSON.
    /// </summary>
    public string? NewValuesJson { get; set; }

    /// <summary>
    /// Địa chỉ IP của thiết bị thực hiện thao tác.
    /// </summary>
    public string? IpAddress { get; set; }

    /// <summary>
    /// Thông tin trình duyệt hoặc ứng dụng khách.
    /// </summary>
    public string? UserAgent { get; set; }

    /// <summary>
    /// Thời điểm ghi nhận hành động theo UTC.
    /// </summary>
    public DateTime CreatedAt { get; set; }
}
