// <auto-generated>
// File được sinh bởi tools/SimsObjectGenerator. Không sửa trực tiếp file này.
// </auto-generated>

#nullable enable

namespace SimsObject;

/// <summary>
/// [SYS] Quan hệ nhiều-nhiều giữa tài khoản và vai trò.
/// </summary>
public partial class SYS_UserRoles
{
    public const string TableSchema = "dbo";
    public const string TableName = "SYS_UserRoles";
    public const string QualifiedTableName = "[dbo].[SYS_UserRoles]";

    public const string C_UserId = "UserId";
    public const string P_UserId = "@UserId";

    public const string C_RoleId = "RoleId";
    public const string P_RoleId = "@RoleId";

    /// <summary>
    /// ID người dùng được gán vai trò. (Khóa chính).
    /// </summary>
    public long UserId { get; set; }

    /// <summary>
    /// ID vai trò được gán cho người dùng. (Khóa chính).
    /// </summary>
    public long RoleId { get; set; }
}
