// <auto-generated>
// File được sinh bởi tools/SimsObjectGenerator. Không sửa trực tiếp file này.
// </auto-generated>

#nullable enable

namespace SimsObject;

/// <summary>
/// [SYS] Tài khoản quản trị viên, giảng viên và học viên.
/// </summary>
public partial class SYS_Users
{
    public const string TableSchema = "dbo";
    public const string TableName = "SYS_Users";
    public const string QualifiedTableName = "[dbo].[SYS_Users]";

    public const string C_UserID = "UserID";
    public const string P_UserID = "@UserID";

    public const string C_Username = "Username";
    public const string P_Username = "@Username";

    public const string C_PasswordHash = "PasswordHash";
    public const string P_PasswordHash = "@PasswordHash";

    public const string C_FullName = "FullName";
    public const string P_FullName = "@FullName";

    public const string C_Email = "Email";
    public const string P_Email = "@Email";

    public const string C_StudentCode = "StudentCode";
    public const string P_StudentCode = "@StudentCode";

    public const string C_TeacherCode = "TeacherCode";
    public const string P_TeacherCode = "@TeacherCode";

    public const string C_AvatarUrl = "AvatarUrl";
    public const string P_AvatarUrl = "@AvatarUrl";

    public const string C_Status = "Status";
    public const string P_Status = "@Status";

    public const string C_LastLoginAt = "LastLoginAt";
    public const string P_LastLoginAt = "@LastLoginAt";

    public const string C_CreatedAt = "CreatedAt";
    public const string P_CreatedAt = "@CreatedAt";

    public const string C_UpdatedAt = "UpdatedAt";
    public const string P_UpdatedAt = "@UpdatedAt";

    public const string C_CreatedByUserID = "CreatedByUserID";
    public const string P_CreatedByUserID = "@CreatedByUserID";

    public const string C_UpdatedByUserID = "UpdatedByUserID";
    public const string P_UpdatedByUserID = "@UpdatedByUserID";

    public const string C_IsDeleted = "IsDeleted";
    public const string P_IsDeleted = "@IsDeleted";

    public const string C_DataGroupID = "DataGroupID";
    public const string P_DataGroupID = "@DataGroupID";

    public const string C_StudentID = "StudentID";
    public const string P_StudentID = "@StudentID";

    public const string C_TeacherID = "TeacherID";
    public const string P_TeacherID = "@TeacherID";

    /// <summary>
    /// Khóa chính tự tăng của người dùng. (Khóa chính, Tự tăng).
    /// </summary>
    public long UserID { get; set; }

    /// <summary>
    /// Tên đăng nhập duy nhất của người dùng.
    /// </summary>
    public string? Username { get; set; }

    /// <summary>
    /// Chuỗi mật khẩu đã băm; không lưu mật khẩu dạng rõ.
    /// </summary>
    public string? PasswordHash { get; set; }

    /// <summary>
    /// Họ và tên đầy đủ của người dùng.
    /// </summary>
    public string? FullName { get; set; }

    /// <summary>
    /// Địa chỉ email duy nhất của người dùng.
    /// </summary>
    public string? Email { get; set; }

    /// <summary>
    /// Mã học viên; chỉ có giá trị với tài khoản học viên.
    /// </summary>
    public string? StudentCode { get; set; }

    /// <summary>
    /// Mã giảng viên; chỉ có giá trị với tài khoản giảng viên.
    /// </summary>
    public string? TeacherCode { get; set; }

    /// <summary>
    /// Đường dẫn ảnh đại diện của người dùng.
    /// </summary>
    public string? AvatarUrl { get; set; }

    /// <summary>
    /// Trạng thái tài khoản: ACTIVE, INACTIVE hoặc LOCKED.
    /// </summary>
    public string? Status { get; set; }

    /// <summary>
    /// Thời điểm đăng nhập thành công gần nhất theo UTC.
    /// </summary>
    public DateTime? LastLoginAt { get; set; }

    /// <summary>
    /// Thời điểm tạo tài khoản theo UTC.
    /// </summary>
    public DateTime CreatedAt { get; set; }

    /// <summary>
    /// Thời điểm cập nhật tài khoản gần nhất theo UTC.
    /// </summary>
    public DateTime? UpdatedAt { get; set; }

    /// <summary>
    /// ID người dùng đã tạo tài khoản này.
    /// </summary>
    public long? CreatedByUserID { get; set; }

    /// <summary>
    /// ID người dùng cập nhật tài khoản gần nhất.
    /// </summary>
    public long? UpdatedByUserID { get; set; }

    /// <summary>
    /// Cờ xóa mềm: 1 là đã xóa, 0 là đang sử dụng.
    /// </summary>
    public bool IsDeleted { get; set; }

    /// <summary>
    /// Mã đơn vị hoặc nhóm dữ liệu sở hữu tài khoản.
    /// </summary>
    public int DataGroupID { get; set; }

    /// <summary>
    /// Mã hồ sơ học viên liên kết với tài khoản, nếu người dùng là học viên.
    /// </summary>
    public string? StudentID { get; set; }

    /// <summary>
    /// Mã hồ sơ giảng viên liên kết với tài khoản, nếu người dùng là giảng viên.
    /// </summary>
    public string? TeacherID { get; set; }
}
