<template>
  <section><header class="mb-4"><h1 class="page-title">Khóa học của tôi</h1><p class="page-subtitle">Theo dõi và tiếp tục các khóa học đã ghi danh.</p></header><div class="app-card p-3 mb-4"><div class="row g-2"><div class="col-md-8"><input v-model="search" class="form-control" placeholder="Tìm theo tên khóa học hoặc giảng viên..."></div><div class="col-md-4"><select v-model="status" class="form-select"><option value="">Tất cả trạng thái</option><option value="ENROLLED">Chưa bắt đầu</option><option value="IN_PROGRESS">Đang học</option><option value="COMPLETED">Hoàn thành</option></select></div></div></div>
    <div v-if="loading" class="app-card p-5 text-center"><span class="spinner-border text-success"></span></div><div v-else-if="error" class="alert alert-danger">{{ error }} <button class="btn btn-sm btn-light ms-2" @click="loadCourses">Thử lại</button></div><div v-else-if="!filtered.length" class="app-card p-5 text-center text-secondary"><i class="bi bi-journal-x fs-1"></i><p class="mt-2 mb-0">Không có khóa học phù hợp.</p></div>
    <div v-else class="row g-4"><div v-for="course in filtered" :key="course.id" class="col-md-6 col-xl-4"><article class="course-card app-card h-100"><div class="course-art" :style="{background:course.color}"><i class="bi bi-code-square"></i><span>{{ course.code }}</span></div><div class="p-3"><span class="badge badge-soft-primary">{{ course.category }}</span><h2>{{ course.title }}</h2><p><i class="bi bi-person me-1"></i>{{ course.teacher }}</p><div class="d-flex justify-content-between small"><span>{{ course.lessons }} bài học</span><b>{{ course.progress }}%</b></div><div class="progress my-2" style="height:7px"><div class="progress-bar" :style="{width:course.progress+'%'}"></div></div><RouterLink :to="`/lms/courses/${course.id}`" class="btn btn-brand w-100 mt-2">Xem khóa học</RouterLink></div></article></div></div>
  </section>
</template>
<script setup>
import { computed,onMounted,ref } from 'vue'
import axiosClient from '../../api/axiosClient'
const search=ref(''),status=ref(''),courses=ref([]),loading=ref(true),error=ref(''),pick=(source,...names)=>names.map(name=>source?.[name]).find(value=>value!==undefined&&value!==null)
const colors=['#07875a','#005099','#465f55','#8a7000']
const filtered=computed(()=>courses.value.filter(c=>(!status.value||c.enrollmentStatus===status.value)&&(`${c.title} ${c.teacher}`.toLowerCase().includes(search.value.toLowerCase()))))
onMounted(loadCourses)
async function loadCourses(){loading.value=true;error.value='';try{const data=await axiosClient.get('/lms/courses',{params:{_fresh:Date.now()}});courses.value=(Array.isArray(data)?data:[]).map((row,index)=>({id:Number(pick(row,'Id','id')),code:pick(row,'Code','code')||'',title:pick(row,'Title','title')||'',teacher:pick(row,'TeacherName','teacherName')||'',category:pick(row,'CategoryName','categoryName')||'Khóa học',lessons:Number(pick(row,'LessonCount','lessonCount')||0),progress:Number(pick(row,'ProgressPercent','progressPercent')||0),enrollmentStatus:pick(row,'EnrollmentStatus','enrollmentStatus')||'ENROLLED',color:colors[index%colors.length]}))}catch(e){error.value=e.message}finally{loading.value=false}}
</script>
<style scoped>.course-card{overflow:hidden;transition:.2s}.course-card:hover{transform:translateY(-3px);box-shadow:0 13px 32px rgba(15,49,38,.09)}.course-art{height:145px;color:white;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:.4rem}.course-art i{font-size:2.6rem}.course-art span{font-weight:800}.course-card h2{font-size:1.08rem;font-weight:800;margin:.65rem 0}.course-card p{font-size:.86rem;color:#71817b}</style>
