<template>
  <section>
    <div class="welcome app-card mb-4"><div><span class="welcome-label">THỨ BA, 11 THÁNG 8</span><h1>Xin chào, Nguyễn Văn Học 👋</h1><p>Tiếp tục hành trình học tập và hoàn thành mục tiêu hôm nay.</p><RouterLink class="btn btn-brand" to="/lms/courses/1/lessons/104">Tiếp tục học <i class="bi bi-arrow-right ms-1"></i></RouterLink></div><div class="goal"><span class="goal-ring">72<small>%</small></span><div><strong>Mục tiêu tuần</strong><small>3 giờ 36 phút / 5 giờ</small></div></div></div>
    <div class="row g-3 mb-4"><div v-for="stat in stats" :key="stat.label" class="col-6 col-lg-3"><div class="stat app-card"><span :class="['stat-icon',stat.tone]"><i :class="['bi',stat.icon]"></i></span><div><strong>{{ stat.value }}</strong><small>{{ stat.label }}</small></div></div></div></div>
    <div class="d-flex justify-content-between align-items-end mb-3"><div><h2 class="h4 fw-bold mb-1">Tiếp tục học</h2><span class="page-subtitle">Khóa học bạn truy cập gần đây</span></div><RouterLink class="text-brand fw-semibold small" to="/lms/courses">Xem tất cả <i class="bi bi-arrow-right"></i></RouterLink></div>
    <div class="row g-4"><div v-for="course in courses.slice(0,2)" :key="course.id" class="col-lg-6"><article class="course app-card"><div class="course-cover" :style="{background:course.color}"><i class="bi bi-code-slash"></i><span>{{ course.code }}</span></div><div class="p-3 flex-grow-1"><span class="badge badge-soft-success mb-2">{{ course.category }}</span><h3>{{ course.title }}</h3><div class="small text-secondary mb-3"><i class="bi bi-person me-1"></i>{{ course.teacher }}</div><div class="d-flex justify-content-between small mb-1"><span>Tiến độ</span><b>{{ course.progress }}%</b></div><div class="progress mb-3" style="height:7px"><div class="progress-bar" :style="{width:course.progress+'%'}"></div></div><div class="d-flex justify-content-between align-items-center"><small class="text-secondary">Bài gần nhất: <b>{{ course.lastLesson }}</b></small><RouterLink class="btn btn-light btn-sm" :to="`/lms/courses/${course.id}`">Mở khóa học</RouterLink></div></div></article></div></div>
  </section>
</template>
<script setup>
import { courses } from '../../data/demo'
const stats=[{label:'Khóa học đang học',value:3,icon:'bi-journal-play',tone:'green'},{label:'Bài học hoàn thành',value:18,icon:'bi-check2-circle',tone:'blue'},{label:'Điểm trung bình',value:'8.4',icon:'bi-star',tone:'yellow'},{label:'Chuỗi học tập',value:'7 ngày',icon:'bi-fire',tone:'red'}]
</script>
<style scoped>
.welcome{min-height:220px;padding:2rem 2.2rem;display:flex;justify-content:space-between;align-items:center;background:linear-gradient(120deg,#fff 55%,#e9f6f1)}.welcome h1{font-size:clamp(1.8rem,3vw,2.7rem);font-weight:850;letter-spacing:-.04em}.welcome p{color:#65776f}.welcome-label{color:#07875a;font-size:.72rem;font-weight:850;letter-spacing:.12em}.goal{display:flex;align-items:center;gap:1rem;margin-right:2rem}.goal-ring{width:100px;height:100px;border-radius:50%;display:grid;place-items:center;background:#07875a;color:white;font-size:1.8rem;font-weight:850;box-shadow:0 12px 30px rgba(7,135,90,.2)}.goal-ring small{font-size:.8rem}.goal>div{display:grid}.goal>div small{color:#667970}.stat{padding:1.1rem;display:flex;align-items:center;gap:.9rem}.stat-icon{width:44px;height:44px;border-radius:11px;display:grid;place-items:center;font-size:1.2rem}.stat-icon.green{background:#e0f4ec;color:#07875a}.stat-icon.blue{background:#e5f0fa;color:#005099}.stat-icon.yellow{background:#fffbd1;color:#8a7000}.stat-icon.red{background:#fde9e9;color:#cd1b1b}.stat>div{display:grid}.stat strong{font-size:1.4rem}.stat small{color:#72817c}.course{display:flex;overflow:hidden;height:100%}.course-cover{width:150px;min-height:210px;color:white;display:flex;flex-direction:column;justify-content:center;align-items:center;gap:.7rem}.course-cover i{font-size:2.4rem}.course-cover span{font-weight:800}.course h3{font-size:1.05rem;font-weight:800}@media(max-width:767px){.goal{display:none}.welcome{padding:1.5rem}.course{display:block}.course-cover{width:100%;min-height:120px}}
</style>
