CREATE OR ALTER PROCEDURE dbo.LMS_Chapter_GetByCourse @CourseId BIGINT,@ActorId BIGINT,@IsAdmin BIT=0 AS
BEGIN SET NOCOUNT ON; IF NOT EXISTS(SELECT 1 FROM dbo.Courses WHERE Id=@CourseId AND IsDeleted=0 AND (@IsAdmin=1 OR TeacherId=@ActorId)) THROW 50003,N'Bạn không có quyền quản lý khóa học này.',1; SELECT Id,CourseId,Title,Description,SortOrder,Status FROM dbo.Chapters WHERE CourseId=@CourseId AND IsDeleted=0 ORDER BY SortOrder,Id; END
GO
CREATE OR ALTER PROCEDURE dbo.LMS_Chapter_Create @CourseId BIGINT,@Title NVARCHAR(500),@Description NVARCHAR(1000)=NULL,@SortOrder INT,@Status VARCHAR(30),@ActorId BIGINT,@IsAdmin BIT=0 AS
BEGIN SET NOCOUNT ON; IF NULLIF(LTRIM(RTRIM(@Title)),'') IS NULL OR @SortOrder<1 THROW 50001,N'Dữ liệu chương không hợp lệ.',1; IF NOT EXISTS(SELECT 1 FROM dbo.Courses WHERE Id=@CourseId AND IsDeleted=0 AND (@IsAdmin=1 OR TeacherId=@ActorId)) THROW 50003,N'Bạn không có quyền quản lý khóa học này.',1; INSERT dbo.Chapters(CourseId,Title,Description,SortOrder,Status) VALUES(@CourseId,@Title,@Description,@SortOrder,@Status); DECLARE @Id BIGINT=SCOPE_IDENTITY(); INSERT dbo.AuditLogs(UserId,Action,Module,EntityName,EntityId,NewValuesJson) VALUES(@ActorId,'CREATE','CHAPTER','Chapter',CONVERT(NVARCHAR(100),@Id),(SELECT @Title title FOR JSON PATH,WITHOUT_ARRAY_WRAPPER)); SELECT @Id; END
GO
CREATE OR ALTER PROCEDURE dbo.LMS_Chapter_Update @Id BIGINT,@Title NVARCHAR(500),@Description NVARCHAR(1000)=NULL,@SortOrder INT,@Status VARCHAR(30),@ActorId BIGINT,@IsAdmin BIT=0 AS
BEGIN SET NOCOUNT ON; IF NULLIF(LTRIM(RTRIM(@Title)),'') IS NULL OR @SortOrder<1 THROW 50001,N'Dữ liệu chương không hợp lệ.',1; UPDATE ch SET Title=@Title,Description=@Description,SortOrder=@SortOrder,Status=@Status,UpdatedAt=SYSUTCDATETIME() FROM dbo.Chapters ch JOIN dbo.Courses c ON c.Id=ch.CourseId WHERE ch.Id=@Id AND ch.IsDeleted=0 AND (@IsAdmin=1 OR c.TeacherId=@ActorId); DECLARE @Rows INT=@@ROWCOUNT; IF @Rows>0 INSERT dbo.AuditLogs(UserId,Action,Module,EntityName,EntityId) VALUES(@ActorId,'UPDATE','CHAPTER','Chapter',CONVERT(NVARCHAR(100),@Id)); SELECT @Rows; END
GO
CREATE OR ALTER PROCEDURE dbo.LMS_Chapter_Delete @Id BIGINT,@ActorId BIGINT,@IsAdmin BIT=0 AS
BEGIN SET NOCOUNT ON; SET XACT_ABORT ON; BEGIN TRANSACTION; UPDATE ch SET IsDeleted=1,UpdatedAt=SYSUTCDATETIME() FROM dbo.Chapters ch JOIN dbo.Courses c ON c.Id=ch.CourseId WHERE ch.Id=@Id AND ch.IsDeleted=0 AND (@IsAdmin=1 OR c.TeacherId=@ActorId); DECLARE @Rows INT=@@ROWCOUNT; IF @Rows>0 BEGIN UPDATE dbo.Lessons SET IsDeleted=1,UpdatedAt=SYSUTCDATETIME() WHERE ChapterId=@Id; INSERT dbo.AuditLogs(UserId,Action,Module,EntityName,EntityId) VALUES(@ActorId,'DELETE','CHAPTER','Chapter',CONVERT(NVARCHAR(100),@Id)); END; COMMIT; SELECT @Rows; END
GO
CREATE OR ALTER PROCEDURE dbo.LMS_Chapter_Reorder @Id BIGINT,@SortOrder INT,@ActorId BIGINT,@IsAdmin BIT=0 AS
BEGIN SET NOCOUNT ON; UPDATE ch SET SortOrder=@SortOrder,UpdatedAt=SYSUTCDATETIME() FROM dbo.Chapters ch JOIN dbo.Courses c ON c.Id=ch.CourseId WHERE ch.Id=@Id AND ch.IsDeleted=0 AND (@IsAdmin=1 OR c.TeacherId=@ActorId); IF @@ROWCOUNT=0 THROW 50003,N'Không thể sắp xếp chương này.',1; END
GO
CREATE OR ALTER PROCEDURE dbo.LMS_Lesson_GetById @Id BIGINT,@ActorId BIGINT,@IsAdmin BIT=0 AS
BEGIN SET NOCOUNT ON; SELECT l.* FROM dbo.Lessons l JOIN dbo.Courses c ON c.Id=l.CourseId WHERE l.Id=@Id AND l.IsDeleted=0 AND (@IsAdmin=1 OR c.TeacherId=@ActorId); END
GO
CREATE OR ALTER PROCEDURE dbo.LMS_Lesson_Create @ChapterId BIGINT,@Title NVARCHAR(500),@Description NVARCHAR(1000)=NULL,@LessonType VARCHAR(50),@DurationSeconds INT,@SortOrder INT,@IsRequired BIT,@PassingScore DECIMAL(5,2)=NULL,@Status VARCHAR(30),@ActorId BIGINT,@IsAdmin BIT=0 AS
BEGIN SET NOCOUNT ON; DECLARE @CourseId BIGINT=(SELECT ch.CourseId FROM dbo.Chapters ch JOIN dbo.Courses c ON c.Id=ch.CourseId WHERE ch.Id=@ChapterId AND ch.IsDeleted=0 AND (@IsAdmin=1 OR c.TeacherId=@ActorId)); IF @CourseId IS NULL THROW 50003,N'Bạn không có quyền quản lý chương này.',1; IF NULLIF(LTRIM(RTRIM(@Title)),'') IS NULL OR @LessonType NOT IN('VIDEO','INTERACTIVE_VIDEO','QUIZ','DOCUMENT') OR @DurationSeconds<0 OR @SortOrder<1 OR @PassingScore NOT BETWEEN 0 AND 100 THROW 50001,N'Dữ liệu bài học không hợp lệ.',1; INSERT dbo.Lessons(CourseId,ChapterId,Title,Description,LessonType,DurationSeconds,SortOrder,IsRequired,PassingScore,Status) VALUES(@CourseId,@ChapterId,@Title,@Description,@LessonType,@DurationSeconds,@SortOrder,@IsRequired,@PassingScore,@Status); DECLARE @Id BIGINT=SCOPE_IDENTITY(); INSERT dbo.AuditLogs(UserId,Action,Module,EntityName,EntityId) VALUES(@ActorId,'CREATE','LESSON','Lesson',CONVERT(NVARCHAR(100),@Id)); SELECT @Id; END
GO
CREATE OR ALTER PROCEDURE dbo.LMS_Lesson_Update @Id BIGINT,@Title NVARCHAR(500),@Description NVARCHAR(1000)=NULL,@LessonType VARCHAR(50),@DurationSeconds INT,@SortOrder INT,@IsRequired BIT,@PassingScore DECIMAL(5,2)=NULL,@Status VARCHAR(30),@ActorId BIGINT,@IsAdmin BIT=0 AS
BEGIN SET NOCOUNT ON; IF NULLIF(LTRIM(RTRIM(@Title)),'') IS NULL OR @LessonType NOT IN('VIDEO','INTERACTIVE_VIDEO','QUIZ','DOCUMENT') OR @DurationSeconds<0 OR @SortOrder<1 OR @PassingScore NOT BETWEEN 0 AND 100 THROW 50001,N'Dữ liệu bài học không hợp lệ.',1; UPDATE l SET Title=@Title,Description=@Description,LessonType=@LessonType,DurationSeconds=@DurationSeconds,SortOrder=@SortOrder,IsRequired=@IsRequired,PassingScore=@PassingScore,Status=@Status,UpdatedAt=SYSUTCDATETIME() FROM dbo.Lessons l JOIN dbo.Courses c ON c.Id=l.CourseId WHERE l.Id=@Id AND l.IsDeleted=0 AND (@IsAdmin=1 OR c.TeacherId=@ActorId); DECLARE @Rows INT=@@ROWCOUNT; IF @Rows>0 INSERT dbo.AuditLogs(UserId,Action,Module,EntityName,EntityId) VALUES(@ActorId,'UPDATE','LESSON','Lesson',CONVERT(NVARCHAR(100),@Id)); SELECT @Rows; END
GO
CREATE OR ALTER PROCEDURE dbo.LMS_Lesson_Delete @Id BIGINT,@ActorId BIGINT,@IsAdmin BIT=0 AS
BEGIN SET NOCOUNT ON; UPDATE l SET IsDeleted=1,UpdatedAt=SYSUTCDATETIME() FROM dbo.Lessons l JOIN dbo.Courses c ON c.Id=l.CourseId WHERE l.Id=@Id AND l.IsDeleted=0 AND (@IsAdmin=1 OR c.TeacherId=@ActorId); DECLARE @Rows INT=@@ROWCOUNT; IF @Rows>0 INSERT dbo.AuditLogs(UserId,Action,Module,EntityName,EntityId) VALUES(@ActorId,'DELETE','LESSON','Lesson',CONVERT(NVARCHAR(100),@Id)); SELECT @Rows; END
GO
CREATE OR ALTER PROCEDURE dbo.LMS_Lesson_Reorder @Id BIGINT,@SortOrder INT,@ActorId BIGINT,@IsAdmin BIT=0 AS
BEGIN SET NOCOUNT ON; UPDATE l SET SortOrder=@SortOrder,UpdatedAt=SYSUTCDATETIME() FROM dbo.Lessons l JOIN dbo.Courses c ON c.Id=l.CourseId WHERE l.Id=@Id AND l.IsDeleted=0 AND (@IsAdmin=1 OR c.TeacherId=@ActorId); IF @@ROWCOUNT=0 THROW 50003,N'Không thể sắp xếp bài học này.',1; END
GO
CREATE OR ALTER PROCEDURE dbo.LMS_Video_GetById @Id BIGINT AS BEGIN SET NOCOUNT ON; SELECT v.*,(SELECT COUNT(*) FROM dbo.Videos x WHERE x.VideoAssetId=v.VideoAssetId) AssetUsageCount FROM dbo.Videos v WHERE v.Id=@Id; END
GO
CREATE OR ALTER PROCEDURE dbo.LMS_Video_Create @Id BIGINT=NULL,@LessonId BIGINT,@Title NVARCHAR(500),@VideoUrl NVARCHAR(1000)=NULL,@PosterUrl NVARCHAR(1000)=NULL,@DurationSeconds INT,@AllowSeek BIT,@AllowSpeed BIT,@RequiredWatchPercent DECIMAL(5,2),@Status VARCHAR(30),@ActorId BIGINT,@IsAdmin BIT=0 AS
BEGIN SET NOCOUNT ON; SET XACT_ABORT ON; IF @DurationSeconds<=0 OR @RequiredWatchPercent NOT BETWEEN 0 AND 100 THROW 50001,N'Dữ liệu video không hợp lệ.',1; IF @VideoUrl IS NOT NULL AND (@VideoUrl NOT LIKE '/uploads/videos/%' OR @VideoUrl LIKE '%..%' OR @VideoUrl LIKE '%\%' OR @VideoUrl LIKE '%?%' OR @VideoUrl LIKE '%#%') THROW 50001,N'VideoUrl phải là URL tương đối an toàn trong /uploads/videos/.',1; IF NOT EXISTS(SELECT 1 FROM dbo.Lessons l JOIN dbo.Courses c ON c.Id=l.CourseId WHERE l.Id=@LessonId AND l.IsDeleted=0 AND (@IsAdmin=1 OR c.TeacherId=@ActorId)) THROW 50003,N'Bạn không có quyền quản lý bài học này.',1; IF EXISTS(SELECT 1 FROM dbo.Videos WHERE LessonId=@LessonId) THROW 50006,N'Bài học đã có video.',1; BEGIN TRANSACTION; INSERT dbo.VideoAssets(Title,VideoUrl,PosterUrl,DurationSeconds,CreatedBy,Status) VALUES(@Title,@VideoUrl,@PosterUrl,@DurationSeconds,@ActorId,@Status); DECLARE @AssetId BIGINT=SCOPE_IDENTITY(); INSERT dbo.Videos(LessonId,VideoAssetId,Title,VideoUrl,PosterUrl,DurationSeconds,AllowSeek,AllowSpeed,RequiredWatchPercent,Status) VALUES(@LessonId,@AssetId,@Title,@VideoUrl,@PosterUrl,@DurationSeconds,@AllowSeek,@AllowSpeed,@RequiredWatchPercent,@Status); DECLARE @VideoId BIGINT=SCOPE_IDENTITY(); INSERT dbo.AuditLogs(UserId,Action,Module,EntityName,EntityId) VALUES(@ActorId,'CREATE','VIDEO','Video',CONVERT(NVARCHAR(100),@VideoId)); COMMIT; SELECT @VideoId; END
GO
CREATE OR ALTER PROCEDURE dbo.LMS_Video_Update @Id BIGINT,@LessonId BIGINT,@Title NVARCHAR(500),@VideoUrl NVARCHAR(1000)=NULL,@PosterUrl NVARCHAR(1000)=NULL,@DurationSeconds INT,@AllowSeek BIT,@AllowSpeed BIT,@RequiredWatchPercent DECIMAL(5,2),@Status VARCHAR(30),@ActorId BIGINT,@IsAdmin BIT=0 AS
BEGIN SET NOCOUNT ON; SET XACT_ABORT ON; IF @DurationSeconds<=0 OR @RequiredWatchPercent NOT BETWEEN 0 AND 100 THROW 50001,N'Dữ liệu video không hợp lệ.',1; IF @VideoUrl IS NOT NULL AND (@VideoUrl NOT LIKE '/uploads/videos/%' OR @VideoUrl LIKE '%..%' OR @VideoUrl LIKE '%\%' OR @VideoUrl LIKE '%?%' OR @VideoUrl LIKE '%#%') THROW 50001,N'VideoUrl phải là URL tương đối an toàn trong /uploads/videos/.',1; DECLARE @AssetId BIGINT=(SELECT v.VideoAssetId FROM dbo.Videos v JOIN dbo.Lessons l ON l.Id=v.LessonId JOIN dbo.Courses c ON c.Id=l.CourseId WHERE v.Id=@Id AND v.LessonId=@LessonId AND (@IsAdmin=1 OR c.TeacherId=@ActorId)); IF @AssetId IS NULL AND NOT EXISTS(SELECT 1 FROM dbo.Videos v JOIN dbo.Lessons l ON l.Id=v.LessonId JOIN dbo.Courses c ON c.Id=l.CourseId WHERE v.Id=@Id AND v.LessonId=@LessonId AND (@IsAdmin=1 OR c.TeacherId=@ActorId)) THROW 50003,N'Bạn không có quyền quản lý video này.',1; BEGIN TRANSACTION; UPDATE dbo.Videos SET Title=@Title,VideoUrl=@VideoUrl,PosterUrl=@PosterUrl,DurationSeconds=@DurationSeconds WHERE VideoAssetId=@AssetId; UPDATE dbo.Videos SET Title=@Title,VideoUrl=@VideoUrl,PosterUrl=@PosterUrl,DurationSeconds=@DurationSeconds,AllowSeek=@AllowSeek,AllowSpeed=@AllowSpeed,RequiredWatchPercent=@RequiredWatchPercent,Status=@Status,UpdatedAt=SYSUTCDATETIME() WHERE Id=@Id; IF @AssetId IS NOT NULL UPDATE dbo.VideoAssets SET Title=@Title,VideoUrl=@VideoUrl,PosterUrl=@PosterUrl,DurationSeconds=@DurationSeconds,UpdatedAt=SYSUTCDATETIME() WHERE Id=@AssetId; INSERT dbo.AuditLogs(UserId,Action,Module,EntityName,EntityId) VALUES(@ActorId,'UPDATE','VIDEO','Video',CONVERT(NVARCHAR(100),@Id)); COMMIT; SELECT @Id; END
GO
CREATE OR ALTER PROCEDURE dbo.LMS_VideoLibrary_GetList @Search NVARCHAR(500)=NULL AS
BEGIN SET NOCOUNT ON; SELECT a.Id,a.Title,a.VideoUrl,a.PosterUrl,a.DurationSeconds,a.OriginalFileName,a.FileSize,a.MimeType,a.Status,a.CreatedAt,u.FullName CreatedByName,ISNULL(useInfo.UsageCount,0) UsageCount,useInfo.FirstVideoId FROM dbo.VideoAssets a JOIN dbo.Users u ON u.Id=a.CreatedBy OUTER APPLY(SELECT COUNT(*) UsageCount,MIN(v.Id) FirstVideoId FROM dbo.Videos v JOIN dbo.Lessons l ON l.Id=v.LessonId AND l.IsDeleted=0 WHERE v.VideoAssetId=a.Id) useInfo WHERE a.IsDeleted=0 AND (@Search IS NULL OR @Search='' OR a.Title LIKE '%'+@Search+'%' OR a.OriginalFileName LIKE '%'+@Search+'%') ORDER BY a.CreatedAt DESC,a.Id DESC; END
GO
CREATE OR ALTER PROCEDURE dbo.LMS_VideoLibrary_Create @Title NVARCHAR(500),@VideoUrl NVARCHAR(1000)=NULL,@PosterUrl NVARCHAR(1000)=NULL,@DurationSeconds INT,@OriginalFileName NVARCHAR(500)=NULL,@FileSize BIGINT=NULL,@MimeType NVARCHAR(150)=NULL,@ActorId BIGINT AS
BEGIN SET NOCOUNT ON; IF NULLIF(LTRIM(RTRIM(@Title)),'') IS NULL OR @DurationSeconds<=0 THROW 50001,N'Dữ liệu video thư viện không hợp lệ.',1; IF @VideoUrl IS NOT NULL AND (@VideoUrl NOT LIKE '/uploads/videos/%' OR @VideoUrl LIKE '%..%' OR @VideoUrl LIKE '%\%' OR @VideoUrl LIKE '%?%' OR @VideoUrl LIKE '%#%') THROW 50001,N'VideoUrl không hợp lệ.',1; INSERT dbo.VideoAssets(Title,VideoUrl,PosterUrl,DurationSeconds,OriginalFileName,FileSize,MimeType,CreatedBy) VALUES(@Title,@VideoUrl,@PosterUrl,@DurationSeconds,@OriginalFileName,@FileSize,@MimeType,@ActorId); DECLARE @Id BIGINT=SCOPE_IDENTITY(); INSERT dbo.AuditLogs(UserId,Action,Module,EntityName,EntityId) VALUES(@ActorId,'CREATE','VIDEO_LIBRARY','VideoAsset',CONVERT(NVARCHAR(100),@Id)); SELECT @Id; END
GO
CREATE OR ALTER PROCEDURE dbo.LMS_VideoLibrary_Delete @Id BIGINT,@ActorId BIGINT AS
BEGIN SET NOCOUNT ON; IF EXISTS(SELECT 1 FROM dbo.Videos v JOIN dbo.Lessons l ON l.Id=v.LessonId WHERE v.VideoAssetId=@Id AND l.IsDeleted=0) THROW 50006,N'Video đang được sử dụng trong bài học nên không thể xóa.',1; UPDATE dbo.VideoAssets SET IsDeleted=1,UpdatedAt=SYSUTCDATETIME() WHERE Id=@Id AND IsDeleted=0; DECLARE @Rows INT=@@ROWCOUNT; IF @Rows>0 INSERT dbo.AuditLogs(UserId,Action,Module,EntityName,EntityId) VALUES(@ActorId,'DELETE','VIDEO_LIBRARY','VideoAsset',CONVERT(NVARCHAR(100),@Id)); SELECT @Rows; END
GO
CREATE OR ALTER PROCEDURE dbo.LMS_VideoLibrary_Attach @LessonId BIGINT,@VideoAssetId BIGINT,@AllowSeek BIT,@AllowSpeed BIT,@RequiredWatchPercent DECIMAL(5,2),@ActorId BIGINT,@IsAdmin BIT=0 AS
BEGIN SET NOCOUNT ON; IF @RequiredWatchPercent NOT BETWEEN 0 AND 100 THROW 50001,N'Tỷ lệ xem bắt buộc không hợp lệ.',1; IF NOT EXISTS(SELECT 1 FROM dbo.Lessons l JOIN dbo.Courses c ON c.Id=l.CourseId WHERE l.Id=@LessonId AND l.IsDeleted=0 AND l.LessonType IN('VIDEO','INTERACTIVE_VIDEO') AND (@IsAdmin=1 OR c.TeacherId=@ActorId)) THROW 50003,N'Bạn không có quyền quản lý bài học này.',1; IF EXISTS(SELECT 1 FROM dbo.Videos WHERE LessonId=@LessonId) THROW 50006,N'Bài học đã có video.',1; DECLARE @Title NVARCHAR(500),@VideoUrl NVARCHAR(1000),@PosterUrl NVARCHAR(1000),@DurationSeconds INT; SELECT @Title=Title,@VideoUrl=VideoUrl,@PosterUrl=PosterUrl,@DurationSeconds=DurationSeconds FROM dbo.VideoAssets WHERE Id=@VideoAssetId AND IsDeleted=0 AND Status='ACTIVE'; IF @Title IS NULL THROW 50002,N'Không tìm thấy video trong thư viện.',1; INSERT dbo.Videos(LessonId,VideoAssetId,Title,VideoUrl,PosterUrl,DurationSeconds,AllowSeek,AllowSpeed,RequiredWatchPercent,Status) VALUES(@LessonId,@VideoAssetId,@Title,@VideoUrl,@PosterUrl,@DurationSeconds,@AllowSeek,@AllowSpeed,@RequiredWatchPercent,'ACTIVE'); DECLARE @Id BIGINT=SCOPE_IDENTITY(); UPDATE dbo.Lessons SET DurationSeconds=@DurationSeconds,UpdatedAt=SYSUTCDATETIME() WHERE Id=@LessonId; INSERT dbo.AuditLogs(UserId,Action,Module,EntityName,EntityId) VALUES(@ActorId,'ATTACH','VIDEO_LIBRARY','Video',CONVERT(NVARCHAR(100),@Id)); SELECT @Id; END
GO
CREATE OR ALTER PROCEDURE dbo.LMS_VideoInteraction_GetByVideo @VideoId BIGINT AS BEGIN SET NOCOUNT ON; SELECT vi.*,q.QuestionText,q.QuestionType FROM dbo.VideoInteractions vi JOIN dbo.Questions q ON q.Id=vi.QuestionId WHERE vi.VideoId=@VideoId AND vi.IsDeleted=0 ORDER BY vi.SortOrder,vi.TimeSeconds; END
GO
CREATE OR ALTER PROCEDURE dbo.LMS_VideoInteraction_Create @VideoId BIGINT,@QuestionId BIGINT,@TimeSeconds INT,@EndTimeSeconds INT=NULL,@InteractionType VARCHAR(50),@Required BIT,@PauseVideo BIT,@AllowSkip BIT,@Score DECIMAL(8,2),@AttemptLimit INT,@SortOrder INT,@Status VARCHAR(30),@ActorId BIGINT,@IsAdmin BIT=0 AS
BEGIN SET NOCOUNT ON; DECLARE @Duration INT=(SELECT v.DurationSeconds FROM dbo.Videos v JOIN dbo.Lessons l ON l.Id=v.LessonId JOIN dbo.Courses c ON c.Id=l.CourseId WHERE v.Id=@VideoId AND (@IsAdmin=1 OR c.TeacherId=@ActorId)); IF @Duration IS NULL THROW 50003,N'Bạn không có quyền quản lý video này.',1; IF NOT EXISTS(SELECT 1 FROM dbo.Questions WHERE Id=@QuestionId AND IsDeleted=0) OR @TimeSeconds<0 OR @TimeSeconds>@Duration OR @AttemptLimit<1 OR @Score<0 THROW 50001,N'Dữ liệu tương tác không hợp lệ.',1; INSERT dbo.VideoInteractions(VideoId,QuestionId,TimeSeconds,EndTimeSeconds,InteractionType,Required,PauseVideo,AllowSkip,Score,AttemptLimit,SortOrder,Status) VALUES(@VideoId,@QuestionId,@TimeSeconds,@EndTimeSeconds,@InteractionType,@Required,@PauseVideo,@AllowSkip,@Score,@AttemptLimit,@SortOrder,@Status); DECLARE @Id BIGINT=SCOPE_IDENTITY(); INSERT dbo.AuditLogs(UserId,Action,Module,EntityName,EntityId) VALUES(@ActorId,'CREATE','VIDEO_INTERACTION','VideoInteraction',CONVERT(NVARCHAR(100),@Id)); SELECT @Id; END
GO
CREATE OR ALTER PROCEDURE dbo.LMS_VideoInteraction_Update @Id BIGINT,@QuestionId BIGINT,@TimeSeconds INT,@EndTimeSeconds INT=NULL,@InteractionType VARCHAR(50),@Required BIT,@PauseVideo BIT,@AllowSkip BIT,@Score DECIMAL(8,2),@AttemptLimit INT,@SortOrder INT,@Status VARCHAR(30),@ActorId BIGINT,@IsAdmin BIT=0 AS
BEGIN SET NOCOUNT ON; DECLARE @Duration INT=(SELECT v.DurationSeconds FROM dbo.VideoInteractions vi JOIN dbo.Videos v ON v.Id=vi.VideoId JOIN dbo.Lessons l ON l.Id=v.LessonId JOIN dbo.Courses c ON c.Id=l.CourseId WHERE vi.Id=@Id AND vi.IsDeleted=0 AND (@IsAdmin=1 OR c.TeacherId=@ActorId)); IF @Duration IS NULL THROW 50003,N'Bạn không có quyền quản lý tương tác này.',1; IF NOT EXISTS(SELECT 1 FROM dbo.Questions WHERE Id=@QuestionId AND IsDeleted=0) OR @TimeSeconds<0 OR @TimeSeconds>@Duration OR @AttemptLimit<1 OR @Score<0 THROW 50001,N'Dữ liệu tương tác không hợp lệ.',1; UPDATE dbo.VideoInteractions SET QuestionId=@QuestionId,TimeSeconds=@TimeSeconds,EndTimeSeconds=@EndTimeSeconds,InteractionType=@InteractionType,Required=@Required,PauseVideo=@PauseVideo,AllowSkip=@AllowSkip,Score=@Score,AttemptLimit=@AttemptLimit,SortOrder=@SortOrder,Status=@Status,UpdatedAt=SYSUTCDATETIME() WHERE Id=@Id; INSERT dbo.AuditLogs(UserId,Action,Module,EntityName,EntityId) VALUES(@ActorId,'UPDATE','VIDEO_INTERACTION','VideoInteraction',CONVERT(NVARCHAR(100),@Id)); SELECT 1; END
GO
CREATE OR ALTER PROCEDURE dbo.LMS_VideoInteraction_Delete @Id BIGINT,@ActorId BIGINT,@IsAdmin BIT=0 AS
BEGIN SET NOCOUNT ON; UPDATE vi SET IsDeleted=1,UpdatedAt=SYSUTCDATETIME() FROM dbo.VideoInteractions vi JOIN dbo.Videos v ON v.Id=vi.VideoId JOIN dbo.Lessons l ON l.Id=v.LessonId JOIN dbo.Courses c ON c.Id=l.CourseId WHERE vi.Id=@Id AND vi.IsDeleted=0 AND (@IsAdmin=1 OR c.TeacherId=@ActorId); DECLARE @Rows INT=@@ROWCOUNT; IF @Rows>0 INSERT dbo.AuditLogs(UserId,Action,Module,EntityName,EntityId) VALUES(@ActorId,'DELETE','VIDEO_INTERACTION','VideoInteraction',CONVERT(NVARCHAR(100),@Id)); SELECT @Rows; END
GO
CREATE OR ALTER PROCEDURE dbo.LMS_VideoInteraction_Reorder @Id BIGINT,@SortOrder INT,@ActorId BIGINT,@IsAdmin BIT=0 AS
BEGIN SET NOCOUNT ON; UPDATE vi SET SortOrder=@SortOrder,UpdatedAt=SYSUTCDATETIME() FROM dbo.VideoInteractions vi JOIN dbo.Videos v ON v.Id=vi.VideoId JOIN dbo.Lessons l ON l.Id=v.LessonId JOIN dbo.Courses c ON c.Id=l.CourseId WHERE vi.Id=@Id AND vi.IsDeleted=0 AND (@IsAdmin=1 OR c.TeacherId=@ActorId); IF @@ROWCOUNT=0 THROW 50003,N'Không thể sắp xếp tương tác này.',1; END
GO
