CREATE OR ALTER PROCEDURE dbo.LMS_Question_GetList @Search NVARCHAR(500)=NULL,@Type VARCHAR(50)=NULL,@Page INT=1,@PageSize INT=20 AS
BEGIN SET NOCOUNT ON; SELECT q.Id,q.QuestionType,q.QuestionText,q.Difficulty,q.DefaultScore,q.Status,u.FullName CreatedBy,q.CreatedAt,(SELECT COUNT(*) FROM dbo.VideoInteractions vi WHERE vi.QuestionId=q.Id AND vi.IsDeleted=0) UsedCount FROM dbo.Questions q JOIN dbo.Users u ON u.Id=q.CreatedBy WHERE q.IsDeleted=0 AND (@Type IS NULL OR @Type='' OR q.QuestionType=@Type) AND (@Search IS NULL OR @Search='' OR q.QuestionText LIKE '%'+@Search+'%') ORDER BY q.CreatedAt DESC OFFSET (@Page-1)*@PageSize ROWS FETCH NEXT @PageSize ROWS ONLY; SELECT COUNT(*) FROM dbo.Questions q WHERE q.IsDeleted=0 AND (@Type IS NULL OR @Type='' OR q.QuestionType=@Type) AND (@Search IS NULL OR @Search='' OR q.QuestionText LIKE '%'+@Search+'%'); END
GO
CREATE OR ALTER PROCEDURE dbo.LMS_Question_GetById @Id BIGINT AS
BEGIN SET NOCOUNT ON; SELECT Id,QuestionType,QuestionText,Description,Explanation,Difficulty,DefaultScore,ShortAnswerMode,CreatedBy,CreatedAt,UpdatedAt,Status FROM dbo.Questions WHERE Id=@Id AND IsDeleted=0; SELECT Id,QuestionId,OptionCode,OptionText,IsCorrect,SortOrder FROM dbo.QuestionOptions WHERE QuestionId=@Id AND IsDeleted=0 ORDER BY SortOrder; SELECT Id,QuestionId,AnswerText,IsCaseSensitive,SortOrder FROM dbo.QuestionAnswerKeys WHERE QuestionId=@Id ORDER BY SortOrder; END
GO
CREATE OR ALTER PROCEDURE dbo.LMS_Question_Create @Id BIGINT=NULL,@QuestionType VARCHAR(50),@QuestionText NVARCHAR(MAX),@Description NVARCHAR(MAX)=NULL,@Explanation NVARCHAR(MAX)=NULL,@Difficulty VARCHAR(30),@DefaultScore DECIMAL(8,2),@ShortAnswerMode VARCHAR(30)=NULL,@Status VARCHAR(30),@ActorId BIGINT AS
BEGIN SET NOCOUNT ON; IF @QuestionType NOT IN('SINGLE_CHOICE','MULTIPLE_CHOICE','TRUE_FALSE','SHORT_ANSWER') OR NULLIF(LTRIM(RTRIM(@QuestionText)),'') IS NULL OR @DefaultScore<0 THROW 50001,N'Dữ liệu câu hỏi không hợp lệ.',1; INSERT dbo.Questions(QuestionType,QuestionText,Description,Explanation,Difficulty,DefaultScore,ShortAnswerMode,CreatedBy,Status) VALUES(@QuestionType,@QuestionText,@Description,@Explanation,@Difficulty,@DefaultScore,@ShortAnswerMode,@ActorId,@Status); DECLARE @QuestionId BIGINT=SCOPE_IDENTITY(); INSERT dbo.AuditLogs(UserId,Action,Module,EntityName,EntityId) VALUES(@ActorId,'CREATE','QUESTION','Question',CONVERT(NVARCHAR(100),@QuestionId)); SELECT @QuestionId; END
GO
CREATE OR ALTER PROCEDURE dbo.LMS_Question_Update @Id BIGINT,@QuestionType VARCHAR(50),@QuestionText NVARCHAR(MAX),@Description NVARCHAR(MAX)=NULL,@Explanation NVARCHAR(MAX)=NULL,@Difficulty VARCHAR(30),@DefaultScore DECIMAL(8,2),@ShortAnswerMode VARCHAR(30)=NULL,@Status VARCHAR(30),@ActorId BIGINT AS
BEGIN SET NOCOUNT ON; IF @QuestionType NOT IN('SINGLE_CHOICE','MULTIPLE_CHOICE','TRUE_FALSE','SHORT_ANSWER') OR NULLIF(LTRIM(RTRIM(@QuestionText)),'') IS NULL OR @DefaultScore<0 THROW 50001,N'Dữ liệu câu hỏi không hợp lệ.',1; UPDATE dbo.Questions SET QuestionType=@QuestionType,QuestionText=@QuestionText,Description=@Description,Explanation=@Explanation,Difficulty=@Difficulty,DefaultScore=@DefaultScore,ShortAnswerMode=@ShortAnswerMode,Status=@Status,UpdatedAt=SYSUTCDATETIME() WHERE Id=@Id AND IsDeleted=0; IF @@ROWCOUNT=0 THROW 50002,N'Không tìm thấy câu hỏi.',1; INSERT dbo.AuditLogs(UserId,Action,Module,EntityName,EntityId) VALUES(@ActorId,'UPDATE','QUESTION','Question',CONVERT(NVARCHAR(100),@Id)); SELECT @Id; END
GO
CREATE OR ALTER PROCEDURE dbo.LMS_QuestionAnswers_DeleteByQuestion @QuestionId BIGINT AS BEGIN SET NOCOUNT ON; UPDATE dbo.QuestionOptions SET IsDeleted=1 WHERE QuestionId=@QuestionId; DELETE FROM dbo.QuestionAnswerKeys WHERE QuestionId=@QuestionId; END
GO
CREATE OR ALTER PROCEDURE dbo.LMS_QuestionOption_Create @QuestionId BIGINT,@OptionCode NVARCHAR(20),@OptionText NVARCHAR(2000),@IsCorrect BIT,@SortOrder INT AS BEGIN SET NOCOUNT ON; IF NULLIF(LTRIM(RTRIM(@OptionCode)),'') IS NULL OR NULLIF(LTRIM(RTRIM(@OptionText)),'') IS NULL THROW 50001,N'Phương án trả lời không hợp lệ.',1; SET @OptionCode=UPPER(LTRIM(RTRIM(@OptionCode))); IF EXISTS(SELECT 1 FROM dbo.QuestionOptions WHERE QuestionId=@QuestionId AND OptionCode=@OptionCode) UPDATE dbo.QuestionOptions SET OptionText=@OptionText,IsCorrect=@IsCorrect,SortOrder=@SortOrder,IsDeleted=0 WHERE QuestionId=@QuestionId AND OptionCode=@OptionCode; ELSE INSERT dbo.QuestionOptions(QuestionId,OptionCode,OptionText,IsCorrect,SortOrder,IsDeleted) VALUES(@QuestionId,@OptionCode,@OptionText,@IsCorrect,@SortOrder,0); END
GO
CREATE OR ALTER PROCEDURE dbo.LMS_QuestionAnswerKey_Create @QuestionId BIGINT,@AnswerText NVARCHAR(2000),@IsCaseSensitive BIT,@SortOrder INT AS BEGIN SET NOCOUNT ON; IF NULLIF(LTRIM(RTRIM(@AnswerText)),'') IS NULL THROW 50001,N'Đáp án mẫu không hợp lệ.',1; INSERT dbo.QuestionAnswerKeys(QuestionId,AnswerText,IsCaseSensitive,SortOrder) VALUES(@QuestionId,@AnswerText,@IsCaseSensitive,@SortOrder); END
GO
CREATE OR ALTER PROCEDURE dbo.LMS_Question_Delete @Id BIGINT,@ActorId BIGINT AS BEGIN SET NOCOUNT ON; UPDATE dbo.Questions SET IsDeleted=1,UpdatedAt=SYSUTCDATETIME() WHERE Id=@Id AND IsDeleted=0; DECLARE @Rows INT=@@ROWCOUNT; IF @Rows>0 BEGIN UPDATE dbo.VideoInteractions SET IsDeleted=1,UpdatedAt=SYSUTCDATETIME() WHERE QuestionId=@Id AND IsDeleted=0; INSERT dbo.AuditLogs(UserId,Action,Module,EntityName,EntityId) VALUES(@ActorId,'DELETE','QUESTION','Question',CONVERT(NVARCHAR(100),@Id)); END; SELECT @Rows; END
GO
