using System.Security.Claims;
using LmsCms.Application.Common;
using LmsCms.Application.DTOs;
using LmsCms.Application.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace LmsCms.Api.Controllers;
[ApiController,Route("api"),Authorize(Roles="ADMIN,TEACHER")]
public sealed class ContentController(IContentService content):ControllerBase
{
 private long UserId=>long.Parse(User.FindFirstValue("userId")!);private bool IsAdmin=>User.IsInRole("ADMIN");
 [HttpGet("courses/{courseId:long}/chapters")] public async Task<ActionResult<ApiResponse<object>>> Chapters(long courseId,CancellationToken ct)=>Ok(ApiResponse<object>.Ok(await content.GetChaptersAsync(courseId,UserId,IsAdmin,ct)));
 [HttpPost("courses/{courseId:long}/chapters")] public async Task<ActionResult<ApiResponse<object>>> CreateChapter(long courseId,ChapterSaveRequest r,CancellationToken ct){var id=await content.CreateChapterAsync(courseId,r,UserId,IsAdmin,ct);return Ok(ApiResponse<object>.Ok(new{id}));}
 [HttpPut("chapters/{id:long}")] public async Task<ActionResult<ApiResponse<object>>> UpdateChapter(long id,ChapterSaveRequest r,CancellationToken ct)=>await content.UpdateChapterAsync(id,r,UserId,IsAdmin,ct)?Ok(ApiResponse<object>.Ok(new{id})):NotFound(ApiResponse<object>.Fail("Không tìm thấy chương."));
 [HttpDelete("chapters/{id:long}")] public async Task<ActionResult<ApiResponse<object>>> DeleteChapter(long id,CancellationToken ct)=>await content.DeleteChapterAsync(id,UserId,IsAdmin,ct)?Ok(ApiResponse<object>.Ok(new{id})):NotFound(ApiResponse<object>.Fail("Không tìm thấy chương."));
 [HttpPost("chapters/reorder")] public async Task<ActionResult<ApiResponse<object>>> ReorderChapters(ReorderRequest r,CancellationToken ct){await content.ReorderChaptersAsync(r,UserId,IsAdmin,ct);return Ok(ApiResponse<object>.Ok(new{}));}
 [HttpGet("lessons/{id:long}")] public async Task<ActionResult<ApiResponse<object>>> Lesson(long id,CancellationToken ct){var x=await content.GetLessonAsync(id,UserId,IsAdmin,ct);return x is null?NotFound(ApiResponse<object>.Fail("Không tìm thấy bài học.")):Ok(ApiResponse<object>.Ok(x));}
 [HttpPost("chapters/{chapterId:long}/lessons")] public async Task<ActionResult<ApiResponse<object>>> CreateLesson(long chapterId,LessonSaveRequest r,CancellationToken ct){var id=await content.CreateLessonAsync(chapterId,r,UserId,IsAdmin,ct);return Ok(ApiResponse<object>.Ok(new{id}));}
 [HttpPut("lessons/{id:long}")] public async Task<ActionResult<ApiResponse<object>>> UpdateLesson(long id,LessonSaveRequest r,CancellationToken ct)=>await content.UpdateLessonAsync(id,r,UserId,IsAdmin,ct)?Ok(ApiResponse<object>.Ok(new{id})):NotFound(ApiResponse<object>.Fail("Không tìm thấy bài học."));
 [HttpDelete("lessons/{id:long}")] public async Task<ActionResult<ApiResponse<object>>> DeleteLesson(long id,CancellationToken ct)=>await content.DeleteLessonAsync(id,UserId,IsAdmin,ct)?Ok(ApiResponse<object>.Ok(new{id})):NotFound(ApiResponse<object>.Fail("Không tìm thấy bài học."));
 [HttpPost("lessons/reorder")] public async Task<ActionResult<ApiResponse<object>>> ReorderLessons(ReorderRequest r,CancellationToken ct){await content.ReorderLessonsAsync(r,UserId,IsAdmin,ct);return Ok(ApiResponse<object>.Ok(new{}));}
 [HttpGet("videos/{id:long}")] public async Task<ActionResult<ApiResponse<object>>> Video(long id,CancellationToken ct){var x=await content.GetVideoAsync(id,UserId,IsAdmin,ct);return x is null?NotFound(ApiResponse<object>.Fail("Không tìm thấy video.")):Ok(ApiResponse<object>.Ok(x));}
 [HttpPost("lessons/{lessonId:long}/video")] public async Task<ActionResult<ApiResponse<object>>> CreateVideo(long lessonId,VideoSaveRequest r,CancellationToken ct){var id=await content.SaveVideoAsync(null,lessonId,r,UserId,IsAdmin,ct);return Ok(ApiResponse<object>.Ok(new{id}));}
 [HttpPut("videos/{id:long}")] public async Task<ActionResult<ApiResponse<object>>> UpdateVideo(long id,VideoSaveRequest r,CancellationToken ct){var saved=await content.SaveVideoAsync(id,r.LessonId,r,UserId,IsAdmin,ct);return Ok(ApiResponse<object>.Ok(new{id=saved}));}
 [HttpGet("video-library")] public async Task<ActionResult<ApiResponse<object>>> VideoLibrary([FromQuery]string? search,[FromQuery]string? access,[FromQuery]string? source,[FromQuery]string? usage,[FromQuery]string? status,CancellationToken ct)=>Ok(ApiResponse<object>.Ok(await content.GetVideoLibraryAsync(search,access,source,usage,status,UserId,IsAdmin,ct)));
 [HttpGet("video-library/{id:long}/usage")] public async Task<ActionResult<ApiResponse<object>>> VideoUsage(long id,CancellationToken ct)=>Ok(ApiResponse<object>.Ok(await content.GetVideoUsageAsync(id,UserId,IsAdmin,ct)));
 [HttpPost("video-library")] public async Task<ActionResult<ApiResponse<object>>> CreateVideoAsset(VideoAssetSaveRequest r,CancellationToken ct){var id=await content.CreateVideoAssetAsync(r,UserId,ct);return Ok(ApiResponse<object>.Ok(new{id}));}
 [HttpPut("video-library/{id:long}")] public async Task<ActionResult<ApiResponse<object>>> UpdateVideoAsset(long id,VideoAssetSaveRequest r,CancellationToken ct)=>await content.UpdateVideoAssetAsync(id,r,UserId,IsAdmin,ct)?Ok(ApiResponse<object>.Ok(new{id})):NotFound(ApiResponse<object>.Fail("Không tìm thấy video thư viện."));
 [HttpPost("video-library/{id:long}/duplicate")] public async Task<ActionResult<ApiResponse<object>>> DuplicateVideoAsset(long id,VideoDuplicateRequest r,CancellationToken ct){var videoId=await content.DuplicateVideoAssetAsync(id,r,UserId,IsAdmin,ct);return Ok(ApiResponse<object>.Ok(new{id=videoId}));}
 [HttpDelete("video-library/{id:long}")] public async Task<ActionResult<ApiResponse<object>>> DeleteVideoAsset(long id,CancellationToken ct)=>await content.DeleteVideoAssetAsync(id,UserId,IsAdmin,ct)?Ok(ApiResponse<object>.Ok(new{id})):NotFound(ApiResponse<object>.Fail("Không tìm thấy video thư viện."));
 [HttpGet("video-library/{id:long}/sharing")] public async Task<ActionResult<ApiResponse<object>>> GetVideoSharing(long id,CancellationToken ct)=>Ok(ApiResponse<object>.Ok(await content.GetVideoSharingAsync(id,UserId,IsAdmin,ct)));
 [HttpPut("video-library/{id:long}/sharing")] public async Task<ActionResult<ApiResponse<object>>> SaveVideoSharing(long id,VideoShareSaveRequest r,CancellationToken ct){await content.SaveVideoSharingAsync(id,r,UserId,IsAdmin,ct);return Ok(ApiResponse<object>.Ok(new{id}));}
 [HttpPost("lessons/{lessonId:long}/video-library/{assetId:long}")] public async Task<ActionResult<ApiResponse<object>>> AttachVideoAsset(long lessonId,long assetId,VideoAttachRequest r,CancellationToken ct){var id=await content.AttachVideoAssetAsync(lessonId,assetId,r,UserId,IsAdmin,ct);return Ok(ApiResponse<object>.Ok(new{id}));}
 [HttpPut("lessons/{lessonId:long}/video/{videoId:long}")] public async Task<ActionResult<ApiResponse<object>>> AttachVideo(long lessonId,long videoId,CancellationToken ct){var id=await content.AttachVideoAsync(lessonId,videoId,UserId,IsAdmin,ct);return Ok(ApiResponse<object>.Ok(new{id}));}
 [HttpGet("videos/{videoId:long}/interactions")] public async Task<ActionResult<ApiResponse<object>>> Interactions(long videoId,CancellationToken ct)=>Ok(ApiResponse<object>.Ok(await content.GetInteractionsAsync(videoId,UserId,IsAdmin,ct)));
 [HttpPost("videos/{videoId:long}/preview-answer")] public async Task<ActionResult<ApiResponse<PreviewAnswerResultDto>>> PreviewAnswer(long videoId,PreviewAnswerRequest r,CancellationToken ct)=>Ok(ApiResponse<PreviewAnswerResultDto>.Ok(await content.PreviewAnswerAsync(videoId,r,UserId,IsAdmin,ct)));
 [HttpPost("videos/{videoId:long}/interactions")] public async Task<ActionResult<ApiResponse<object>>> CreateInteraction(long videoId,InteractionSaveRequest r,CancellationToken ct){var id=await content.CreateInteractionAsync(videoId,r,UserId,IsAdmin,ct);return Ok(ApiResponse<object>.Ok(new{id}));}
 [HttpPut("video-interactions/{id:long}")] public async Task<ActionResult<ApiResponse<object>>> UpdateInteraction(long id,InteractionSaveRequest r,CancellationToken ct)=>await content.UpdateInteractionAsync(id,r,UserId,IsAdmin,ct)?Ok(ApiResponse<object>.Ok(new{id})):NotFound(ApiResponse<object>.Fail("Không tìm thấy tương tác."));
 [HttpDelete("video-interactions/{id:long}")] public async Task<ActionResult<ApiResponse<object>>> DeleteInteraction(long id,CancellationToken ct)=>await content.DeleteInteractionAsync(id,UserId,IsAdmin,ct)?Ok(ApiResponse<object>.Ok(new{id})):NotFound(ApiResponse<object>.Fail("Không tìm thấy tương tác."));
 [HttpPost("video-interactions/reorder")] public async Task<ActionResult<ApiResponse<object>>> ReorderInteractions(ReorderRequest r,CancellationToken ct){await content.ReorderInteractionsAsync(r,UserId,IsAdmin,ct);return Ok(ApiResponse<object>.Ok(new{}));}
 [HttpGet("lessons/{lessonId:long}/interactive-content")] public async Task<ActionResult<ApiResponse<object>>> GetInteractiveContent(long lessonId,CancellationToken ct)=>Ok(ApiResponse<object>.Ok(await content.GetInteractiveContentForTeacherAsync(lessonId,UserId,IsAdmin,ct)));
 [HttpPut("lessons/{lessonId:long}/interactive-content/settings")] public async Task<ActionResult<ApiResponse<object>>> SaveInteractiveContentSettings(long lessonId,InteractiveContentSettingsRequest r,CancellationToken ct){var id=await content.SaveInteractiveContentSettingsAsync(lessonId,r,UserId,IsAdmin,ct);return Ok(ApiResponse<object>.Ok(new{id}));}
 [HttpPost("lessons/{lessonId:long}/content-interactions")] public async Task<ActionResult<ApiResponse<object>>> CreateContentInteraction(long lessonId,ContentInteractionSaveRequest r,CancellationToken ct){var id=await content.CreateContentInteractionAsync(lessonId,r,UserId,IsAdmin,ct);return Ok(ApiResponse<object>.Ok(new{id}));}
 [HttpPut("content-interactions/{id:long}")] public async Task<ActionResult<ApiResponse<object>>> UpdateContentInteraction(long id,ContentInteractionSaveRequest r,CancellationToken ct)=>await content.UpdateContentInteractionAsync(id,r,UserId,IsAdmin,ct)?Ok(ApiResponse<object>.Ok(new{id})):NotFound(ApiResponse<object>.Fail("Không tìm thấy câu hỏi tương tác."));
 [HttpDelete("content-interactions/{id:long}")] public async Task<ActionResult<ApiResponse<object>>> DeleteContentInteraction(long id,CancellationToken ct)=>await content.DeleteContentInteractionAsync(id,UserId,IsAdmin,ct)?Ok(ApiResponse<object>.Ok(new{id})):NotFound(ApiResponse<object>.Fail("Không tìm thấy câu hỏi tương tác."));
 [HttpPost("content-interactions/reorder")] public async Task<ActionResult<ApiResponse<object>>> ReorderContentInteractions(ReorderRequest r,CancellationToken ct){await content.ReorderContentInteractionsAsync(r,UserId,IsAdmin,ct);return Ok(ApiResponse<object>.Ok(new{}));}
}
