IF OBJECT_ID('dbo.Roles','U') IS NULL CREATE TABLE dbo.Roles(
 Id BIGINT IDENTITY PRIMARY KEY, Code VARCHAR(50) NOT NULL, Name NVARCHAR(150) NOT NULL, Description NVARCHAR(500) NULL, Status VARCHAR(30) NOT NULL CONSTRAINT DF_Roles_Status DEFAULT 'ACTIVE', CONSTRAINT UQ_Roles_Code UNIQUE(Code));
GO
IF OBJECT_ID('dbo.Users','U') IS NULL CREATE TABLE dbo.Users(
 Id BIGINT IDENTITY PRIMARY KEY, Username NVARCHAR(100) NOT NULL, PasswordHash NVARCHAR(500) NOT NULL, FullName NVARCHAR(250) NOT NULL, Email NVARCHAR(250) NOT NULL,
 StudentCode NVARCHAR(100) NULL, TeacherCode NVARCHAR(100) NULL, AvatarUrl NVARCHAR(1000) NULL, Status VARCHAR(30) NOT NULL CONSTRAINT DF_Users_Status DEFAULT 'ACTIVE',
 LastLoginAt DATETIME2 NULL, CreatedAt DATETIME2 NOT NULL CONSTRAINT DF_Users_Created DEFAULT SYSUTCDATETIME(), UpdatedAt DATETIME2 NULL, CreatedBy BIGINT NULL, UpdatedBy BIGINT NULL, IsDeleted BIT NOT NULL CONSTRAINT DF_Users_Deleted DEFAULT 0,
 CONSTRAINT UQ_Users_Username UNIQUE(Username), CONSTRAINT UQ_Users_Email UNIQUE(Email), CONSTRAINT CK_Users_Status CHECK(Status IN('ACTIVE','INACTIVE','LOCKED')));
GO
IF OBJECT_ID('dbo.UserRoles','U') IS NULL CREATE TABLE dbo.UserRoles(UserId BIGINT NOT NULL,RoleId BIGINT NOT NULL,CONSTRAINT PK_UserRoles PRIMARY KEY(UserId,RoleId),CONSTRAINT FK_UserRoles_User FOREIGN KEY(UserId) REFERENCES dbo.Users(Id),CONSTRAINT FK_UserRoles_Role FOREIGN KEY(RoleId) REFERENCES dbo.Roles(Id));
GO
IF OBJECT_ID('dbo.Permissions','U') IS NULL CREATE TABLE dbo.Permissions(Id BIGINT IDENTITY PRIMARY KEY,Code VARCHAR(100) NOT NULL UNIQUE,Name NVARCHAR(200) NOT NULL,Module VARCHAR(100) NOT NULL,Description NVARCHAR(500) NULL);
GO
IF OBJECT_ID('dbo.RolePermissions','U') IS NULL CREATE TABLE dbo.RolePermissions(RoleId BIGINT NOT NULL,PermissionId BIGINT NOT NULL,CONSTRAINT PK_RolePermissions PRIMARY KEY(RoleId,PermissionId),CONSTRAINT FK_RolePermissions_Role FOREIGN KEY(RoleId) REFERENCES dbo.Roles(Id),CONSTRAINT FK_RolePermissions_Permission FOREIGN KEY(PermissionId) REFERENCES dbo.Permissions(Id));
GO
IF OBJECT_ID('dbo.RefreshTokens','U') IS NULL CREATE TABLE dbo.RefreshTokens(Id BIGINT IDENTITY PRIMARY KEY,UserId BIGINT NOT NULL,TokenHash VARCHAR(128) NOT NULL UNIQUE,ExpiresAt DATETIME2 NOT NULL,CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),RevokedAt DATETIME2 NULL,CreatedIp VARCHAR(64) NULL,RevokedIp VARCHAR(64) NULL,IsRevoked BIT NOT NULL DEFAULT 0,CONSTRAINT FK_RefreshTokens_User FOREIGN KEY(UserId) REFERENCES dbo.Users(Id));
GO
IF OBJECT_ID('dbo.AuditLogs','U') IS NULL CREATE TABLE dbo.AuditLogs(Id BIGINT IDENTITY PRIMARY KEY,UserId BIGINT NULL,Action VARCHAR(100) NOT NULL,Module VARCHAR(100) NOT NULL,EntityName VARCHAR(100) NOT NULL,EntityId NVARCHAR(100) NULL,OldValuesJson NVARCHAR(MAX) NULL,NewValuesJson NVARCHAR(MAX) NULL,IpAddress VARCHAR(64) NULL,UserAgent NVARCHAR(1000) NULL,CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
GO
